// Decompiled with JetBrains decompiler
// Type: BaseStatsLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

#nullable disable
public class BaseStatsLibrary : AssetLibrary<BaseStatAsset>
{
  public override void init()
  {
    base.init();
    BaseStatAsset pAsset1 = new BaseStatAsset();
    pAsset1.id = "personality_aggression";
    pAsset1.hidden = true;
    pAsset1.normalize = true;
    pAsset1.normalize_min = 0.0f;
    pAsset1.normalize_max = 1f;
    pAsset1.used_only_for_civs = true;
    this.add(pAsset1);
    BaseStatAsset pAsset2 = new BaseStatAsset();
    pAsset2.id = "personality_administration";
    pAsset2.hidden = true;
    pAsset2.normalize = true;
    pAsset2.normalize_min = 0.0f;
    pAsset2.normalize_max = 1f;
    pAsset2.used_only_for_civs = true;
    this.add(pAsset2);
    BaseStatAsset pAsset3 = new BaseStatAsset();
    pAsset3.id = "personality_diplomatic";
    pAsset3.hidden = true;
    pAsset3.normalize = true;
    pAsset3.normalize_min = 0.0f;
    pAsset3.normalize_max = 1f;
    pAsset3.used_only_for_civs = true;
    this.add(pAsset3);
    BaseStatAsset pAsset4 = new BaseStatAsset();
    pAsset4.id = "personality_rationality";
    pAsset4.hidden = true;
    pAsset4.normalize = true;
    pAsset4.normalize_min = 0.0f;
    pAsset4.normalize_max = 1f;
    pAsset4.used_only_for_civs = true;
    this.add(pAsset4);
    BaseStatAsset pAsset5 = new BaseStatAsset();
    pAsset5.id = "diplomacy";
    pAsset5.actor_data_attribute = true;
    pAsset5.normalize = true;
    pAsset5.normalize_max = 999f;
    pAsset5.used_only_for_civs = true;
    pAsset5.sort_rank = 900;
    this.add(pAsset5);
    BaseStatAsset pAsset6 = new BaseStatAsset();
    pAsset6.id = "warfare";
    pAsset6.actor_data_attribute = true;
    pAsset6.normalize = true;
    pAsset6.normalize_max = 999f;
    pAsset6.used_only_for_civs = true;
    pAsset6.sort_rank = 900;
    this.add(pAsset6);
    BaseStatAsset pAsset7 = new BaseStatAsset();
    pAsset7.id = "stewardship";
    pAsset7.actor_data_attribute = true;
    pAsset7.normalize = true;
    pAsset7.normalize_max = 999f;
    pAsset7.used_only_for_civs = true;
    pAsset7.sort_rank = 900;
    this.add(pAsset7);
    BaseStatAsset pAsset8 = new BaseStatAsset();
    pAsset8.id = "intelligence";
    pAsset8.actor_data_attribute = true;
    pAsset8.normalize = true;
    pAsset8.normalize_max = 999f;
    pAsset8.used_only_for_civs = true;
    pAsset8.sort_rank = 900;
    this.add(pAsset8);
    BaseStatAsset pAsset9 = new BaseStatAsset();
    pAsset9.id = "lifespan";
    pAsset9.sort_rank = 997;
    pAsset9.normalize = true;
    pAsset9.normalize_min = 1f;
    this.add(pAsset9);
    BaseStatAsset pAsset10 = new BaseStatAsset();
    pAsset10.id = "mutation";
    pAsset10.sort_rank = 996;
    this.add(pAsset10);
    BaseStatAsset pAsset11 = new BaseStatAsset();
    pAsset11.id = "offspring";
    pAsset11.normalize = true;
    pAsset11.normalize_min = 0.0f;
    pAsset11.normalize_max = 1000f;
    this.add(pAsset11);
    BaseStatAsset pAsset12 = new BaseStatAsset();
    pAsset12.id = "multiplier_offspring";
    pAsset12.show_as_percents = true;
    pAsset12.multiplier = true;
    pAsset12.main_stat_to_multiply = "offspring";
    pAsset12.tooltip_multiply_for_visual_number = 100f;
    pAsset12.translation_key = "offspring";
    this.add(pAsset12);
    BaseStatAsset pAsset13 = new BaseStatAsset();
    pAsset13.id = "army";
    pAsset13.normalize = true;
    pAsset13.normalize_min = 0.1f;
    pAsset13.used_only_for_civs = true;
    this.add(pAsset13);
    BaseStatAsset pAsset14 = new BaseStatAsset();
    pAsset14.id = "cities";
    pAsset14.used_only_for_civs = true;
    this.add(pAsset14);
    BaseStatAsset pAsset15 = new BaseStatAsset();
    pAsset15.id = "range";
    this.add(pAsset15);
    BaseStatAsset pAsset16 = new BaseStatAsset();
    pAsset16.id = "bonus_towers";
    pAsset16.normalize = true;
    pAsset16.normalize_max = 2f;
    pAsset16.used_only_for_civs = true;
    this.add(pAsset16);
    BaseStatAsset pAsset17 = new BaseStatAsset();
    pAsset17.id = "damage";
    pAsset17.normalize = true;
    pAsset17.normalize_min = 1f;
    pAsset17.sort_rank = 999;
    this.add(pAsset17);
    BaseStatAsset pAsset18 = new BaseStatAsset();
    pAsset18.id = "speed";
    pAsset18.normalize = true;
    pAsset18.normalize_min = 1f;
    pAsset18.sort_rank = 998;
    this.add(pAsset18);
    BaseStatAsset pAsset19 = new BaseStatAsset();
    pAsset19.id = "health";
    pAsset19.normalize = true;
    pAsset19.normalize_min = 1f;
    pAsset19.sort_rank = 1000;
    this.add(pAsset19);
    BaseStatAsset pAsset20 = new BaseStatAsset();
    pAsset20.id = "armor";
    pAsset20.normalize = true;
    pAsset20.normalize_min = 0.0f;
    pAsset20.normalize_max = 99f;
    this.add(pAsset20);
    BaseStatAsset pAsset21 = new BaseStatAsset();
    pAsset21.id = "stamina";
    pAsset21.normalize = true;
    pAsset21.normalize_min = 1f;
    pAsset21.sort_rank = 1000;
    this.add(pAsset21);
    BaseStatAsset pAsset22 = new BaseStatAsset();
    pAsset22.id = "mana";
    pAsset22.normalize = true;
    pAsset22.normalize_min = 0.0f;
    pAsset22.sort_rank = 1000;
    this.add(pAsset22);
    BaseStatAsset pAsset23 = new BaseStatAsset();
    pAsset23.id = "accuracy";
    pAsset23.normalize_min = 1f;
    pAsset23.normalize_max = 10f;
    pAsset23.normalize = true;
    this.add(pAsset23);
    BaseStatAsset pAsset24 = new BaseStatAsset();
    pAsset24.id = "targets";
    pAsset24.hidden = true;
    this.add(pAsset24);
    BaseStatAsset pAsset25 = new BaseStatAsset();
    pAsset25.id = "projectiles";
    pAsset25.normalize = true;
    pAsset25.normalize_min = 1f;
    pAsset25.hidden = true;
    this.add(pAsset25);
    BaseStatAsset pAsset26 = new BaseStatAsset();
    pAsset26.id = "experience";
    this.add(pAsset26);
    BaseStatAsset pAsset27 = new BaseStatAsset();
    pAsset27.id = "happiness";
    pAsset27.normalize = true;
    pAsset27.normalize_min = 0.0f;
    this.add(pAsset27);
    BaseStatAsset pAsset28 = new BaseStatAsset();
    pAsset28.id = "critical_chance";
    pAsset28.normalize = true;
    pAsset28.normalize_min = 0.0f;
    pAsset28.show_as_percents = true;
    pAsset28.tooltip_multiply_for_visual_number = 100f;
    this.add(pAsset28);
    BaseStatAsset pAsset29 = new BaseStatAsset();
    pAsset29.id = "critical_damage_multiplier";
    pAsset29.show_as_percents = true;
    pAsset29.tooltip_multiply_for_visual_number = 100f;
    this.add(pAsset29);
    BaseStatAsset pAsset30 = new BaseStatAsset();
    pAsset30.id = "size";
    pAsset30.hidden = true;
    this.add(pAsset30);
    BaseStatAsset pAsset31 = new BaseStatAsset();
    pAsset31.id = "area_of_effect";
    pAsset31.hidden = true;
    this.add(pAsset31);
    BaseStatAsset pAsset32 = new BaseStatAsset();
    pAsset32.id = "attack_speed";
    pAsset32.normalize = true;
    pAsset32.normalize_min = 0.5f;
    pAsset32.normalize_max = 10f;
    this.add(pAsset32);
    BaseStatAsset pAsset33 = new BaseStatAsset();
    pAsset33.id = "throwing_range";
    pAsset33.normalize = true;
    pAsset33.normalize_min = 1f;
    pAsset33.normalize_max = 100f;
    this.add(pAsset33);
    BaseStatAsset pAsset34 = new BaseStatAsset();
    pAsset34.id = "construction_speed";
    pAsset34.normalize = true;
    pAsset34.normalize_min = 1f;
    pAsset34.normalize_max = 100f;
    this.add(pAsset34);
    BaseStatAsset pAsset35 = new BaseStatAsset();
    pAsset35.id = "loyalty_traits";
    pAsset35.translation_key = "loyalty";
    pAsset35.used_only_for_civs = true;
    this.add(pAsset35);
    BaseStatAsset pAsset36 = new BaseStatAsset();
    pAsset36.id = "birth_rate";
    pAsset36.translation_key = "birth_rate";
    this.add(pAsset36);
    BaseStatAsset pAsset37 = new BaseStatAsset();
    pAsset37.id = "maturation";
    pAsset37.translation_key = "maturation";
    this.add(pAsset37);
    BaseStatAsset pAsset38 = new BaseStatAsset();
    pAsset38.id = "age_adult";
    pAsset38.translation_key = "age_adult";
    pAsset38.hidden = true;
    this.add(pAsset38);
    BaseStatAsset pAsset39 = new BaseStatAsset();
    pAsset39.id = "age_breeding";
    pAsset39.translation_key = "age_breeding";
    pAsset39.hidden = true;
    this.add(pAsset39);
    BaseStatAsset pAsset40 = new BaseStatAsset();
    pAsset40.id = "max_nutrition";
    pAsset40.translation_key = "max_nutrition";
    this.add(pAsset40);
    BaseStatAsset pAsset41 = new BaseStatAsset();
    pAsset41.id = "metabolic_rate";
    pAsset41.translation_key = "metabolic_rate";
    pAsset41.normalize_min = 1f;
    pAsset41.hidden = true;
    this.add(pAsset41);
    BaseStatAsset pAsset42 = new BaseStatAsset();
    pAsset42.id = "loyalty_mood";
    pAsset42.translation_key = "loyalty";
    pAsset42.used_only_for_civs = true;
    this.add(pAsset42);
    BaseStatAsset pAsset43 = new BaseStatAsset();
    pAsset43.id = "opinion";
    pAsset43.used_only_for_civs = true;
    this.add(pAsset43);
    BaseStatAsset pAsset44 = new BaseStatAsset();
    pAsset44.id = "skill_combat";
    pAsset44.show_as_percents = true;
    pAsset44.tooltip_multiply_for_visual_number = 100f;
    this.add(pAsset44);
    BaseStatAsset pAsset45 = new BaseStatAsset();
    pAsset45.id = "skill_spell";
    pAsset45.show_as_percents = true;
    pAsset45.tooltip_multiply_for_visual_number = 100f;
    this.add(pAsset45);
    BaseStatAsset pAsset46 = new BaseStatAsset();
    pAsset46.id = "knockback";
    this.add(pAsset46);
    BaseStatAsset pAsset47 = new BaseStatAsset();
    pAsset47.id = "recoil";
    this.add(pAsset47);
    BaseStatAsset pAsset48 = new BaseStatAsset();
    pAsset48.id = "mass";
    this.add(pAsset48);
    BaseStatAsset pAsset49 = new BaseStatAsset();
    pAsset49.id = "mass_2";
    this.add(pAsset49);
    BaseStatAsset pAsset50 = new BaseStatAsset();
    pAsset50.id = "multiplier_mass";
    pAsset50.show_as_percents = true;
    pAsset50.multiplier = true;
    pAsset50.main_stat_to_multiply = "mass_2";
    pAsset50.hidden = true;
    this.add(pAsset50);
    BaseStatAsset pAsset51 = new BaseStatAsset();
    pAsset51.id = "limit_population";
    this.add(pAsset51);
    BaseStatAsset pAsset52 = new BaseStatAsset();
    pAsset52.id = "multiplier_health";
    pAsset52.show_as_percents = true;
    pAsset52.multiplier = true;
    pAsset52.main_stat_to_multiply = "health";
    pAsset52.tooltip_multiply_for_visual_number = 100f;
    pAsset52.translation_key = "health";
    this.add(pAsset52);
    BaseStatAsset pAsset53 = new BaseStatAsset();
    pAsset53.id = "multiplier_lifespan";
    pAsset53.show_as_percents = true;
    pAsset53.multiplier = true;
    pAsset53.main_stat_to_multiply = "lifespan";
    pAsset53.tooltip_multiply_for_visual_number = 100f;
    pAsset53.translation_key = "lifespan";
    this.add(pAsset53);
    BaseStatAsset pAsset54 = new BaseStatAsset();
    pAsset54.id = "multiplier_stamina";
    pAsset54.show_as_percents = true;
    pAsset54.multiplier = true;
    pAsset54.main_stat_to_multiply = "stamina";
    pAsset54.tooltip_multiply_for_visual_number = 100f;
    pAsset54.translation_key = "stamina";
    this.add(pAsset54);
    BaseStatAsset pAsset55 = new BaseStatAsset();
    pAsset55.id = "multiplier_mana";
    pAsset55.show_as_percents = true;
    pAsset55.multiplier = true;
    pAsset55.main_stat_to_multiply = "mana";
    pAsset55.tooltip_multiply_for_visual_number = 100f;
    pAsset55.translation_key = "mana";
    this.add(pAsset55);
    BaseStatAsset pAsset56 = new BaseStatAsset();
    pAsset56.id = "multiplier_damage";
    pAsset56.show_as_percents = true;
    pAsset56.multiplier = true;
    pAsset56.main_stat_to_multiply = "damage";
    pAsset56.tooltip_multiply_for_visual_number = 100f;
    pAsset56.translation_key = "damage";
    this.add(pAsset56);
    BaseStatAsset pAsset57 = new BaseStatAsset();
    pAsset57.id = "multiplier_crit";
    pAsset57.show_as_percents = true;
    pAsset57.multiplier = true;
    pAsset57.main_stat_to_multiply = "critical_chance";
    pAsset57.tooltip_multiply_for_visual_number = 100f;
    pAsset57.translation_key = "critical_chance_multiplier";
    this.add(pAsset57);
    BaseStatAsset pAsset58 = new BaseStatAsset();
    pAsset58.id = "multiplier_diplomacy";
    pAsset58.show_as_percents = true;
    pAsset58.multiplier = true;
    pAsset58.main_stat_to_multiply = "diplomacy";
    pAsset58.tooltip_multiply_for_visual_number = 100f;
    pAsset58.translation_key = "diplomacy";
    pAsset58.used_only_for_civs = true;
    this.add(pAsset58);
    BaseStatAsset pAsset59 = new BaseStatAsset();
    pAsset59.id = "multiplier_speed";
    pAsset59.show_as_percents = true;
    pAsset59.multiplier = true;
    pAsset59.main_stat_to_multiply = "speed";
    pAsset59.tooltip_multiply_for_visual_number = 100f;
    pAsset59.translation_key = "speed";
    this.add(pAsset59);
    BaseStatAsset pAsset60 = new BaseStatAsset();
    pAsset60.id = "multiplier_attack_speed";
    pAsset60.show_as_percents = true;
    pAsset60.multiplier = true;
    pAsset60.main_stat_to_multiply = "attack_speed";
    pAsset60.tooltip_multiply_for_visual_number = 100f;
    pAsset60.translation_key = "attack_speed";
    this.add(pAsset60);
    BaseStatAsset pAsset61 = new BaseStatAsset();
    pAsset61.id = "scale";
    pAsset61.show_as_percents = true;
    pAsset61.tooltip_multiply_for_visual_number = 1000f;
    pAsset61.translation_key = "size";
    this.add(pAsset61);
    BaseStatAsset pAsset62 = new BaseStatAsset();
    pAsset62.id = "multiplier_supply_timer";
    pAsset62.hidden = true;
    pAsset62.used_only_for_civs = true;
    this.add(pAsset62);
    BaseStatAsset pAsset63 = new BaseStatAsset();
    pAsset63.id = "limit_clan_members";
    pAsset63.used_only_for_civs = true;
    this.add(pAsset63);
    BaseStatAsset pAsset64 = new BaseStatAsset();
    pAsset64.id = "status_chance";
    this.add(pAsset64);
    BaseStatAsset pAsset65 = new BaseStatAsset();
    pAsset65.id = "damage_range";
    pAsset65.hidden = true;
    pAsset65.normalize = true;
    pAsset65.normalize_min = 0.1f;
    this.add(pAsset65);
  }

  public override void editorDiagnosticLocales()
  {
    foreach (BaseStatAsset pAsset in this.list)
    {
      if (!pAsset.hidden)
        this.checkLocale((Asset) pAsset, pAsset.getLocaleID());
    }
    base.editorDiagnosticLocales();
  }
}
