// Decompiled with JetBrains decompiler
// Type: BiomeLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

using System.Collections.Generic;

#nullable disable
public class BiomeLibrary : AssetLibrary<BiomeAsset>
{
  public static List<BiomeAsset> pool_biomes = new List<BiomeAsset>();

  public override void init()
  {
    base.init();
    this.addNormalBiomes();
    this.addCreepBiomes();
    this.addSpecialBiomes();
  }

  public void addNormalBiomes()
  {
    BiomeAsset pAsset1 = new BiomeAsset();
    pAsset1.id = "biome_grass";
    pAsset1.tile_low = "grass_low";
    pAsset1.tile_high = "grass_high";
    pAsset1.localized_key = "Grass";
    pAsset1.grow_strength = 5;
    pAsset1.spread_biome = true;
    pAsset1.spread_by_drops_water = true;
    pAsset1.generator_pot_amount = 8;
    pAsset1.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset1.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset1.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset1.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset1.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("graminae", "viridis", "pratensis");
    this.add(pAsset1);
    this.t.addSubspeciesTrait("fast_builders");
    this.t.addCultureTrait("pep_talks");
    this.t.addCultureTrait("youth_reverence");
    this.t.addCultureTrait("gossip_lovers");
    this.t.addLanguageTrait("strict_spelling");
    this.t.addUnit("wolf");
    this.t.addUnit("fox", 2);
    this.t.addUnit("raccoon");
    this.t.addUnit("sheep", 3);
    this.t.addUnit("chicken", 3);
    this.t.addUnit("rabbit", 3);
    this.t.addUnit("fly", 4);
    this.t.addUnit("beetle", 4);
    this.t.addUnit("grasshopper", 4);
    this.t.addSapientUnit("human");
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("orc");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("civ_wolf");
    this.t.addSapientUnit("civ_fox");
    this.t.addSapientUnit("bandit");
    this.t.addSapientUnit("civ_sheep");
    this.t.addSapientUnit("civ_chicken");
    this.t.addSapientUnit("civ_rabbit");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("tree_green_1");
    this.t.addTree("tree_green_2");
    this.t.addTree("tree_green_3");
    this.t.addPlant("mushroom_red", 2);
    this.t.addPlant("mushroom_green", 2);
    this.t.addPlant("mushroom_teal", 2);
    this.t.addPlant("mushroom_white", 2);
    this.t.addPlant("mushroom_yellow", 2);
    this.t.addPlant("green_herb", 4);
    this.t.addPlant("flower", 4);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset2 = new BiomeAsset();
    pAsset2.id = "biome_savanna";
    pAsset2.tile_low = "savanna_low";
    pAsset2.tile_high = "savanna_high";
    pAsset2.localized_key = "Savanna";
    pAsset2.spread_biome = true;
    pAsset2.spread_by_drops_water = true;
    pAsset2.generator_pot_amount = 5;
    pAsset2.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset2.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset2.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset2.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset2.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("savannae", "aridus", "praeruptus");
    this.add(pAsset2);
    this.t.addActorTrait("fast");
    this.t.addCultureTrait("sword_lovers");
    this.t.addLanguageTrait("elegant_words");
    this.t.addUnit("rhino");
    this.t.addUnit("hyena");
    this.t.addUnit("buffalo");
    this.t.addUnit("cat", 3);
    this.t.addUnit("armadillo");
    this.t.addUnit("ostrich", 2);
    this.t.addUnit("fly", 4);
    this.t.addUnit("beetle", 4);
    this.t.addSapientUnit("human");
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("orc");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("civ_cat");
    this.t.addSapientUnit("civ_rhino");
    this.t.addSapientUnit("civ_hyena");
    this.t.addSapientUnit("civ_buffalo");
    this.t.addSapientUnit("civ_armadillo");
    this.t.addMineral("mineral_stone", 5);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("savanna_tree_1", 5);
    this.t.addTree("savanna_tree_2", 5);
    this.t.addTree("savanna_tree_big_1");
    this.t.addTree("savanna_tree_big_2");
    this.t.addPlant("savanna_plant");
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset3 = new BiomeAsset();
    pAsset3.id = "biome_jungle";
    pAsset3.tile_low = "jungle_low";
    pAsset3.tile_high = "jungle_high";
    pAsset3.localized_key = "Jungle";
    pAsset3.spread_biome = true;
    pAsset3.spread_by_drops_water = true;
    pAsset3.generator_pot_amount = 6;
    pAsset3.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset3.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset3.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset3.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset3.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("junglis", "viriditas", "tropicus");
    this.add(pAsset3);
    this.t.addActorTrait("tiny");
    this.t.addActorTrait("poison_immune");
    this.t.addCultureTrait("spear_lovers");
    this.t.addCultureTrait("city_layout_raindrops");
    this.t.addLanguageTrait("beautiful_calligraphy");
    this.t.addUnit("snake");
    this.t.addUnit("cat", 2);
    this.t.addUnit("monkey");
    this.t.addUnit("frog", 3);
    this.t.addUnit("scorpion");
    this.t.addSapientUnit("human");
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("orc");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("civ_snake");
    this.t.addSapientUnit("civ_cat");
    this.t.addSapientUnit("civ_monkey");
    this.t.addSapientUnit("civ_frog");
    this.t.addSapientUnit("civ_scorpion");
    this.t.addMineral("mineral_silver", 5);
    this.t.addMineral("mineral_metals");
    this.t.addMineral("mineral_gems");
    this.t.addTree("jungle_tree");
    this.t.addPlant("jungle_plant");
    this.t.addPlant("jungle_flower");
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset4 = new BiomeAsset();
    pAsset4.id = "biome_desert";
    pAsset4.tile_low = "desert_low";
    pAsset4.tile_high = "desert_high";
    pAsset4.localized_key = "Desert";
    pAsset4.spread_biome = true;
    pAsset4.spread_by_drops_water = true;
    pAsset4.generator_pot_amount = 4;
    pAsset4.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset4.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset4.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset4.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset4.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("solantheria", "ergensis", "deserticus");
    this.add(pAsset4);
    this.t.addActorTrait("eagle_eyed");
    this.t.addClanTrait("silver_tongues");
    this.t.addCultureTrait("solitude_seekers");
    this.t.addCultureTrait("gossip_lovers");
    this.t.addLanguageTrait("stylish_writing");
    this.t.addSubspeciesTraitAlways("adaptation_desert");
    this.t.addUnit("cat");
    this.t.addUnit("snake");
    this.t.addSapientUnit("human");
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("orc");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("civ_cat");
    this.t.addSapientUnit("civ_snake");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_gems");
    this.t.addMineral("mineral_silver");
    this.t.addTree("desert_tree");
    this.t.addPlant("desert_plant");
    this.t.addUnit("scorpion");
    BiomeAsset pAsset5 = new BiomeAsset();
    pAsset5.id = "biome_lemon";
    pAsset5.tile_low = "lemon_low";
    pAsset5.tile_high = "lemon_high";
    pAsset5.localized_key = "Lemon";
    pAsset5.spread_biome = true;
    pAsset5.spread_by_drops_water = true;
    pAsset5.generator_pot_amount = 3;
    pAsset5.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset5.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset5.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset5.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset5.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("aurantium", "acidus", "limonum");
    this.add(pAsset5);
    this.t.addActorTrait("genius");
    this.t.addCultureTrait("fast_learners");
    this.t.addLanguageTrait("melodic");
    this.t.addLanguageTrait("elegant_words");
    this.t.addUnit("lemon_snail");
    this.t.addSapientUnit("civ_lemon_man");
    this.t.addMineral("mineral_stone", 5);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("lemon_tree");
    this.t.addPlant("mushroom_red");
    this.t.addPlant("mushroom_green");
    this.t.addPlant("mushroom_teal");
    this.t.addPlant("mushroom_white");
    this.t.addPlant("mushroom_yellow");
    this.t.addPlant("green_herb", 5);
    this.t.addPlant("flower", 5);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset6 = new BiomeAsset();
    pAsset6.id = "biome_permafrost";
    pAsset6.tile_low = "permafrost_low";
    pAsset6.tile_high = "permafrost_high";
    pAsset6.localized_key = "Permafrost";
    pAsset6.cold_biome = true;
    pAsset6.spread_biome = true;
    pAsset6.generator_pot_amount = 3;
    pAsset6.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset6.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset6.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset6.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset6.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("albus", "sibericus", "frostis");
    this.add(pAsset6);
    this.t.addActorTrait("freeze_proof");
    this.t.addSubspeciesTrait("cold_resistance");
    this.t.addSubspeciesTraitAlways("adaptation_permafrost");
    this.t.addCultureTrait("attentive_readers");
    this.t.addCultureTrait("ancestors_knowledge");
    this.t.addUnit("penguin", 4);
    this.t.addUnit("bear");
    this.t.addUnit("wolf", 2);
    this.t.addUnit("snowman");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addSapientUnit("human");
    this.t.addSapientUnit("cold_one");
    this.t.addSapientUnit("civ_penguin");
    this.t.addSapientUnit("civ_bear");
    this.t.addSapientUnit("civ_wolf");
    this.t.addSapientUnit("snowman");
    this.t.addTree("pine_tree");
    this.t.addPlant("snow_plant");
    BiomeAsset pAsset7 = new BiomeAsset();
    pAsset7.id = "biome_swamp";
    pAsset7.tile_low = "swamp_low";
    pAsset7.tile_high = "swamp_high";
    pAsset7.localized_key = "Swamp";
    pAsset7.spread_biome = true;
    pAsset7.spread_by_drops_water = true;
    pAsset7.generator_pot_amount = 3;
    pAsset7.generator_max_size = 300;
    pAsset7.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset7.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset7.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset7.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset7.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("paludis", "limosa", "paluster");
    this.add(pAsset7);
    this.t.addActorTrait("regeneration");
    this.t.addCultureTrait("bow_lovers");
    this.t.addLanguageTrait("scribble");
    this.t.addSubspeciesTraitAlways("adaptation_swamp");
    this.t.addSubspeciesTraitEvolution("mutation_skin_tentacle_horror");
    this.t.addUnit("crocodile");
    this.t.addUnit("snake", 4);
    this.t.addUnit("frog", 6);
    this.t.addUnit("fly", 5);
    this.t.addUnit("turtle", 3);
    this.t.addUnit("capybara");
    this.t.addSapientUnit("orc");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("bandit");
    this.t.addSapientUnit("civ_crocodile");
    this.t.addSapientUnit("civ_snake");
    this.t.addSapientUnit("civ_frog");
    this.t.addSapientUnit("civ_capybara");
    this.t.addSapientUnit("civ_piranha");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("swamp_tree");
    this.t.addPlant("swamp_plant");
    this.t.addPlant("swamp_plant_big");
    BiomeAsset pAsset8 = new BiomeAsset();
    pAsset8.id = "biome_crystal";
    pAsset8.tile_low = "crystal_low";
    pAsset8.tile_high = "crystal_high";
    pAsset8.localized_key = "Crystal";
    pAsset8.loot_generation = 2;
    pAsset8.spread_biome = true;
    pAsset8.generator_pot_amount = 2;
    pAsset8.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset8.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset8.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset8.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset8.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("crystallus", "lucidus", "prismatus");
    this.add(pAsset8);
    this.t.addActorTrait("strong");
    this.t.addSubspeciesTrait("bioproduct_gems");
    this.t.addCultureTrait("tiny_legends");
    this.t.addCultureTrait("armorsmith_mastery");
    this.t.addCultureTrait("weaponsmith_mastery");
    this.t.addLanguageTrait("powerful_words");
    this.t.addUnit("crystal_sword", 2);
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("civ_crystal_golem");
    this.t.addTree("crystal_tree");
    this.t.addPlant("crystal_plant");
    BiomeAsset pAsset9 = new BiomeAsset();
    pAsset9.id = "biome_enchanted";
    pAsset9.tile_low = "enchanted_low";
    pAsset9.tile_high = "enchanted_high";
    pAsset9.localized_key = "Enchanted";
    pAsset9.spread_biome = true;
    pAsset9.spread_by_drops_blessing = true;
    pAsset9.loot_generation = 1;
    pAsset9.generator_pot_amount = 3;
    pAsset9.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset9.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset9.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset9.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset9.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("incantatum", "enchanta", "herbaeonis");
    this.add(pAsset9);
    this.t.addActorTrait("attractive");
    this.t.addSubspeciesTrait("gaia_roots");
    this.t.addSubspeciesTraitEvolution("mutation_skin_energy");
    this.t.addCultureTrait("training_potential");
    this.t.addCultureTrait("diplomatic_ascension");
    this.t.addCultureTrait("legacy_keepers");
    this.t.addLanguageTrait("ancient_runes");
    this.t.addLanguageTrait("enlightening_script");
    this.t.addUnit("butterfly", 5);
    this.t.addUnit("fairy");
    this.t.addSapientUnit("elf");
    this.t.addSapientUnit("white_mage");
    this.t.addSapientUnit("fairy");
    this.t.addMineral("mineral_silver", 5);
    this.t.addMineral("mineral_metals", 2);
    this.t.addMineral("mineral_gems");
    this.t.addTree("enchanted_tree");
    this.t.addPlant("flower", 5);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset10 = new BiomeAsset();
    pAsset10.id = "biome_corrupted";
    pAsset10.tile_low = "corrupted_low";
    pAsset10.tile_high = "corrupted_high";
    pAsset10.localized_key = "Corrupted";
    pAsset10.loot_generation = -1;
    pAsset10.dark_biome = true;
    pAsset10.spread_biome = true;
    pAsset10.spread_by_drops_curse = true;
    pAsset10.generator_pot_amount = 1;
    pAsset10.generator_max_size = 20;
    pAsset10.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset10.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset10.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset10.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset10.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("corruptus", "morbida", "tenebris");
    this.add(pAsset10);
    this.t.addActorTrait("weak");
    this.t.addSubspeciesTrait("death_grow_mythril");
    this.t.addSubspeciesTraitAlways("adaptation_corruption");
    this.t.addCultureTrait("happiness_from_war");
    this.t.addCultureTrait("xenophobic");
    this.t.addCultureTrait("ethnocentric_guard");
    this.t.addLanguageTrait("cursed_font");
    this.t.addReligionTrait("rite_of_restless_dead");
    this.t.addReligionTrait("cast_curse");
    this.t.addReligionTrait("spawn_skeleton");
    this.t.addUnit("jumpy_skull");
    this.t.addSapientUnit("necromancer");
    this.t.addSapientUnit("jumpy_skull");
    this.t.addSapientUnit("plague_doctor");
    this.t.addMineral("mineral_bones", 7);
    this.t.addTree("corrupted_tree");
    this.t.addTree("corrupted_tree_big");
    this.t.addPlant("corrupted_plant");
    BiomeAsset pAsset11 = new BiomeAsset();
    pAsset11.id = "biome_infernal";
    pAsset11.tile_low = "infernal_low";
    pAsset11.tile_high = "infernal_high";
    pAsset11.localized_key = "Infernal";
    pAsset11.spread_biome = true;
    pAsset11.spread_by_drops_fire = true;
    pAsset11.spread_ignore_burned_stages = true;
    pAsset11.generator_pot_amount = 1;
    pAsset11.generator_max_size = 20;
    pAsset11.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset11.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset11.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset11.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset11.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("ignifer", "brasarius", "ardorus");
    this.add(pAsset11);
    this.t.addActorTrait("fire_blood");
    this.t.addActorTrait("fire_proof");
    this.t.addSubspeciesTrait("heat_resistance");
    this.t.addSubspeciesTrait("hydrophobia");
    this.t.addSubspeciesTraitAlways("adaptation_infernal");
    this.t.addCultureTrait("happiness_from_war");
    this.t.addCultureTrait("xenophobic");
    this.t.addClanTrait("cursed_blood");
    this.t.addLanguageTrait("raging_paragraphs");
    this.t.addReligionTrait("rite_of_the_abyss");
    this.t.addUnit("fire_skull");
    this.t.addSapientUnit("evil_mage");
    this.t.addSapientUnit("demon");
    this.t.addSapientUnit("fire_skull");
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_adamantine", 3);
    this.t.addTree("infernal_tree");
    this.t.addTree("infernal_tree_big");
    this.t.addTree("infernal_tree_small");
    this.t.addPlant("flame_flower");
    BiomeAsset pAsset12 = new BiomeAsset();
    pAsset12.id = "biome_candy";
    pAsset12.tile_low = "candy_low";
    pAsset12.tile_high = "candy_high";
    pAsset12.localized_key = "Candy";
    pAsset12.spread_biome = true;
    pAsset12.spread_by_drops_water = true;
    pAsset12.generator_pot_amount = 1;
    pAsset12.generator_max_size = 30;
    pAsset12.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset12.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset12.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset12.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset12.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("dulcis", "glucosus", "crispus");
    this.add(pAsset12);
    this.t.addActorTrait("fat");
    this.t.addActorTrait("gluttonous");
    this.t.addSubspeciesTrait("annoying_fireworks");
    this.t.addSubspeciesTrait("super_positivity");
    this.t.addCultureTrait("tiny_legends");
    this.t.addLanguageTrait("foolish_glyphs");
    this.t.addUnit("smore");
    this.t.addSapientUnit("civ_candy_man");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("candy_tree");
    this.t.addPlant("candy_plant");
    BiomeAsset pAsset13 = new BiomeAsset();
    pAsset13.id = "biome_mushroom";
    pAsset13.tile_low = "mushroom_low";
    pAsset13.tile_high = "mushroom_high";
    pAsset13.localized_key = "Mushroom";
    pAsset13.spread_biome = true;
    pAsset13.spread_by_drops_water = true;
    pAsset13.spread_by_drops_powerup = true;
    pAsset13.generator_pot_amount = 1;
    pAsset13.generator_max_size = 300;
    pAsset13.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset13.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset13.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset13.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset13.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("sporae", "mycota", "mycetis");
    this.add(pAsset13);
    this.t.addActorTrait("regeneration");
    this.t.addSubspeciesTrait("bioproduct_mushrooms");
    this.t.addSubspeciesTrait("super_positivity");
    this.t.addCultureTrait("animal_whisperers");
    this.t.addCultureTrait("pep_talks");
    this.t.addLanguageTrait("powerful_words");
    this.t.addUnit("frog", 3);
    this.t.addUnit("sheep");
    this.t.addSapientUnit("civ_sheep");
    this.t.addSapientUnit("civ_frog");
    this.t.addMineral("mineral_silver", 3);
    this.t.addMineral("mineral_stone", 5);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_gems");
    this.t.addTree("mushroom_tree");
    this.t.addPlant("flower", 2);
    this.t.addPlant("mushroom_red", 2);
    this.t.addPlant("mushroom_green", 2);
    this.t.addPlant("mushroom_teal", 2);
    this.t.addPlant("mushroom_white", 2);
    this.t.addPlant("mushroom_yellow", 2);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset14 = new BiomeAsset();
    pAsset14.id = "biome_wasteland";
    pAsset14.tile_low = "wasteland_low";
    pAsset14.tile_high = "wasteland_high";
    pAsset14.localized_key = "Wasteland";
    pAsset14.loot_generation = -2;
    pAsset14.dark_biome = true;
    pAsset14.spread_biome = true;
    pAsset14.spread_by_drops_acid = true;
    pAsset14.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset14.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset14.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset14.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset14.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("toxicus", "wastus");
    this.add(pAsset14);
    this.t.addActorTrait("ugly");
    this.t.addSubspeciesTrait("bad_genes");
    this.t.addSubspeciesTrait("bioluminescence");
    this.t.addSubspeciesTraitAlways("adaptation_wasteland");
    this.t.addSubspeciesTraitEvolution("mutation_skin_abomination");
    this.t.addCultureTrait("xenophobic");
    this.t.addCultureTrait("solitude_seekers");
    this.t.addCultureTrait("legacy_keepers");
    this.t.addLanguageTrait("foolish_glyphs");
    this.t.addUnit("rat", 4);
    this.t.addUnit("acid_blob");
    this.t.addSapientUnit("civ_acid_gentleman");
    this.t.addSapientUnit("civ_rat");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("wasteland_tree");
    this.t.addPlant("wasteland_flower");
    BiomeAsset pAsset15 = new BiomeAsset();
    pAsset15.id = "biome_birch";
    pAsset15.tile_low = "birch_low";
    pAsset15.tile_high = "birch_high";
    pAsset15.localized_key = "Birch";
    pAsset15.grow_strength = 5;
    pAsset15.spread_biome = true;
    pAsset15.spread_by_drops_water = true;
    pAsset15.generator_pot_amount = 4;
    pAsset15.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset15.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset15.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset15.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset15.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("silvanus", "virentis", "sylvestris");
    this.add(pAsset15);
    this.t.addSubspeciesTrait("enhanced_strength");
    this.t.addCultureTrait("axe_lovers");
    this.t.addCultureTrait("diplomatic_ascension");
    this.t.addUnit("wolf");
    this.t.addUnit("sheep");
    this.t.addUnit("rabbit");
    this.t.addUnit("fox");
    this.t.addSapientUnit("civ_wolf");
    this.t.addSapientUnit("civ_sheep");
    this.t.addSapientUnit("civ_rabbit");
    this.t.addSapientUnit("civ_fox");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("birch_tree");
    this.t.addPlant("birch_plant");
    this.t.addPlant("mushroom_red");
    this.t.addPlant("mushroom_green");
    this.t.addPlant("mushroom_teal");
    this.t.addPlant("mushroom_white");
    this.t.addPlant("mushroom_yellow");
    this.t.addPlant("green_herb", 4);
    this.t.addPlant("flower", 4);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset16 = new BiomeAsset();
    pAsset16.id = "biome_maple";
    pAsset16.tile_low = "maple_low";
    pAsset16.tile_high = "maple_high";
    pAsset16.localized_key = "Maple";
    pAsset16.grow_strength = 5;
    pAsset16.spread_biome = true;
    pAsset16.spread_by_drops_water = true;
    pAsset16.generator_pot_amount = 5;
    pAsset16.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset16.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset16.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset16.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset16.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("mapleleafus", "canadus", "malifolia");
    this.add(pAsset16);
    this.t.addSubspeciesTrait("death_grow_tree");
    this.t.addCultureTrait("xenophiles");
    this.t.addLanguageTrait("nicely_structured_grammar");
    this.t.addLanguageTrait("melodic");
    this.t.addUnit("wolf");
    this.t.addUnit("dog");
    this.t.addSapientUnit("civ_wolf");
    this.t.addSapientUnit("civ_dog");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("maple_tree");
    this.t.addPlant("maple_plant");
    this.t.addPlant("mushroom_red");
    this.t.addPlant("mushroom_green");
    this.t.addPlant("mushroom_teal");
    this.t.addPlant("mushroom_white");
    this.t.addPlant("mushroom_yellow");
    this.t.addPlant("green_herb", 4);
    this.t.addPlant("flower", 4);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset17 = new BiomeAsset();
    pAsset17.id = "biome_rocklands";
    pAsset17.tile_low = "rocklands_low";
    pAsset17.tile_high = "rocklands_high";
    pAsset17.localized_key = "Rocklands";
    pAsset17.grow_strength = 5;
    pAsset17.spread_biome = true;
    pAsset17.generator_pot_amount = 2;
    pAsset17.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset17.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset17.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset17.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset17.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("lithos", "petrae", "rupes");
    this.add(pAsset17);
    this.t.addActorTrait("giant");
    this.t.addSubspeciesTrait("bioproduct_stone");
    this.t.addSubspeciesTrait("parental_care");
    this.t.addSubspeciesTraitEvolution("mutation_skin_living_rock");
    this.t.addCultureTrait("statue_lovers");
    this.t.addCultureTrait("training_potential");
    this.t.addCultureTrait("city_layout_stone_garden");
    this.t.addClanTrait("blood_of_giants");
    this.t.addLanguageTrait("powerful_words");
    this.t.addUnit("goat");
    this.t.addUnit("alpaca");
    this.t.addUnit("armadillo");
    this.t.addSapientUnit("dwarf");
    this.t.addSapientUnit("civ_goat");
    this.t.addSapientUnit("civ_alpaca");
    this.t.addSapientUnit("civ_armadillo");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_gems");
    this.t.addTree("rocklands_tree");
    this.t.addPlant("rocklands_plant");
    BiomeAsset pAsset18 = new BiomeAsset();
    pAsset18.id = "biome_garlic";
    pAsset18.tile_low = "garlic_low";
    pAsset18.tile_high = "garlic_high";
    pAsset18.localized_key = "Garlic";
    pAsset18.grow_strength = 5;
    pAsset18.spread_biome = true;
    pAsset18.spread_by_drops_water = true;
    pAsset18.generator_pot_amount = 2;
    pAsset18.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset18.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset18.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset18.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset18.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("aromatica", "vampiris", "odoratus");
    this.add(pAsset18);
    this.t.addActorTrait("immune");
    this.t.addSubspeciesTrait("accelerated_healing");
    this.t.addCultureTrait("attentive_readers");
    this.t.addClanTrait("masters_of_propaganda");
    this.t.addLanguageTrait("enlightening_script");
    this.t.addUnit("garl");
    this.t.addSapientUnit("civ_garlic_man");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("garlic_tree");
    this.t.addPlant("garlic_plant");
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset19 = new BiomeAsset();
    pAsset19.id = "biome_flower";
    pAsset19.tile_low = "flower_low";
    pAsset19.tile_high = "flower_high";
    pAsset19.localized_key = "Flower";
    pAsset19.grow_strength = 5;
    pAsset19.spread_biome = true;
    pAsset19.spread_by_drops_water = true;
    pAsset19.generator_pot_amount = 3;
    pAsset19.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset19.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset19.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset19.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset19.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("botanicus", "petala", "fragrans");
    this.add(pAsset19);
    this.t.addActorTrait("attractive");
    this.t.addSubspeciesTrait("death_grow_plant");
    this.t.addCultureTrait("matriarchy");
    this.t.addCultureTrait("gossip_lovers");
    this.t.addLanguageTrait("elegant_words");
    this.t.addUnit("flower_bud");
    this.t.addUnit("butterfly");
    this.t.addUnit("beetle");
    this.t.addUnit("bee");
    this.t.addUnit("grasshopper");
    this.t.addUnit("fly");
    this.t.addSapientUnit("civ_liliar");
    this.t.addSapientUnit("druid");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addTree("flower_tree_1");
    this.t.addTree("flower_tree_2");
    this.t.addTree("flower_tree_3");
    this.t.addPlant("flower_plant", 3);
    this.t.addPlant("mushroom_red");
    this.t.addPlant("mushroom_green");
    this.t.addPlant("mushroom_teal");
    this.t.addPlant("mushroom_white");
    this.t.addPlant("mushroom_yellow");
    this.t.addPlant("green_herb", 5);
    this.t.addPlant("flower", 20);
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset20 = new BiomeAsset();
    pAsset20.id = "biome_celestial";
    pAsset20.tile_low = "celestial_low";
    pAsset20.tile_high = "celestial_high";
    pAsset20.localized_key = "Celestial";
    pAsset20.grow_strength = 5;
    pAsset20.spread_biome = true;
    pAsset20.generator_pot_amount = 1;
    pAsset20.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset20.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset20.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset20.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset20.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("caelestis", "stellaris", "fragrans");
    this.add(pAsset20);
    this.t.addActorTrait("giant");
    this.t.addActorTrait("genius");
    this.t.addSubspeciesTrait("hyper_intelligence");
    this.t.addSubspeciesTraitEvolution("mutation_skin_light_orb");
    this.t.addClanTrait("gods_chosen");
    this.t.addCultureTrait("serenity_now");
    this.t.addCultureTrait("ancestors_knowledge");
    this.t.addLanguageTrait("font_of_gods");
    this.t.addLanguageTrait("magic_words");
    this.t.addReligionTrait("rite_of_falling_stars");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_mythril");
    this.t.addTree("celestial_tree", 10);
    this.t.addTree("celestial_tree_small");
    this.t.addUnit("unicorn");
    this.t.addSapientUnit("civ_unicorn");
    this.t.addPlant("celestial_plant");
    BiomeAsset pAsset21 = new BiomeAsset();
    pAsset21.id = "biome_clover";
    pAsset21.tile_low = "clover_low";
    pAsset21.tile_high = "clover_high";
    pAsset21.localized_key = "Clover";
    pAsset21.loot_generation = 3;
    pAsset21.grow_strength = 5;
    pAsset21.spread_biome = true;
    pAsset21.spread_by_drops_water = true;
    pAsset21.generator_pot_amount = 2;
    pAsset21.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset21.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset21.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset21.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset21.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("luckii", "trifolii", "prosperus");
    this.add(pAsset21);
    this.t.addActorTrait("lucky");
    this.t.addSubspeciesTrait("death_grow_plant");
    this.t.addCultureTrait("elder_reverence");
    this.t.addLanguageTrait("stylish_writing");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_gems");
    this.t.addUnit("rabbit");
    this.t.addUnit("cow");
    this.t.addUnit("butterfly", 5);
    this.t.addUnit("bee", 3);
    this.t.addUnit("fairy");
    this.t.addSapientUnit("civ_rabbit");
    this.t.addSapientUnit("civ_cow");
    this.t.addTree("clover_tree");
    this.t.addPlant("clover_plant");
    this.t.addBush("fruit_bush");
    BiomeAsset pAsset22 = new BiomeAsset();
    pAsset22.id = "biome_singularity";
    pAsset22.tile_low = "singularity_low";
    pAsset22.tile_high = "singularity_high";
    pAsset22.localized_key = "Singularity Swamp";
    pAsset22.loot_generation = 3;
    pAsset22.dark_biome = true;
    pAsset22.grow_strength = 5;
    pAsset22.spread_biome = true;
    pAsset22.spread_by_drops_coffee = true;
    pAsset22.generator_pot_amount = 0;
    pAsset22.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset22.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset22.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset22.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset22.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("singularis", "infinitus", "quantumus");
    this.add(pAsset22);
    this.t.addActorTrait("tiny");
    this.t.addActorTrait("long_liver");
    this.t.addSubspeciesTrait("big_stomach");
    this.t.addSubspeciesTraitEvolution("mutation_skin_void");
    this.t.addCultureTrait("ancestors_knowledge");
    this.t.addCultureTrait("gossip_lovers");
    this.t.addLanguageTrait("repeated_sentences");
    this.t.addReligionTrait("teleport");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addUnit("angle");
    this.t.addSapientUnit("angle");
    this.t.addTree("singularity_tree");
    this.t.addPlant("singularity_plant");
    BiomeAsset pAsset23 = new BiomeAsset();
    pAsset23.id = "biome_paradox";
    pAsset23.tile_low = "paradox_low";
    pAsset23.tile_high = "paradox_high";
    pAsset23.localized_key = "Paradox";
    pAsset23.grow_strength = 5;
    pAsset23.spread_biome = true;
    pAsset23.generator_pot_amount = 0;
    pAsset23.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset23.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomTrees);
    pAsset23.grow_type_selector_plants = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomPlants);
    pAsset23.grow_type_selector_bushes = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomBushes);
    pAsset23.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("temporis", "tempus", "chronos");
    this.add(pAsset23);
    this.t.addActorTrait("long_liver");
    this.t.addSubspeciesTrait("rapid_aging");
    this.t.addSubspeciesTrait("long_lifespan");
    this.t.addSubspeciesTraitEvolution("mutation_skin_fractal");
    this.t.addClanTrait("blood_of_eons");
    this.t.addCultureTrait("reading_lovers");
    this.t.addCultureTrait("youth_reverence");
    this.t.addCultureTrait("ancestors_knowledge");
    this.t.addCultureTrait("elder_reverence");
    this.t.addCultureTrait("expansionists");
    this.t.addLanguageTrait("eternal_text");
    this.t.addLanguageTrait("confusing_semantics");
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals", 3);
    this.t.addMineral("mineral_mythril");
    this.t.addTree("paradox_tree");
    this.t.addUnit("scorpion");
    this.t.addSapientUnit("alien");
    this.t.addSapientUnit("civ_scorpion");
    this.t.addPlant("paradox_plant");
  }

  private void addSpecialBiomes()
  {
    BiomeAsset pAsset1 = new BiomeAsset();
    pAsset1.id = "biome_sand";
    pAsset1.localized_key = "Sand";
    pAsset1.grow_type_selector_trees = new GrowTypeSelector(TileActionLibrary.getGrowTypeSand);
    pAsset1.grow_vegetation_auto = true;
    pAsset1.special_biome = true;
    pAsset1.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("granitius", "arenarius", "sabulum");
    this.add(pAsset1);
    this.t.addSubspeciesTrait("metamorphosis_crab");
    this.t.addUnit("crab");
    this.t.addSapientUnit("civ_crab");
    BiomeAsset pAsset2 = new BiomeAsset();
    pAsset2.id = "biome_hill";
    pAsset2.localized_key = "Hills";
    pAsset2.grow_type_selector_minerals = new GrowTypeSelector(TileActionLibrary.getGrowTypeRandomMineral);
    pAsset2.grow_vegetation_auto = true;
    pAsset2.special_biome = true;
    pAsset2.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("hillus", "stonus", "absolutus");
    this.add(pAsset2);
    this.t.addMineral("mineral_stone", 4);
    this.t.addMineral("mineral_metals");
  }

  private void addCreepBiomes()
  {
    BiomeAsset pAsset1 = new BiomeAsset();
    pAsset1.id = "biome_biomass";
    pAsset1.tile_low = "biomass_low";
    pAsset1.tile_high = "biomass_high";
    pAsset1.localized_key = "Biomass";
    pAsset1.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("organicus", "vivum");
    this.add(pAsset1);
    this.t.addSubspeciesTraitEvolution("mutation_skin_abomination");
    BiomeAsset pAsset2 = new BiomeAsset();
    pAsset2.id = "biome_cybertile";
    pAsset2.tile_low = "cybertile_low";
    pAsset2.tile_high = "cybertile_high";
    pAsset2.localized_key = "Cybercore";
    pAsset2.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("machinus", "cyberneticus", "technus");
    this.add(pAsset2);
    this.t.addSubspeciesTraitEvolution("mutation_skin_metalic_orb");
    BiomeAsset pAsset3 = new BiomeAsset();
    pAsset3.id = "biome_pumpkin";
    pAsset3.tile_low = "pumpkin_low";
    pAsset3.tile_high = "pumpkin_high";
    pAsset3.localized_key = "Super Pumpkin";
    pAsset3.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("maximus", "pepo", "cucurbitae");
    this.add(pAsset3);
    BiomeAsset pAsset4 = new BiomeAsset();
    pAsset4.id = "biome_tumor";
    pAsset4.tile_low = "tumor_low";
    pAsset4.tile_high = "tumor_high";
    pAsset4.localized_key = "Tumor";
    pAsset4.subspecies_name_suffix = AssetLibrary<BiomeAsset>.a<string>("neoplasmis", "cancrosus", "tumoralis");
    this.add(pAsset4);
    this.t.addSubspeciesTraitEvolution("mutation_skin_blood_vortex");
  }

  public override void linkAssets()
  {
    base.linkAssets();
    foreach (BiomeAsset pAsset in this.list)
      this.addBiomeToPool(pAsset);
  }

  private void addBiomeToPool(BiomeAsset pAsset)
  {
    for (int index = 0; index < pAsset.generator_pot_amount; ++index)
      BiomeLibrary.pool_biomes.Add(pAsset);
  }

  public override void editorDiagnosticLocales()
  {
    base.editorDiagnosticLocales();
    foreach (BiomeAsset pAsset in this.list)
    {
      this.checkLocale((Asset) pAsset, pAsset.getLocaleID());
      this.checkLocale((Asset) pAsset, pAsset.getDescriptionID());
    }
  }
}
