// Decompiled with JetBrains decompiler
// Type: HappinessLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

#nullable disable
public class HappinessLibrary : AssetLibrary<HappinessAsset>
{
  public override void init()
  {
    base.init();
    HappinessAsset pAsset1 = new HappinessAsset();
    pAsset1.id = "death_family_member";
    pAsset1.value = -20;
    pAsset1.pot_task_id = "crying";
    pAsset1.path_icon = "ui/Icons/iconDead";
    pAsset1.ignored_by_psychopaths = true;
    pAsset1.pot_amount = 5;
    this.add(pAsset1);
    HappinessAsset pAsset2 = new HappinessAsset();
    pAsset2.id = "death_lover";
    pAsset2.value = -50;
    pAsset2.pot_task_id = "crying";
    pAsset2.path_icon = "ui/Icons/iconCrying";
    pAsset2.ignored_by_psychopaths = true;
    pAsset2.pot_amount = 5;
    this.add(pAsset2);
    HappinessAsset pAsset3 = new HappinessAsset();
    pAsset3.id = "death_child";
    pAsset3.value = -60;
    pAsset3.pot_task_id = "crying";
    pAsset3.path_icon = "ui/Icons/iconCrying";
    pAsset3.ignored_by_psychopaths = true;
    pAsset3.pot_amount = 10;
    this.add(pAsset3);
    HappinessAsset pAsset4 = new HappinessAsset();
    pAsset4.id = "death_best_friend";
    pAsset4.value = -25;
    pAsset4.pot_task_id = "crying";
    pAsset4.path_icon = "ui/Icons/iconDead";
    pAsset4.ignored_by_psychopaths = true;
    pAsset4.pot_amount = 3;
    this.add(pAsset4);
    HappinessAsset pAsset5 = new HappinessAsset();
    pAsset5.id = "got_robbed";
    pAsset5.value = -20;
    pAsset5.pot_task_id = "swearing";
    pAsset5.path_icon = "ui/Icons/actor_traits/iconThief";
    pAsset5.pot_amount = 2;
    this.add(pAsset5);
    HappinessAsset pAsset6 = new HappinessAsset();
    pAsset6.id = "got_poked";
    pAsset6.value = -5;
    pAsset6.dialogs_amount = 10;
    pAsset6.path_icon = "ui/Icons/iconGodFinger";
    this.add(pAsset6);
    HappinessAsset pAsset7 = new HappinessAsset();
    pAsset7.id = "lost_fight";
    pAsset7.value = -20;
    pAsset7.pot_task_id = "swearing";
    pAsset7.path_icon = "ui/Icons/actor_traits/iconWeak";
    pAsset7.pot_amount = 2;
    this.add(pAsset7);
    HappinessAsset pAsset8 = new HappinessAsset();
    pAsset8.id = "got_caught";
    pAsset8.value = -20;
    pAsset8.pot_task_id = "crying";
    pAsset8.path_icon = "ui/Icons/iconSuspicious";
    pAsset8.ignored_by_psychopaths = true;
    pAsset8.pot_amount = 2;
    this.add(pAsset8);
    HappinessAsset pAsset9 = new HappinessAsset();
    pAsset9.id = "paid_tax";
    pAsset9.value = -5;
    pAsset9.pot_task_id = "swearing";
    pAsset9.path_icon = "ui/Icons/kingdom_traits/kingdom_trait_tax_rate_local_high";
    pAsset9.pot_amount = 1;
    this.add(pAsset9);
    HappinessAsset pAsset10 = new HappinessAsset();
    pAsset10.id = "just_ate";
    pAsset10.path_icon = "ui/Icons/iconHunger";
    pAsset10.value = 10;
    this.add(pAsset10);
    HappinessAsset pAsset11 = new HappinessAsset();
    pAsset11.id = "just_received_gift";
    pAsset11.path_icon = "ui/Icons/iconGift";
    pAsset11.ignored_by_psychopaths = true;
    pAsset11.value = 10;
    this.add(pAsset11);
    HappinessAsset pAsset12 = new HappinessAsset();
    pAsset12.id = "just_gave_gift";
    pAsset12.path_icon = "ui/Icons/iconGift";
    pAsset12.value = 20;
    this.add(pAsset12);
    HappinessAsset pAsset13 = new HappinessAsset();
    pAsset13.id = "just_pooped";
    pAsset13.path_icon = "ui/Icons/iconPoop";
    pAsset13.value = 5;
    this.add(pAsset13);
    HappinessAsset pAsset14 = new HappinessAsset();
    pAsset14.id = "just_slept";
    pAsset14.path_icon = "ui/Icons/iconSleep";
    pAsset14.value = 5;
    this.add(pAsset14);
    HappinessAsset pAsset15 = new HappinessAsset();
    pAsset15.id = "had_bad_dream";
    pAsset15.path_icon = "ui/Icons/iconDreamBad";
    pAsset15.value = -15;
    this.add(pAsset15);
    HappinessAsset pAsset16 = new HappinessAsset();
    pAsset16.id = "had_good_dream";
    pAsset16.path_icon = "ui/Icons/iconDreamGood";
    pAsset16.value = 15;
    this.add(pAsset16);
    HappinessAsset pAsset17 = new HappinessAsset();
    pAsset17.id = "had_nightmare";
    pAsset17.path_icon = "ui/Icons/iconDreamNightmare";
    pAsset17.value = -30;
    this.add(pAsset17);
    HappinessAsset pAsset18 = new HappinessAsset();
    pAsset18.id = "slept_outside";
    pAsset18.path_icon = "ui/Icons/iconSleep";
    pAsset18.value = -30;
    this.add(pAsset18);
    HappinessAsset pAsset19 = new HappinessAsset();
    pAsset19.id = "just_kissed";
    pAsset19.value = 10;
    pAsset19.pot_task_id = "singing";
    pAsset19.path_icon = "ui/Icons/iconLovers";
    pAsset19.ignored_by_psychopaths = true;
    pAsset19.pot_amount = 2;
    this.add(pAsset19);
    HappinessAsset pAsset20 = new HappinessAsset();
    pAsset20.id = "just_killed";
    pAsset20.path_icon = "ui/Icons/iconKills";
    pAsset20.value = 10;
    this.add(pAsset20);
    HappinessAsset pAsset21 = new HappinessAsset();
    pAsset21.id = "become_king";
    pAsset21.value = 50;
    pAsset21.pot_task_id = "happy_laughing";
    pAsset21.path_icon = "ui/Icons/iconKings";
    pAsset21.pot_amount = 2;
    this.add(pAsset21);
    HappinessAsset pAsset22 = new HappinessAsset();
    pAsset22.id = "become_leader";
    pAsset22.value = 40;
    pAsset22.pot_task_id = "happy_laughing";
    pAsset22.path_icon = "ui/Icons/iconLeaders";
    pAsset22.pot_amount = 2;
    this.add(pAsset22);
    HappinessAsset pAsset23 = new HappinessAsset();
    pAsset23.id = "just_won_war";
    pAsset23.path_icon = "ui/Icons/iconWar";
    pAsset23.value = 20;
    pAsset23.pot_task_id = "singing";
    pAsset23.pot_amount = 3;
    this.add(pAsset23);
    HappinessAsset pAsset24 = new HappinessAsset();
    pAsset24.id = "just_made_peace";
    pAsset24.path_icon = "ui/Icons/actor_traits/iconPeaceful";
    pAsset24.value = 5;
    this.add(pAsset24);
    HappinessAsset pAsset25 = new HappinessAsset();
    pAsset25.id = "just_lost_war";
    pAsset25.path_icon = "ui/Icons/iconDeadKingdom";
    pAsset25.value = -20;
    pAsset25.pot_task_id = "swearing";
    pAsset25.ignored_by_psychopaths = true;
    pAsset25.pot_amount = 2;
    this.add(pAsset25);
    HappinessAsset pAsset26 = new HappinessAsset();
    pAsset26.id = "was_conquered";
    pAsset26.path_icon = "ui/Icons/iconDeadKingdom";
    pAsset26.value = -20;
    pAsset26.pot_task_id = "crying";
    pAsset26.pot_amount = 2;
    this.add(pAsset26);
    HappinessAsset pAsset27 = new HappinessAsset();
    pAsset27.id = "kingdom_fell_apart";
    pAsset27.path_icon = "ui/Icons/iconDeadKingdom";
    pAsset27.value = -5;
    pAsset27.pot_task_id = "swearing";
    pAsset27.ignored_by_psychopaths = true;
    pAsset27.pot_amount = 2;
    this.add(pAsset27);
    HappinessAsset pAsset28 = new HappinessAsset();
    pAsset28.id = "just_started_war";
    pAsset28.path_icon = "ui/Icons/iconWar";
    pAsset28.value = 20;
    this.add(pAsset28);
    HappinessAsset pAsset29 = new HappinessAsset();
    pAsset29.id = "just_rebelled";
    pAsset29.value = 30;
    pAsset29.pot_task_id = "singing";
    pAsset29.path_icon = "ui/Icons/iconRebellion";
    pAsset29.pot_amount = 3;
    this.add(pAsset29);
    HappinessAsset pAsset30 = new HappinessAsset();
    pAsset30.id = "fallen_in_love";
    pAsset30.value = 40;
    pAsset30.pot_task_id = "singing";
    pAsset30.path_icon = "ui/Icons/iconLovers";
    pAsset30.ignored_by_psychopaths = true;
    pAsset30.pot_amount = 3;
    this.add(pAsset30);
    HappinessAsset pAsset31 = new HappinessAsset();
    pAsset31.id = "just_had_child";
    pAsset31.value = 30;
    pAsset31.pot_task_id = "singing";
    pAsset31.path_icon = "ui/Icons/iconChildren";
    pAsset31.ignored_by_psychopaths = true;
    pAsset31.pot_amount = 1;
    this.add(pAsset31);
    HappinessAsset pAsset32 = new HappinessAsset();
    pAsset32.id = "just_read_book";
    pAsset32.path_icon = "ui/Icons/iconBooks";
    pAsset32.value = 10;
    this.add(pAsset32);
    HappinessAsset pAsset33 = new HappinessAsset();
    pAsset33.id = "just_played";
    pAsset33.value = 15;
    pAsset33.pot_task_id = "happy_laughing";
    pAsset33.ignored_by_psychopaths = true;
    pAsset33.path_icon = "ui/Icons/iconPlayed";
    pAsset33.pot_amount = 3;
    this.add(pAsset33);
    HappinessAsset pAsset34 = new HappinessAsset();
    pAsset34.id = "just_talked";
    pAsset34.path_icon = "ui/Icons/iconRecoverySocial";
    pAsset34.value = 10;
    this.add(pAsset34);
    HappinessAsset pAsset35 = new HappinessAsset();
    pAsset35.id = "just_laughed";
    pAsset35.path_icon = "ui/Icons/iconLaughing";
    pAsset35.value = 5;
    this.add(pAsset35);
    HappinessAsset pAsset36 = new HappinessAsset();
    pAsset36.id = "just_sang";
    pAsset36.path_icon = "ui/Icons/iconSinging";
    pAsset36.value = 10;
    this.add(pAsset36);
    HappinessAsset pAsset37 = new HappinessAsset();
    pAsset37.id = "just_swore";
    pAsset37.path_icon = "ui/Icons/iconSwearing";
    pAsset37.value = 2;
    this.add(pAsset37);
    HappinessAsset pAsset38 = new HappinessAsset();
    pAsset38.id = "just_cried";
    pAsset38.path_icon = "ui/Icons/iconCrying";
    pAsset38.ignored_by_psychopaths = true;
    pAsset38.value = 5;
    this.add(pAsset38);
    HappinessAsset pAsset39 = new HappinessAsset();
    pAsset39.id = "just_talked_gossip";
    pAsset39.path_icon = "ui/Icons/iconRecoveryPlot";
    pAsset39.value = 14;
    this.add(pAsset39);
    HappinessAsset pAsset40 = new HappinessAsset();
    pAsset40.id = "just_surprised";
    pAsset40.value = -10;
    pAsset40.pot_task_id = "swearing";
    pAsset40.path_icon = "ui/Icons/iconSurprised";
    pAsset40.show_change_happiness_effect = false;
    pAsset40.pot_amount = 2;
    this.add(pAsset40);
    HappinessAsset pAsset41 = new HappinessAsset();
    pAsset41.id = "just_born";
    pAsset41.value = 50;
    pAsset41.pot_task_id = "singing";
    pAsset41.path_icon = "ui/Icons/iconAge";
    pAsset41.pot_amount = 1;
    pAsset41.dialogs_amount = 13;
    pAsset41.show_change_happiness_effect = false;
    this.add(pAsset41);
    HappinessAsset pAsset42 = new HappinessAsset();
    pAsset42.id = "just_magnetised";
    pAsset42.value = -10;
    pAsset42.pot_task_id = "swearing";
    pAsset42.path_icon = "ui/Icons/iconMagnetized";
    pAsset42.dialogs_amount = 13;
    pAsset42.show_change_happiness_effect = false;
    pAsset42.pot_amount = 3;
    this.add(pAsset42);
    HappinessAsset pAsset43 = new HappinessAsset();
    pAsset43.id = "just_forced_power";
    pAsset43.path_icon = "ui/Icons/iconForce";
    pAsset43.show_change_happiness_effect = false;
    pAsset43.value = -20;
    this.add(pAsset43);
    HappinessAsset pAsset44 = new HappinessAsset();
    pAsset44.id = "just_possessed";
    pAsset44.path_icon = "ui/Icons/iconPossessed";
    pAsset44.show_change_happiness_effect = false;
    pAsset44.value = -20;
    this.add(pAsset44);
    HappinessAsset pAsset45 = new HappinessAsset();
    pAsset45.id = "strange_urge";
    pAsset45.path_icon = "ui/Icons/iconStrangeUrge";
    pAsset45.show_change_happiness_effect = false;
    pAsset45.value = -5;
    this.add(pAsset45);
    HappinessAsset pAsset46 = new HappinessAsset();
    pAsset46.id = "just_had_tantrum";
    pAsset46.path_icon = "ui/Icons/iconTantrum";
    pAsset46.value = 25;
    this.add(pAsset46);
    HappinessAsset pAsset47 = new HappinessAsset();
    pAsset47.id = "just_felt_the_divine";
    pAsset47.path_icon = "ui/Icons/iconGodFinger";
    pAsset47.value = 40;
    this.add(pAsset47);
    HappinessAsset pAsset48 = new HappinessAsset();
    pAsset48.id = "just_enchanted";
    pAsset48.path_icon = "ui/Icons/iconEnchanted";
    pAsset48.value = 30;
    this.add(pAsset48);
    HappinessAsset pAsset49 = new HappinessAsset();
    pAsset49.id = "just_inspired";
    pAsset49.path_icon = "ui/Icons/iconInspired";
    pAsset49.value = 25;
    this.add(pAsset49);
    HappinessAsset pAsset50 = new HappinessAsset();
    pAsset50.id = "wrote_book";
    pAsset50.path_icon = "ui/Icons/iconBooksWritten";
    pAsset50.value = 20;
    this.add(pAsset50);
    HappinessAsset pAsset51 = new HappinessAsset();
    pAsset51.id = "just_became_adult";
    pAsset51.path_icon = "ui/Icons/iconAdults";
    pAsset51.value = 30;
    this.add(pAsset51);
    HappinessAsset pAsset52 = new HappinessAsset();
    pAsset52.id = "just_got_out_of_egg";
    pAsset52.path_icon = "ui/Icons/iconEgg";
    pAsset52.show_change_happiness_effect = false;
    pAsset52.value = 20;
    this.add(pAsset52);
    HappinessAsset pAsset53 = new HappinessAsset();
    pAsset53.id = "just_finished_plot";
    pAsset53.path_icon = "ui/Icons/iconPlotList";
    pAsset53.value = 25;
    this.add(pAsset53);
    HappinessAsset pAsset54 = new HappinessAsset();
    pAsset54.id = "just_found_house";
    pAsset54.path_icon = "ui/Icons/iconHoused";
    pAsset54.value = 35;
    this.add(pAsset54);
    HappinessAsset pAsset55 = new HappinessAsset();
    pAsset55.id = "just_lost_house";
    pAsset55.value = -30;
    pAsset55.pot_task_id = "start_tantrum";
    pAsset55.path_icon = "ui/Icons/iconHomeless";
    pAsset55.pot_amount = 1;
    this.add(pAsset55);
    HappinessAsset pAsset56 = new HappinessAsset();
    pAsset56.id = "just_made_friend";
    pAsset56.path_icon = "ui/Icons/iconFriendship";
    pAsset56.value = 40;
    this.add(pAsset56);
    HappinessAsset pAsset57 = new HappinessAsset();
    pAsset57.id = "just_injured";
    pAsset57.value = -20;
    pAsset57.pot_task_id = "swearing";
    pAsset57.path_icon = "ui/Icons/actor_traits/iconCrippled";
    pAsset57.pot_amount = 2;
    this.add(pAsset57);
    HappinessAsset pAsset58 = new HappinessAsset();
    pAsset58.id = "just_cursed";
    pAsset58.path_icon = "ui/Icons/iconCursed";
    pAsset58.value = -20;
    this.add(pAsset58);
    HappinessAsset pAsset59 = new HappinessAsset();
    pAsset59.id = "starving";
    pAsset59.path_icon = "ui/Icons/iconHungry";
    pAsset59.value = -40;
    this.add(pAsset59);
    HappinessAsset pAsset60 = new HappinessAsset();
    pAsset60.id = "conquered_city";
    pAsset60.path_icon = "ui/Icons/iconCitySelect";
    pAsset60.value = 30;
    this.add(pAsset60);
    HappinessAsset pAsset61 = new HappinessAsset();
    pAsset61.id = "destroyed_city";
    pAsset61.path_icon = "ui/Icons/iconRebellion";
    pAsset61.value = 35;
    this.add(pAsset61);
    HappinessAsset pAsset62 = new HappinessAsset();
    pAsset62.id = "lost_crown";
    pAsset62.value = -60;
    pAsset62.pot_task_id = "start_tantrum";
    pAsset62.path_icon = "ui/Icons/iconCrown";
    pAsset62.ignored_by_psychopaths = true;
    pAsset62.pot_amount = 4;
    this.add(pAsset62);
    HappinessAsset pAsset63 = new HappinessAsset();
    pAsset63.id = "razed_capital";
    pAsset63.value = -35;
    pAsset63.pot_task_id = "swearing";
    pAsset63.path_icon = "ui/Icons/iconRebellion";
    this.add(pAsset63);
    HappinessAsset pAsset64 = new HappinessAsset();
    pAsset64.id = "lost_capital";
    pAsset64.value = -30;
    pAsset64.pot_task_id = "swearing";
    pAsset64.path_icon = "ui/Icons/iconCrown";
    this.add(pAsset64);
    HappinessAsset pAsset65 = new HappinessAsset();
    pAsset65.id = "razed_city";
    pAsset65.value = -20;
    pAsset65.pot_task_id = "swearing";
    pAsset65.path_icon = "ui/Icons/iconRebellion";
    this.add(pAsset65);
    HappinessAsset pAsset66 = new HappinessAsset();
    pAsset66.id = "lost_city";
    pAsset66.value = -15;
    pAsset66.pot_task_id = "swearing";
    pAsset66.path_icon = "ui/Icons/iconCitySelect";
    this.add(pAsset66);
    HappinessAsset pAsset67 = new HappinessAsset();
    pAsset67.id = "become_alpha";
    pAsset67.path_icon = "ui/Icons/iconWolf";
    pAsset67.value = 20;
    this.add(pAsset67);
  }

  public override void post_init()
  {
    base.post_init();
    for (int index = 0; index < this.list.Count; ++index)
      this.list[index].index = index;
  }

  public override void editorDiagnosticLocales()
  {
    foreach (HappinessAsset pAsset in this.list)
    {
      this.checkLocale((Asset) pAsset, pAsset.getLocaleID());
      this.checkSpriteExists("path_icon", pAsset.path_icon, (Asset) pAsset);
      foreach (string localeId in pAsset.getLocaleIDs())
        this.checkLocale((Asset) pAsset, localeId);
    }
    base.editorDiagnosticLocales();
  }
}
