// Decompiled with JetBrains decompiler
// Type: HistoryDataLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

using UnityEngine;

#nullable disable
public class HistoryDataLibrary : AssetLibrary<HistoryDataAsset>
{
  public override void init()
  {
    base.init();
    this.addStats();
    this.addBiomes();
    this.addTiles();
  }

  public void addStats()
  {
    HistoryDataAsset pAsset1 = new HistoryDataAsset();
    pAsset1.id = "population";
    pAsset1.color_hex = "#6295B3";
    pAsset1.path_icon = "ui/Icons/iconPopulation";
    pAsset1.enabled_default = true;
    this.add(pAsset1);
    HistoryDataAsset pAsset2 = new HistoryDataAsset();
    pAsset2.id = "population_civ";
    pAsset2.statistics_asset = "world_statistics_population";
    pAsset2.color_hex = "#65A23F";
    pAsset2.path_icon = "ui/Icons/iconPopulationCiv";
    this.add(pAsset2);
    HistoryDataAsset pAsset3 = new HistoryDataAsset();
    pAsset3.id = "population_beasts";
    pAsset3.statistics_asset = "world_statistics_beasts";
    pAsset3.color_hex = "#664C28";
    pAsset3.path_icon = "ui/Icons/worldrules/icon_animalspawn";
    this.add(pAsset3);
    HistoryDataAsset pAsset4 = new HistoryDataAsset();
    pAsset4.id = "creatures_born";
    pAsset4.statistics_asset = "world_statistics_creatures_born";
    pAsset4.color_hex = "#DA3A57";
    pAsset4.path_icon = "ui/Icons/iconBirths";
    pAsset4.max = true;
    this.add(pAsset4);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset5 = new HistoryDataAsset();
    pAsset5.id = "creatures_created";
    pAsset5.statistics_asset = "world_statistics_creatures_created";
    pAsset5.color_hex = "#9670B5";
    pAsset5.path_icon = "ui/Icons/actor_traits/iconMiracleBorn";
    pAsset5.max = true;
    this.add(pAsset5);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset6 = new HistoryDataAsset();
    pAsset6.id = "food";
    pAsset6.color_hex = "#C67D49";
    pAsset6.path_icon = "ui/Icons/iconResBread";
    pAsset6.enabled_default = true;
    this.add(pAsset6);
    HistoryDataAsset pAsset7 = new HistoryDataAsset();
    pAsset7.id = "hungry";
    pAsset7.color_hex = "#7FA9BC";
    pAsset7.path_icon = "ui/Icons/iconHungry";
    this.add(pAsset7);
    HistoryDataAsset pAsset8 = new HistoryDataAsset();
    pAsset8.id = "starving";
    pAsset8.color_hex = "#BAC6B2";
    pAsset8.path_icon = "ui/Icons/iconStarving";
    pAsset8.enabled_default = true;
    this.add(pAsset8);
    HistoryDataAsset pAsset9 = new HistoryDataAsset();
    pAsset9.id = "items";
    pAsset9.color_hex = "#FFB22D";
    pAsset9.path_icon = "ui/Icons/iconReforge";
    this.add(pAsset9);
    HistoryDataAsset pAsset10 = new HistoryDataAsset();
    pAsset10.id = "homeless";
    pAsset10.color_hex = "#AD3640";
    pAsset10.path_icon = "ui/Icons/iconHomeless";
    this.add(pAsset10);
    HistoryDataAsset pAsset11 = new HistoryDataAsset();
    pAsset11.id = "housed";
    pAsset11.color_hex = "#358A23";
    pAsset11.path_icon = "ui/Icons/iconHoused";
    this.add(pAsset11);
    HistoryDataAsset pAsset12 = new HistoryDataAsset();
    pAsset12.id = "houses";
    pAsset12.statistics_asset = "world_statistics_houses";
    pAsset12.color_hex = "#B59780";
    pAsset12.path_icon = "ui/Icons/iconBuildings";
    pAsset12.max = true;
    this.add(pAsset12);
    HistoryDataAsset pAsset13 = new HistoryDataAsset();
    pAsset13.id = "houses_built";
    pAsset13.statistics_asset = "world_statistics_houses_built";
    pAsset13.color_hex = "#8D9995";
    pAsset13.path_icon = "ui/Icons/citizen_jobs/iconCitizenJobBuilder";
    pAsset13.max = true;
    this.add(pAsset13);
    HistoryDataAsset pAsset14 = new HistoryDataAsset();
    pAsset14.id = "houses_destroyed";
    pAsset14.statistics_asset = "world_statistics_houses_destroyed";
    pAsset14.color_hex = "#DA3722";
    pAsset14.path_icon = "ui/Icons/actor_traits/iconPyromaniac";
    pAsset14.max = true;
    pAsset14.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset14);
    HistoryDataAsset pAsset15 = new HistoryDataAsset();
    pAsset15.id = "cities";
    pAsset15.statistics_asset = "villages";
    pAsset15.color_hex = "#9B785E";
    pAsset15.path_icon = "ui/Icons/iconCitySelect";
    pAsset15.max = true;
    pAsset15.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset15);
    HistoryDataAsset pAsset16 = new HistoryDataAsset();
    pAsset16.id = "cities_destroyed";
    pAsset16.statistics_asset = "world_statistics_cities_destroyed";
    pAsset16.color_hex = "#AD363F";
    pAsset16.path_icon = "ui/Icons/iconCityDestroyed";
    pAsset16.max = true;
    pAsset16.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset16);
    HistoryDataAsset pAsset17 = new HistoryDataAsset();
    pAsset17.id = "cities_created";
    pAsset17.statistics_asset = "world_statistics_cities_created";
    pAsset17.color_hex = "#739297";
    pAsset17.path_icon = "ui/Icons/iconCity";
    pAsset17.max = true;
    pAsset17.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset17);
    HistoryDataAsset pAsset18 = new HistoryDataAsset();
    pAsset18.id = "cities_conquered";
    pAsset18.statistics_asset = "world_statistics_cities_conquered";
    pAsset18.color_hex = "#A1B1A2";
    pAsset18.path_icon = "ui/Icons/iconCityConquered";
    pAsset18.max = true;
    pAsset18.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset18);
    HistoryDataAsset pAsset19 = new HistoryDataAsset();
    pAsset19.id = "cities_rebelled";
    pAsset19.statistics_asset = "world_statistics_cities_rebelled";
    pAsset19.color_hex = "#FE7332";
    pAsset19.path_icon = "ui/Icons/worldrules/icon_rebellion";
    pAsset19.max = true;
    pAsset19.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset19);
    HistoryDataAsset pAsset20 = new HistoryDataAsset();
    pAsset20.id = "kingdoms";
    pAsset20.statistics_asset = "kingdoms";
    pAsset20.color_hex = "#FF8500";
    pAsset20.path_icon = "ui/Icons/iconKingdomList";
    pAsset20.max = true;
    pAsset20.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset20);
    HistoryDataAsset pAsset21 = new HistoryDataAsset();
    pAsset21.id = "kingdoms_created";
    pAsset21.statistics_asset = "world_statistics_kingdoms_created";
    pAsset21.color_hex = "#FFE563";
    pAsset21.path_icon = "ui/Icons/iconKingdom";
    pAsset21.max = true;
    pAsset21.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset21);
    HistoryDataAsset pAsset22 = new HistoryDataAsset();
    pAsset22.id = "kingdoms_destroyed";
    pAsset22.statistics_asset = "world_statistics_kingdoms_destroyed";
    pAsset22.color_hex = "#AD363F";
    pAsset22.path_icon = "ui/Icons/iconKingdomDestroyed";
    pAsset22.max = true;
    pAsset22.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset22);
    HistoryDataAsset pAsset23 = new HistoryDataAsset();
    pAsset23.id = "armies_destroyed";
    pAsset23.statistics_asset = "world_statistics_armies_destroyed";
    pAsset23.color_hex = "#AD363F";
    pAsset23.path_icon = "ui/Icons/iconArmiesDestroyed";
    pAsset23.max = true;
    pAsset23.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset23);
    HistoryDataAsset pAsset24 = new HistoryDataAsset();
    pAsset24.id = "kings";
    pAsset24.color_hex = "#B74007";
    pAsset24.path_icon = "ui/Icons/iconKings";
    pAsset24.max = true;
    this.add(pAsset24);
    HistoryDataAsset pAsset25 = new HistoryDataAsset();
    pAsset25.id = "leaders";
    pAsset25.color_hex = "#9670B5";
    pAsset25.path_icon = "ui/Icons/iconLeaders";
    pAsset25.max = true;
    this.add(pAsset25);
    HistoryDataAsset pAsset26 = new HistoryDataAsset();
    pAsset26.id = "gold";
    pAsset26.color_hex = "#FED760";
    pAsset26.path_icon = "ui/Icons/iconResGold";
    this.add(pAsset26);
    HistoryDataAsset pAsset27 = new HistoryDataAsset();
    pAsset27.id = "money";
    pAsset27.color_hex = "#F5C308";
    pAsset27.path_icon = "ui/Icons/iconMoney";
    pAsset27.max = true;
    this.add(pAsset27);
    HistoryDataAsset pAsset28 = new HistoryDataAsset();
    pAsset28.id = "families";
    pAsset28.statistics_asset = "families";
    pAsset28.color_hex = "#FF006E";
    pAsset28.path_icon = "ui/Icons/iconFamilyList";
    pAsset28.max = true;
    pAsset28.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset28);
    HistoryDataAsset pAsset29 = new HistoryDataAsset();
    pAsset29.id = "families_destroyed";
    pAsset29.statistics_asset = "world_statistics_families_destroyed";
    pAsset29.color_hex = "#FF006E";
    pAsset29.path_icon = "ui/Icons/iconFamilyDestroyed";
    pAsset29.max = true;
    pAsset29.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset29);
    HistoryDataAsset pAsset30 = new HistoryDataAsset();
    pAsset30.id = "families_created";
    pAsset30.statistics_asset = "world_statistics_families_created";
    pAsset30.color_hex = "#FF006E";
    pAsset30.path_icon = "ui/Icons/iconNewFamily";
    pAsset30.max = true;
    pAsset30.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset30);
    HistoryDataAsset pAsset31 = new HistoryDataAsset();
    pAsset31.id = "wood";
    pAsset31.color_hex = "#7C431C";
    pAsset31.path_icon = "ui/Icons/iconResWood";
    this.add(pAsset31);
    HistoryDataAsset pAsset32 = new HistoryDataAsset();
    pAsset32.id = "stone";
    pAsset32.color_hex = "#9E5858";
    pAsset32.path_icon = "ui/Icons/iconResStone";
    this.add(pAsset32);
    HistoryDataAsset pAsset33 = new HistoryDataAsset();
    pAsset33.id = "common_metals";
    pAsset33.color_hex = "#AAC7CF";
    pAsset33.path_icon = "ui/Icons/iconResCommonMetals";
    this.add(pAsset33);
    HistoryDataAsset pAsset34 = new HistoryDataAsset();
    pAsset34.id = "territory";
    pAsset34.color_hex = "#D08B4B";
    pAsset34.path_icon = "ui/Icons/iconZones";
    pAsset34.max = true;
    this.add(pAsset34);
    HistoryDataAsset pAsset35 = new HistoryDataAsset();
    pAsset35.id = "islands";
    pAsset35.statistics_asset = "world_statistics_islands";
    pAsset35.color_hex = "#805C49";
    pAsset35.path_icon = "ui/Icons/iconZones";
    pAsset35.max = true;
    this.add(pAsset35);
    HistoryDataAsset pAsset36 = new HistoryDataAsset();
    pAsset36.id = "army";
    pAsset36.color_hex = "#2DBF4D";
    pAsset36.path_icon = "ui/Icons/iconArmy";
    this.add(pAsset36);
    HistoryDataAsset pAsset37 = new HistoryDataAsset();
    pAsset37.id = "boats";
    pAsset37.color_hex = "#A0653B";
    pAsset37.path_icon = "ui/Icons/iconBoat";
    this.add(pAsset37);
    HistoryDataAsset pAsset38 = new HistoryDataAsset();
    pAsset38.id = "children";
    pAsset38.color_hex = "#EB29B3";
    pAsset38.path_icon = "ui/Icons/iconChildren";
    pAsset38.enabled_default = true;
    this.add(pAsset38);
    HistoryDataAsset pAsset39 = new HistoryDataAsset();
    pAsset39.id = "buildings";
    pAsset39.color_hex = "#BD7743";
    pAsset39.path_icon = "ui/Icons/iconBuildings";
    pAsset39.max = true;
    this.add(pAsset39);
    HistoryDataAsset pAsset40 = new HistoryDataAsset();
    pAsset40.id = "sick";
    pAsset40.color_hex = "#A129EB";
    pAsset40.path_icon = "ui/Icons/iconSick";
    pAsset40.sum = true;
    this.add(pAsset40);
    HistoryDataAsset pAsset41 = new HistoryDataAsset();
    pAsset41.id = "infected";
    pAsset41.statistics_asset = "world_statistics_infected";
    pAsset41.color_hex = "#31A347";
    pAsset41.path_icon = "ui/Icons/actor_traits/iconInfected";
    pAsset41.max = true;
    this.add(pAsset41);
    HistoryDataAsset pAsset42 = new HistoryDataAsset();
    pAsset42.id = "loyalty";
    pAsset42.color_hex = "#EB29B3";
    pAsset42.path_icon = "ui/Icons/iconLoyalty";
    this.add(pAsset42);
    HistoryDataAsset pAsset43 = new HistoryDataAsset();
    pAsset43.id = "happy";
    pAsset43.color_hex = "#FFEC3F";
    pAsset43.path_icon = "ui/Icons/iconHappiness_6";
    this.add(pAsset43);
    HistoryDataAsset pAsset44 = new HistoryDataAsset();
    pAsset44.id = "adults";
    pAsset44.color_hex = "#2B86D1";
    pAsset44.path_icon = "ui/Icons/iconAdults";
    pAsset44.enabled_default = true;
    this.add(pAsset44);
    HistoryDataAsset pAsset45 = new HistoryDataAsset();
    pAsset45.id = "deaths";
    pAsset45.color_hex = "#282828";
    pAsset45.path_icon = "ui/Icons/iconDead";
    pAsset45.max = true;
    this.add(pAsset45);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset46 = new HistoryDataAsset();
    pAsset46.id = "deaths_attackers";
    pAsset46.localized_key = "attackers_deaths";
    pAsset46.color_hex = "#AD9878";
    pAsset46.path_icon = "ui/Icons/iconDeathAttackers";
    pAsset46.sum = true;
    this.add(pAsset46);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset47 = new HistoryDataAsset();
    pAsset47.id = "deaths_defenders";
    pAsset47.localized_key = "defenders_deaths";
    pAsset47.color_hex = "#979894";
    pAsset47.path_icon = "ui/Icons/iconDeathDefenders";
    pAsset47.sum = true;
    this.add(pAsset47);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset48 = new HistoryDataAsset();
    pAsset48.id = "money_attackers";
    pAsset48.localized_key = "attackers_money";
    pAsset48.color_hex = "#C3800E";
    pAsset48.path_icon = "ui/Icons/iconMoney";
    pAsset48.max = true;
    this.add(pAsset48);
    HistoryDataAsset pAsset49 = new HistoryDataAsset();
    pAsset49.id = "money_defenders";
    pAsset49.localized_key = "defenders_money";
    pAsset49.color_hex = "#FFFF49";
    pAsset49.path_icon = "ui/Icons/iconMoney";
    pAsset49.max = true;
    this.add(pAsset49);
    HistoryDataAsset pAsset50 = new HistoryDataAsset();
    pAsset50.id = "births";
    pAsset50.color_hex = "#EB5D4D";
    pAsset50.path_icon = "ui/Icons/iconBirths";
    pAsset50.max = true;
    pAsset50.enabled_default = true;
    this.add(pAsset50);
    this.t.category_group |= GraphCategoryGroup.Deaths;
    HistoryDataAsset pAsset51 = new HistoryDataAsset();
    pAsset51.id = "renown";
    pAsset51.color_hex = "#FFFF49";
    pAsset51.path_icon = "ui/Icons/iconRenown";
    pAsset51.max = true;
    this.add(pAsset51);
    HistoryDataAsset pAsset52 = new HistoryDataAsset();
    pAsset52.id = "joined";
    pAsset52.color_hex = "#DBC93F";
    pAsset52.path_icon = "ui/Icons/iconStatisticsJoined";
    pAsset52.localized_key = "statistics_joined";
    pAsset52.localized_key_description = "statistics_joined".Description();
    pAsset52.max = true;
    this.add(pAsset52);
    HistoryDataAsset pAsset53 = new HistoryDataAsset();
    pAsset53.id = "left";
    pAsset53.color_hex = "#282828";
    pAsset53.path_icon = "ui/Icons/iconStatisticsLeft";
    pAsset53.localized_key = "statistics_left";
    pAsset53.localized_key_description = "statistics_left".Description();
    pAsset53.max = true;
    this.add(pAsset53);
    HistoryDataAsset pAsset54 = new HistoryDataAsset();
    pAsset54.id = "moved";
    pAsset54.color_hex = "#282828";
    pAsset54.path_icon = "ui/Icons/iconStatisticsMoved";
    pAsset54.localized_key = "statistics_moved";
    pAsset54.localized_key_description = "statistics_moved".Description();
    pAsset54.max = true;
    this.add(pAsset54);
    HistoryDataAsset pAsset55 = new HistoryDataAsset();
    pAsset55.id = "migrated";
    pAsset55.color_hex = "#282828";
    pAsset55.path_icon = "ui/Icons/iconStatisticsGoodLookingMigrants";
    pAsset55.localized_key = "statistics_migrated";
    pAsset55.localized_key_description = "statistics_migrated".Description();
    pAsset55.max = true;
    this.add(pAsset55);
    HistoryDataAsset pAsset56 = new HistoryDataAsset();
    pAsset56.id = "males";
    pAsset56.color_hex = "#2B86D1";
    pAsset56.path_icon = "ui/Icons/iconMale";
    this.add(pAsset56);
    HistoryDataAsset pAsset57 = new HistoryDataAsset();
    pAsset57.id = "females";
    pAsset57.color_hex = "#AD3640";
    pAsset57.path_icon = "ui/Icons/iconFemale";
    this.add(pAsset57);
    HistoryDataAsset pAsset58 = new HistoryDataAsset();
    pAsset58.id = "speakers_converted";
    pAsset58.color_hex = "#a42cec";
    pAsset58.path_icon = "ui/Icons/iconSpeakersTotal";
    pAsset58.max = true;
    this.add(pAsset58);
    HistoryDataAsset pAsset59 = new HistoryDataAsset();
    pAsset59.id = "speakers_new";
    pAsset59.color_hex = "#A129EB";
    pAsset59.path_icon = "ui/Icons/iconSpeakersNew";
    pAsset59.max = true;
    this.add(pAsset59);
    HistoryDataAsset pAsset60 = new HistoryDataAsset();
    pAsset60.id = "speakers_lost";
    pAsset60.color_hex = "#B92935";
    pAsset60.path_icon = "ui/Icons/iconSpeakersLost";
    pAsset60.max = true;
    this.add(pAsset60);
    HistoryDataAsset pAsset61 = new HistoryDataAsset();
    pAsset61.id = "books_written";
    pAsset61.statistics_asset = "world_statistics_books_written";
    pAsset61.color_hex = "#ac9c7c";
    pAsset61.path_icon = "ui/Icons/iconBooksWritten";
    pAsset61.max = true;
    pAsset61.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset61);
    HistoryDataAsset pAsset62 = new HistoryDataAsset();
    pAsset62.id = "books";
    pAsset62.statistics_asset = "books";
    pAsset62.color_hex = "#358A23";
    pAsset62.path_icon = "ui/Icons/iconBooks";
    pAsset62.max = true;
    pAsset62.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset62);
    HistoryDataAsset pAsset63 = new HistoryDataAsset();
    pAsset63.id = "books_burnt";
    pAsset63.statistics_asset = "world_statistics_books_burnt";
    pAsset63.color_hex = "#AD3442";
    pAsset63.path_icon = "ui/Icons/iconBooksDestroyed";
    pAsset63.max = true;
    pAsset63.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset63);
    HistoryDataAsset pAsset64 = new HistoryDataAsset();
    pAsset64.id = "books_read";
    pAsset64.statistics_asset = "world_statistics_books_read";
    pAsset64.color_hex = "#7C29B9";
    pAsset64.path_icon = "ui/Icons/iconBooksRead";
    pAsset64.max = true;
    pAsset64.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset64);
    HistoryDataAsset pAsset65 = new HistoryDataAsset();
    pAsset65.id = "army_attackers";
    pAsset65.localized_key = "attackers_army";
    pAsset65.color_hex = "#996753";
    pAsset65.path_icon = "ui/Icons/iconWarriors";
    this.add(pAsset65);
    HistoryDataAsset pAsset66 = new HistoryDataAsset();
    pAsset66.id = "army_defenders";
    pAsset66.localized_key = "defenders_army";
    pAsset66.color_hex = "#698B99";
    pAsset66.path_icon = "ui/Icons/iconShield";
    this.add(pAsset66);
    HistoryDataAsset pAsset67 = new HistoryDataAsset();
    pAsset67.id = "population_attackers";
    pAsset67.localized_key = "attackers_population";
    pAsset67.color_hex = "#325870";
    pAsset67.path_icon = "ui/Icons/iconPopulationAttackers";
    this.add(pAsset67);
    HistoryDataAsset pAsset68 = new HistoryDataAsset();
    pAsset68.id = "population_defenders";
    pAsset68.localized_key = "defenders_population";
    pAsset68.color_hex = "#414349";
    pAsset68.path_icon = "ui/Icons/iconPopulationDefenders";
    this.add(pAsset68);
    HistoryDataAsset pAsset69 = new HistoryDataAsset();
    pAsset69.id = "kills";
    pAsset69.color_hex = "#D7C493";
    pAsset69.path_icon = "ui/Icons/iconKills";
    pAsset69.max = true;
    this.add(pAsset69);
    HistoryDataAsset pAsset70 = new HistoryDataAsset();
    pAsset70.id = "alliances";
    pAsset70.statistics_asset = "alliances";
    pAsset70.color_hex = "#A7B7A8";
    pAsset70.path_icon = "ui/Icons/iconAllianceList";
    pAsset70.max = true;
    pAsset70.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset70);
    HistoryDataAsset pAsset71 = new HistoryDataAsset();
    pAsset71.id = "alliances_dissolved";
    pAsset71.statistics_asset = "world_statistics_alliances_dissolved";
    pAsset71.color_hex = "#CE2C29";
    pAsset71.path_icon = "ui/Icons/iconAllianceDissolved";
    pAsset71.max = true;
    pAsset71.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset71);
    HistoryDataAsset pAsset72 = new HistoryDataAsset();
    pAsset72.id = "alliances_made";
    pAsset72.statistics_asset = "world_statistics_alliances_made";
    pAsset72.color_hex = "#1F4792";
    pAsset72.path_icon = "ui/Icons/iconAlliance";
    pAsset72.max = true;
    pAsset72.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset72);
    HistoryDataAsset pAsset73 = new HistoryDataAsset();
    pAsset73.id = "clans";
    pAsset73.statistics_asset = "clans";
    pAsset73.color_hex = "#65A13F";
    pAsset73.path_icon = "ui/Icons/iconClanList";
    pAsset73.max = true;
    pAsset73.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset73);
    HistoryDataAsset pAsset74 = new HistoryDataAsset();
    pAsset74.id = "clans_destroyed";
    pAsset74.statistics_asset = "world_statistics_clans_destroyed";
    pAsset74.color_hex = "#AD363F";
    pAsset74.path_icon = "ui/Icons/iconClanDestroyed";
    pAsset74.max = true;
    pAsset74.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset74);
    HistoryDataAsset pAsset75 = new HistoryDataAsset();
    pAsset75.id = "clans_created";
    pAsset75.statistics_asset = "world_statistics_clans_created";
    pAsset75.color_hex = "#783057";
    pAsset75.path_icon = "ui/Icons/iconClan";
    pAsset75.max = true;
    pAsset75.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset75);
    HistoryDataAsset pAsset76 = new HistoryDataAsset();
    pAsset76.id = "cultures";
    pAsset76.statistics_asset = "cultures";
    pAsset76.color_hex = "#AD9878";
    pAsset76.path_icon = "ui/Icons/iconCultureList";
    pAsset76.max = true;
    pAsset76.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset76);
    HistoryDataAsset pAsset77 = new HistoryDataAsset();
    pAsset77.id = "cultures_forgotten";
    pAsset77.statistics_asset = "world_statistics_cultures_forgotten";
    pAsset77.color_hex = "#AD9A73";
    pAsset77.path_icon = "ui/Icons/iconCultureForgotten";
    pAsset77.max = true;
    pAsset77.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset77);
    HistoryDataAsset pAsset78 = new HistoryDataAsset();
    pAsset78.id = "cultures_created";
    pAsset78.statistics_asset = "world_statistics_cultures_created";
    pAsset78.color_hex = "#D7C493";
    pAsset78.path_icon = "ui/Icons/iconCulture";
    pAsset78.max = true;
    pAsset78.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset78);
    HistoryDataAsset pAsset79 = new HistoryDataAsset();
    pAsset79.id = "languages";
    pAsset79.statistics_asset = "languages";
    pAsset79.color_hex = "#A7B7A8";
    pAsset79.path_icon = "ui/Icons/iconLanguageList";
    pAsset79.max = true;
    pAsset79.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset79);
    HistoryDataAsset pAsset80 = new HistoryDataAsset();
    pAsset80.id = "languages_forgotten";
    pAsset80.statistics_asset = "world_statistics_languages_forgotten";
    pAsset80.color_hex = "#737874";
    pAsset80.path_icon = "ui/Icons/iconLanguageForgotten";
    pAsset80.max = true;
    pAsset80.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset80);
    HistoryDataAsset pAsset81 = new HistoryDataAsset();
    pAsset81.id = "languages_created";
    pAsset81.statistics_asset = "world_statistics_languages_created";
    pAsset81.color_hex = "#FFFFFF";
    pAsset81.path_icon = "ui/Icons/iconLanguage";
    pAsset81.max = true;
    pAsset81.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset81);
    HistoryDataAsset pAsset82 = new HistoryDataAsset();
    pAsset82.id = "subspecies";
    pAsset82.statistics_asset = "subspecies";
    pAsset82.color_hex = "#FFFFFF";
    pAsset82.path_icon = "ui/Icons/iconSpecies";
    pAsset82.max = true;
    pAsset82.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset82);
    HistoryDataAsset pAsset83 = new HistoryDataAsset();
    pAsset83.id = "subspecies_extinct";
    pAsset83.statistics_asset = "world_statistics_subspecies_extinct";
    pAsset83.color_hex = "#AD9A7B";
    pAsset83.path_icon = "ui/Icons/iconSpeciesExtinct";
    pAsset83.max = true;
    pAsset83.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset83);
    HistoryDataAsset pAsset84 = new HistoryDataAsset();
    pAsset84.id = "subspecies_created";
    pAsset84.statistics_asset = "world_statistics_subspecies_created";
    pAsset84.color_hex = "#FFFFFF";
    pAsset84.path_icon = "ui/Icons/iconSpecies";
    pAsset84.max = true;
    pAsset84.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset84);
    HistoryDataAsset pAsset85 = new HistoryDataAsset();
    pAsset85.id = "plots_started";
    pAsset85.statistics_asset = "world_statistics_plots_started";
    pAsset85.color_hex = "#ac9c7c";
    pAsset85.path_icon = "ui/Icons/iconPlot";
    pAsset85.max = true;
    pAsset85.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset85);
    HistoryDataAsset pAsset86 = new HistoryDataAsset();
    pAsset86.id = "plots";
    pAsset86.statistics_asset = "plots";
    pAsset86.color_hex = "#3a3bbb";
    pAsset86.path_icon = "ui/Icons/iconPlotList";
    pAsset86.max = true;
    pAsset86.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset86);
    HistoryDataAsset pAsset87 = new HistoryDataAsset();
    pAsset87.id = "plots_forgotten";
    pAsset87.statistics_asset = "world_statistics_plots_forgotten";
    pAsset87.color_hex = "#AD9A7B";
    pAsset87.path_icon = "ui/Icons/iconPlotForgotten";
    pAsset87.max = true;
    pAsset87.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset87);
    HistoryDataAsset pAsset88 = new HistoryDataAsset();
    pAsset88.id = "plots_succeeded";
    pAsset88.statistics_asset = "world_statistics_plots_succeeded";
    pAsset88.color_hex = "#3a3bbb";
    pAsset88.path_icon = "ui/Icons/iconPlotSucceeded";
    pAsset88.max = true;
    pAsset88.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset88);
    HistoryDataAsset pAsset89 = new HistoryDataAsset();
    pAsset89.id = "religions";
    pAsset89.statistics_asset = "religions";
    pAsset89.color_hex = "#8EFFD9";
    pAsset89.path_icon = "ui/Icons/iconReligionList";
    pAsset89.max = true;
    this.add(pAsset89);
    HistoryDataAsset pAsset90 = new HistoryDataAsset();
    pAsset90.id = "religions_forgotten";
    pAsset90.statistics_asset = "world_statistics_religions_forgotten";
    pAsset90.color_hex = "#CEDBBD";
    pAsset90.path_icon = "ui/Icons/iconReligionForgotten";
    pAsset90.max = true;
    pAsset90.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset90);
    HistoryDataAsset pAsset91 = new HistoryDataAsset();
    pAsset91.id = "religions_created";
    pAsset91.statistics_asset = "world_statistics_religions_created";
    pAsset91.color_hex = "#46DCE3";
    pAsset91.path_icon = "ui/Icons/iconReligion";
    pAsset91.max = true;
    pAsset91.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset91);
    HistoryDataAsset pAsset92 = new HistoryDataAsset();
    pAsset92.id = "wars";
    pAsset92.statistics_asset = "wars";
    pAsset92.color_hex = "#D3D9C5";
    pAsset92.path_icon = "ui/Icons/iconWar";
    pAsset92.max = true;
    this.add(pAsset92);
    HistoryDataAsset pAsset93 = new HistoryDataAsset();
    pAsset93.id = "peaces_made";
    pAsset93.statistics_asset = "world_statistics_peaces_made";
    pAsset93.color_hex = "#51B349";
    pAsset93.path_icon = "ui/Icons/actor_traits/iconPacifist";
    pAsset93.max = true;
    pAsset93.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset93);
    HistoryDataAsset pAsset94 = new HistoryDataAsset();
    pAsset94.id = "wars_started";
    pAsset94.statistics_asset = "world_statistics_wars_started";
    pAsset94.color_hex = "#3a3bbb";
    pAsset94.path_icon = "ui/Icons/iconWhisperOfWar";
    pAsset94.max = true;
    pAsset94.category_group = GraphCategoryGroup.Noosphere;
    this.add(pAsset94);
    HistoryDataAsset pAsset95 = new HistoryDataAsset();
    pAsset95.id = "deaths_total";
    pAsset95.statistics_asset = "world_statistics_deaths_total";
    pAsset95.color_hex = "#A7B7A8";
    pAsset95.path_icon = "ui/Icons/iconDead";
    pAsset95.max = true;
    pAsset95.category_group = GraphCategoryGroup.Deaths;
    this.add(pAsset95);
    this.clone("deaths_natural", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_natural";
    this.t.path_icon = "ui/Icons/iconClock";
    this.t.enabled_default = true;
    this.t.color_hex = "#AF6E19";
    this.clone("deaths_hunger", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_hunger";
    this.t.path_icon = "ui/Icons/iconDeathsHunger";
    this.t.enabled_default = true;
    this.t.color_hex = "#BDD7DE";
    this.clone("deaths_eaten", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_eaten";
    this.t.path_icon = "ui/Icons/iconDeathsEaten";
    this.t.color_hex = "#EFAE52";
    this.clone("deaths_plague", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_plague";
    this.t.path_icon = "ui/Icons/actor_traits/iconPlague";
    this.t.color_hex = "#DA18D8";
    this.clone("deaths_poison", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_poison";
    this.t.path_icon = "ui/Icons/iconPoisoned";
    this.t.color_hex = "#A31BC9";
    this.clone("deaths_infection", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_infection";
    this.t.path_icon = "ui/Icons/actor_traits/iconInfected";
    this.t.color_hex = "#31A347";
    this.clone("deaths_tumor", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_tumor";
    this.t.path_icon = "ui/Icons/iconTumor";
    this.t.color_hex = "#EF3F58";
    this.clone("deaths_acid", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_acid";
    this.t.path_icon = "ui/Icons/iconAcid";
    this.t.color_hex = "#ADCF3A";
    this.clone("deaths_fire", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_fire";
    this.t.path_icon = "ui/Icons/iconFire";
    this.t.color_hex = "#D92D14";
    this.clone("deaths_divine", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_divine";
    this.t.path_icon = "ui/Icons/iconDivineLight";
    this.t.color_hex = "#FFE490";
    this.clone("deaths_weapon", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_weapon";
    this.t.path_icon = "ui/Icons/actor_traits/iconBloodlust";
    this.t.enabled_default = true;
    this.t.color_hex = "#7F1212";
    this.clone("deaths_gravity", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_gravity";
    this.t.path_icon = "ui/Icons/worldrules/icon_grow_trees";
    this.t.color_hex = "#65A13F";
    this.clone("deaths_drowning", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_drowning";
    this.t.path_icon = "ui/Icons/iconTileDeepOcean";
    this.t.color_hex = "#00B9D1";
    this.clone("deaths_water", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_water";
    this.t.path_icon = "ui/Icons/iconRain";
    this.t.color_hex = "#CBF4FF";
    this.clone("deaths_explosion", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_explosion";
    this.t.path_icon = "ui/Icons/worldrules/icon_exploding_mushrooms";
    this.t.color_hex = "#FFB22D";
    this.clone("deaths_other", "deaths_total");
    this.t.statistics_asset = "world_statistics_deaths_other";
    this.t.path_icon = "ui/Icons/iconDead";
    this.t.color_hex = "#D7C493";
    HistoryDataAsset pAsset96 = new HistoryDataAsset();
    pAsset96.id = "metamorphosis";
    pAsset96.statistics_asset = "world_statistics_metamorphosis";
    pAsset96.color_hex = "#8EFFD9";
    pAsset96.path_icon = "ui/Icons/subspecies_traits/subspecies_trait_reproduction_metamorph";
    pAsset96.max = true;
    this.add(pAsset96);
    HistoryDataAsset pAsset97 = new HistoryDataAsset();
    pAsset97.id = "evolutions";
    pAsset97.statistics_asset = "world_statistics_evolutions";
    pAsset97.color_hex = "#a3836c";
    pAsset97.path_icon = "ui/Icons/iconMonolith";
    pAsset97.max = true;
    this.add(pAsset97);
    HistoryDataAsset pAsset98 = new HistoryDataAsset();
    pAsset98.id = "trees";
    pAsset98.statistics_asset = "world_statistics_trees";
    pAsset98.color_hex = "#86BC4E";
    pAsset98.path_icon = "ui/Icons/iconFertilizerTrees";
    this.add(pAsset98);
    HistoryDataAsset pAsset99 = new HistoryDataAsset();
    pAsset99.id = "vegetation";
    pAsset99.statistics_asset = "world_statistics_vegetation";
    pAsset99.color_hex = "#31A347";
    pAsset99.path_icon = "ui/Icons/iconFertilizerPlants";
    this.add(pAsset99);
  }

  public void addBiomes()
  {
    HistoryDataAsset pAsset1 = new HistoryDataAsset();
    pAsset1.id = "grass";
    pAsset1.statistics_asset = "world_statistics_grass";
    pAsset1.color_hex = "#5EE54E";
    pAsset1.path_icon = "ui/Icons/iconSeedGrass";
    pAsset1.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset1);
    HistoryDataAsset pAsset2 = new HistoryDataAsset();
    pAsset2.id = "savanna";
    pAsset2.statistics_asset = "world_statistics_savanna";
    pAsset2.color_hex = "#D4854C";
    pAsset2.path_icon = "ui/Icons/iconSeedSavanna";
    pAsset2.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset2);
    HistoryDataAsset pAsset3 = new HistoryDataAsset();
    pAsset3.id = "jungle";
    pAsset3.statistics_asset = "world_statistics_jungle";
    pAsset3.color_hex = "#45C131";
    pAsset3.path_icon = "ui/Icons/iconSeedJungle";
    pAsset3.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset3);
    HistoryDataAsset pAsset4 = new HistoryDataAsset();
    pAsset4.id = "desert";
    pAsset4.statistics_asset = "world_statistics_desert";
    pAsset4.color_hex = "#E9C057";
    pAsset4.path_icon = "ui/Icons/iconSeedDesert";
    pAsset4.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset4);
    HistoryDataAsset pAsset5 = new HistoryDataAsset();
    pAsset5.id = "lemon";
    pAsset5.statistics_asset = "world_statistics_lemon";
    pAsset5.color_hex = "#FDD435";
    pAsset5.path_icon = "ui/Icons/iconSeedLemon";
    pAsset5.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset5);
    HistoryDataAsset pAsset6 = new HistoryDataAsset();
    pAsset6.id = "permafrost";
    pAsset6.statistics_asset = "world_statistics_permafrost";
    pAsset6.color_hex = "#9AF8FF";
    pAsset6.path_icon = "ui/Icons/iconSeedPermafrost";
    pAsset6.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset6);
    HistoryDataAsset pAsset7 = new HistoryDataAsset();
    pAsset7.id = "swamp";
    pAsset7.statistics_asset = "world_statistics_swamp";
    pAsset7.color_hex = "#447528";
    pAsset7.path_icon = "ui/Icons/iconSeedSwamp";
    pAsset7.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset7);
    HistoryDataAsset pAsset8 = new HistoryDataAsset();
    pAsset8.id = "crystal";
    pAsset8.statistics_asset = "world_statistics_crystal";
    pAsset8.color_hex = "#7D6887";
    pAsset8.path_icon = "ui/Icons/iconSeedCrystal";
    pAsset8.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset8);
    HistoryDataAsset pAsset9 = new HistoryDataAsset();
    pAsset9.id = "enchanted";
    pAsset9.statistics_asset = "world_statistics_enchanted";
    pAsset9.color_hex = "#F6FFC2";
    pAsset9.path_icon = "ui/Icons/iconSeedEnchanted";
    pAsset9.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset9);
    HistoryDataAsset pAsset10 = new HistoryDataAsset();
    pAsset10.id = "corruption";
    pAsset10.statistics_asset = "world_statistics_corruption";
    pAsset10.color_hex = "#3D2F40";
    pAsset10.path_icon = "ui/Icons/iconSeedCorrupted";
    pAsset10.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset10);
    HistoryDataAsset pAsset11 = new HistoryDataAsset();
    pAsset11.id = "infernal";
    pAsset11.statistics_asset = "world_statistics_infernal";
    pAsset11.color_hex = "#D0371D";
    pAsset11.path_icon = "ui/Icons/iconSeedInfernal";
    pAsset11.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset11);
    HistoryDataAsset pAsset12 = new HistoryDataAsset();
    pAsset12.id = "candy";
    pAsset12.statistics_asset = "world_statistics_candy";
    pAsset12.color_hex = "#C73736";
    pAsset12.path_icon = "ui/Icons/iconSeedCandy";
    pAsset12.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset12);
    HistoryDataAsset pAsset13 = new HistoryDataAsset();
    pAsset13.id = "mushroom";
    pAsset13.statistics_asset = "world_statistics_mushroom";
    pAsset13.color_hex = "#D65C4A";
    pAsset13.path_icon = "ui/Icons/iconSeedMushroom";
    pAsset13.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset13);
    HistoryDataAsset pAsset14 = new HistoryDataAsset();
    pAsset14.id = "wasteland";
    pAsset14.statistics_asset = "world_statistics_wasteland";
    pAsset14.color_hex = "#65A03F";
    pAsset14.path_icon = "ui/Icons/achievements/achievements_wastelandbiome";
    pAsset14.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset14);
    HistoryDataAsset pAsset15 = new HistoryDataAsset();
    pAsset15.id = "birch";
    pAsset15.statistics_asset = "world_statistics_birch";
    pAsset15.color_hex = "#757A81";
    pAsset15.path_icon = "ui/Icons/iconSeedBirch";
    pAsset15.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset15);
    HistoryDataAsset pAsset16 = new HistoryDataAsset();
    pAsset16.id = "maple";
    pAsset16.statistics_asset = "world_statistics_maple";
    pAsset16.color_hex = "#B92935";
    pAsset16.path_icon = "ui/Icons/iconSeedMaple";
    pAsset16.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset16);
    HistoryDataAsset pAsset17 = new HistoryDataAsset();
    pAsset17.id = "rocklands";
    pAsset17.statistics_asset = "world_statistics_rocklands";
    pAsset17.color_hex = "#3C6732";
    pAsset17.path_icon = "ui/Icons/iconSeedRocklands";
    pAsset17.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset17);
    HistoryDataAsset pAsset18 = new HistoryDataAsset();
    pAsset18.id = "garlic";
    pAsset18.statistics_asset = "world_statistics_garlic";
    pAsset18.color_hex = "#D7C493";
    pAsset18.path_icon = "ui/Icons/iconSeedGarlic";
    pAsset18.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset18);
    HistoryDataAsset pAsset19 = new HistoryDataAsset();
    pAsset19.id = "flower";
    pAsset19.statistics_asset = "world_statistics_flower";
    pAsset19.color_hex = "#9E3A4C";
    pAsset19.path_icon = "ui/Icons/iconSeedFlower";
    pAsset19.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset19);
    HistoryDataAsset pAsset20 = new HistoryDataAsset();
    pAsset20.id = "celestial";
    pAsset20.statistics_asset = "world_statistics_celestial";
    pAsset20.color_hex = "#F6F248";
    pAsset20.path_icon = "ui/Icons/iconSeedCelestial";
    pAsset20.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset20);
    HistoryDataAsset pAsset21 = new HistoryDataAsset();
    pAsset21.id = "clover";
    pAsset21.statistics_asset = "world_statistics_clover";
    pAsset21.color_hex = "#35B929";
    pAsset21.path_icon = "ui/Icons/iconSeedClover";
    pAsset21.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset21);
    HistoryDataAsset pAsset22 = new HistoryDataAsset();
    pAsset22.id = "singularity";
    pAsset22.statistics_asset = "world_statistics_singularity";
    pAsset22.color_hex = "#A9CAFF";
    pAsset22.path_icon = "ui/Icons/iconSeedSingularity";
    pAsset22.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset22);
    HistoryDataAsset pAsset23 = new HistoryDataAsset();
    pAsset23.id = "paradox";
    pAsset23.statistics_asset = "world_statistics_paradox";
    pAsset23.color_hex = "#C3800E";
    pAsset23.path_icon = "ui/Icons/iconSeedParadox";
    pAsset23.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset23);
    HistoryDataAsset pAsset24 = new HistoryDataAsset();
    pAsset24.id = "sand";
    pAsset24.statistics_asset = "world_statistics_sand";
    pAsset24.color_hex = "#F6BD67";
    pAsset24.path_icon = "ui/Icons/iconTileSand";
    pAsset24.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset24);
    HistoryDataAsset pAsset25 = new HistoryDataAsset();
    pAsset25.id = "biomass";
    pAsset25.statistics_asset = "world_statistics_biomass";
    pAsset25.color_hex = "#29B326";
    pAsset25.path_icon = "ui/Icons/iconBiomass";
    pAsset25.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset25);
    HistoryDataAsset pAsset26 = new HistoryDataAsset();
    pAsset26.id = "cybertile";
    pAsset26.statistics_asset = "world_statistics_cybertile";
    pAsset26.color_hex = "#BD8137";
    pAsset26.path_icon = "ui/Icons/iconCybercore";
    pAsset26.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset26);
    HistoryDataAsset pAsset27 = new HistoryDataAsset();
    pAsset27.id = "pumpkin";
    pAsset27.statistics_asset = "world_statistics_pumpkin";
    pAsset27.color_hex = "#FF8D1A";
    pAsset27.path_icon = "ui/Icons/iconSuperPumpkin";
    pAsset27.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset27);
    HistoryDataAsset pAsset28 = new HistoryDataAsset();
    pAsset28.id = "tumor";
    pAsset28.statistics_asset = "world_statistics_tumor";
    pAsset28.color_hex = "#D1184F";
    pAsset28.path_icon = "ui/Icons/iconTumor";
    pAsset28.category_group = GraphCategoryGroup.Biomes;
    this.add(pAsset28);
  }

  public void addTiles()
  {
    HistoryDataAsset pAsset1 = new HistoryDataAsset();
    pAsset1.id = "water";
    pAsset1.statistics_asset = "world_statistics_water";
    pAsset1.color_hex = "#00B9D1";
    pAsset1.path_icon = "ui/Icons/iconTileDeepOcean";
    pAsset1.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset1);
    HistoryDataAsset pAsset2 = new HistoryDataAsset();
    pAsset2.id = "soil";
    pAsset2.statistics_asset = "world_statistics_soil";
    pAsset2.color_hex = "#D08B4B";
    pAsset2.path_icon = "ui/Icons/iconTileSoil";
    pAsset2.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset2);
    HistoryDataAsset pAsset3 = new HistoryDataAsset();
    pAsset3.id = "summit";
    pAsset3.statistics_asset = "world_statistics_summit";
    pAsset3.color_hex = "#BBEFFF";
    pAsset3.path_icon = "ui/Icons/iconTileSummit";
    pAsset3.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset3);
    HistoryDataAsset pAsset4 = new HistoryDataAsset();
    pAsset4.id = "mountains";
    pAsset4.statistics_asset = "world_statistics_mountains";
    pAsset4.color_hex = "#97ADB7";
    pAsset4.path_icon = "ui/Icons/iconTileMountains";
    pAsset4.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset4);
    HistoryDataAsset pAsset5 = new HistoryDataAsset();
    pAsset5.id = "hills";
    pAsset5.statistics_asset = "world_statistics_hills";
    pAsset5.color_hex = "#657688";
    pAsset5.path_icon = "ui/Icons/iconTileHills";
    pAsset5.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset5);
    HistoryDataAsset pAsset6 = new HistoryDataAsset();
    pAsset6.id = "lava";
    pAsset6.statistics_asset = "world_statistics_lava";
    pAsset6.color_hex = "#BB311C";
    pAsset6.path_icon = "ui/Icons/iconLava";
    pAsset6.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset6);
    HistoryDataAsset pAsset7 = new HistoryDataAsset();
    pAsset7.id = "pit";
    pAsset7.statistics_asset = "world_statistics_pit";
    pAsset7.color_hex = "#53EDE3";
    pAsset7.path_icon = "ui/Icons/iconTileShallowWater";
    pAsset7.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset7);
    HistoryDataAsset pAsset8 = new HistoryDataAsset();
    pAsset8.id = "field";
    pAsset8.statistics_asset = "world_statistics_field";
    pAsset8.color_hex = "#C3800E";
    pAsset8.path_icon = "ui/Icons/citizen_jobs/iconCitizenJobFarmer";
    pAsset8.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset8);
    HistoryDataAsset pAsset9 = new HistoryDataAsset();
    pAsset9.id = "fireworks";
    pAsset9.statistics_asset = "world_statistics_fireworks";
    pAsset9.color_hex = "#FF0000";
    pAsset9.path_icon = "ui/Icons/iconFireworks";
    pAsset9.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset9);
    HistoryDataAsset pAsset10 = new HistoryDataAsset();
    pAsset10.id = "frozen";
    pAsset10.statistics_asset = "world_statistics_frozen";
    pAsset10.color_hex = "#60C1C8";
    pAsset10.path_icon = "ui/Icons/iconFrozen";
    pAsset10.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset10);
    HistoryDataAsset pAsset11 = new HistoryDataAsset();
    pAsset11.id = "fuse";
    pAsset11.statistics_asset = "world_statistics_fuse";
    pAsset11.color_hex = "#B55400";
    pAsset11.path_icon = "ui/Icons/iconFuse";
    pAsset11.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset11);
    HistoryDataAsset pAsset12 = new HistoryDataAsset();
    pAsset12.id = "ice";
    pAsset12.statistics_asset = "world_statistics_ice";
    pAsset12.color_hex = "#9AF8FF";
    pAsset12.path_icon = "ui/Icons/iconIceberg";
    pAsset12.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset12);
    HistoryDataAsset pAsset13 = new HistoryDataAsset();
    pAsset13.id = "landmine";
    pAsset13.statistics_asset = "world_statistics_landmine";
    pAsset13.color_hex = "#FF2E00";
    pAsset13.path_icon = "ui/Icons/iconLandmine";
    pAsset13.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset13);
    HistoryDataAsset pAsset14 = new HistoryDataAsset();
    pAsset14.id = "road";
    pAsset14.statistics_asset = "world_statistics_road";
    pAsset14.color_hex = "#80D03F";
    pAsset14.path_icon = "ui/Icons/citizen_jobs/iconCitizenJobRoadBuilder";
    pAsset14.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset14);
    HistoryDataAsset pAsset15 = new HistoryDataAsset();
    pAsset15.id = "snow";
    pAsset15.statistics_asset = "world_statistics_snow";
    pAsset15.color_hex = "#F2F3ED";
    pAsset15.path_icon = "ui/Icons/iconSnow";
    pAsset15.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset15);
    HistoryDataAsset pAsset16 = new HistoryDataAsset();
    pAsset16.id = "tnt";
    pAsset16.statistics_asset = "world_statistics_tnt";
    pAsset16.color_hex = "#F67A39";
    pAsset16.path_icon = "ui/Icons/iconTnt";
    pAsset16.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset16);
    HistoryDataAsset pAsset17 = new HistoryDataAsset();
    pAsset17.id = "wall";
    pAsset17.statistics_asset = "world_statistics_wall";
    pAsset17.color_hex = "#425B78";
    pAsset17.path_icon = "ui/Icons/iconWallIron";
    pAsset17.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset17);
    HistoryDataAsset pAsset18 = new HistoryDataAsset();
    pAsset18.id = "water_bomb";
    pAsset18.statistics_asset = "world_statistics_water_bomb";
    pAsset18.color_hex = "#00A2DE";
    pAsset18.path_icon = "ui/Icons/iconWaterBomb";
    pAsset18.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset18);
    HistoryDataAsset pAsset19 = new HistoryDataAsset();
    pAsset19.id = "grey_goo";
    pAsset19.statistics_asset = "world_statistics_grey_goo";
    pAsset19.color_hex = "#4D666D";
    pAsset19.path_icon = "ui/Icons/iconGreygoo";
    pAsset19.category_group = GraphCategoryGroup.Tiles;
    this.add(pAsset19);
  }

  public override HistoryDataAsset add(HistoryDataAsset pAsset)
  {
    pAsset.average = !pAsset.max && !pAsset.sum;
    return base.add(pAsset);
  }

  public override void linkAssets()
  {
    base.linkAssets();
    foreach (HistoryDataAsset historyDataAsset in this.list)
    {
      if (!string.IsNullOrEmpty(historyDataAsset.statistics_asset))
      {
        StatisticsAsset statisticsAsset = AssetManager.statistics_library.get(historyDataAsset.statistics_asset);
        if (statisticsAsset.path_icon != historyDataAsset.path_icon)
          BaseAssetLibrary.logAssetError($"HistoryDataAsset: StatisticsAsset icon_path ({statisticsAsset.path_icon}) does not match HistoryDataAsset path_icon ({historyDataAsset.path_icon})", historyDataAsset.id);
        if (string.IsNullOrEmpty(historyDataAsset.localized_key))
          historyDataAsset.localized_key = statisticsAsset.getLocaleID();
        if (string.IsNullOrEmpty(historyDataAsset.localized_key_description))
          historyDataAsset.localized_key_description = statisticsAsset.localized_key_description;
      }
    }
  }

  public override void post_init()
  {
    base.post_init();
    foreach (HistoryDataAsset historyDataAsset in this.list)
    {
      Color color = Toolbox.makeColor(historyDataAsset.color_hex);
      if ((double) ((Color) ref color).grayscale < 0.2800000011920929)
      {
        string str = "#" + ColorUtility.ToHtmlStringRGB(Color.Lerp(color, Color.white, 0.33f));
        historyDataAsset.tooltip_color_hex = str;
      }
      else
        historyDataAsset.tooltip_color_hex = historyDataAsset.color_hex;
    }
  }

  public override void editorDiagnosticLocales()
  {
    foreach (HistoryDataAsset pAsset in this.list)
    {
      this.checkLocale((Asset) pAsset, pAsset.getLocaleID());
      this.checkLocale((Asset) pAsset, pAsset.getDescriptionID());
    }
    base.editorDiagnosticLocales();
  }

  public string addToGameplayReport(string pWhatFor)
  {
    string str1 = $"{string.Empty}{pWhatFor}\n";
    foreach (HistoryDataAsset historyDataAsset in this.list)
    {
      string str2 = historyDataAsset.getLocaleID().Localize();
      string str3 = historyDataAsset.getDescriptionID().Localize();
      string str4 = "\n" + str2 + "\n";
      if (!string.IsNullOrEmpty(str3))
        str4 = $"{str4}1: {str3}";
      str1 += str4;
    }
    return str1 + "\n\n";
  }
}
