// Decompiled with JetBrains decompiler
// Type: ItemModifierLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

using System.Collections.Generic;

#nullable disable
public class ItemModifierLibrary : ItemAssetLibrary<ItemModAsset>
{
  public const string WEAPON = "weapon";
  public const string ACCESSORY = "accessory";
  public const string ARMOR = "armor";
  public const string ALL = "weapon,accessory,armor";
  public Dictionary<string, List<ItemModAsset>> pools = new Dictionary<string, List<ItemModAsset>>();

  public override void init()
  {
    base.init();
    ItemModAsset itemModAsset1 = new ItemModAsset();
    itemModAsset1.id = "normal";
    itemModAsset1.mod_type = "normal";
    itemModAsset1.pool = "weapon,accessory,armor";
    itemModAsset1.rarity = 5;
    itemModAsset1.mod_can_be_given = false;
    itemModAsset1.has_locales = false;
    ItemModAsset pAsset1 = itemModAsset1;
    this.t = itemModAsset1;
    this.add(pAsset1);
    ItemModAsset itemModAsset2 = new ItemModAsset();
    itemModAsset2.id = "power1";
    itemModAsset2.mod_type = "power";
    itemModAsset2.translation_key = "mod_power";
    itemModAsset2.rarity = 1;
    itemModAsset2.pool = "weapon";
    itemModAsset2.mod_rank = 1;
    ItemModAsset pAsset2 = itemModAsset2;
    this.t = itemModAsset2;
    this.add(pAsset2);
    this.t.base_stats["damage"] = 1f;
    this.clone("power2", "power1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["damage"] = 2f;
    this.clone("power3", "power1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["damage"] = 3f;
    this.clone("power4", "power1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["damage"] = 4f;
    this.clone("power5", "power1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["damage"] = 5f;
    ItemModAsset itemModAsset3 = new ItemModAsset();
    itemModAsset3.id = "truth1";
    itemModAsset3.mod_type = "truth";
    itemModAsset3.translation_key = "mod_truth";
    itemModAsset3.rarity = 1;
    itemModAsset3.pool = "weapon";
    itemModAsset3.mod_rank = 1;
    ItemModAsset pAsset3 = itemModAsset3;
    this.t = itemModAsset3;
    this.add(pAsset3);
    this.t.base_stats["diplomacy"] = 1f;
    this.clone("truth2", "truth1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["diplomacy"] = 2f;
    this.clone("truth3", "truth1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["diplomacy"] = 3f;
    this.clone("truth4", "truth1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["diplomacy"] = 4f;
    this.clone("truth5", "truth1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["diplomacy"] = 5f;
    ItemModAsset itemModAsset4 = new ItemModAsset();
    itemModAsset4.id = "protection1";
    itemModAsset4.mod_type = "protection";
    itemModAsset4.translation_key = "mod_protection";
    itemModAsset4.rarity = 1;
    itemModAsset4.pool = "armor";
    ItemModAsset pAsset4 = itemModAsset4;
    this.t = itemModAsset4;
    this.add(pAsset4);
    this.t.base_stats["armor"] = 3f;
    this.clone("protection2", "protection1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["armor"] = 4f;
    this.clone("protection3", "protection1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["armor"] = 5f;
    this.clone("protection4", "protection1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["armor"] = 6f;
    this.clone("protection5", "protection1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["armor"] = 7f;
    ItemModAsset itemModAsset5 = new ItemModAsset();
    itemModAsset5.id = "speed1";
    itemModAsset5.mod_type = "speed";
    itemModAsset5.translation_key = "mod_speed";
    itemModAsset5.rarity = 3;
    itemModAsset5.pool = "weapon,accessory,armor";
    ItemModAsset pAsset5 = itemModAsset5;
    this.t = itemModAsset5;
    this.add(pAsset5);
    this.t.base_stats["speed"] = 2f;
    this.clone("speed2", "speed1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["speed"] = 3f;
    this.clone("speed3", "speed1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["speed"] = 4f;
    this.clone("speed4", "speed1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["speed"] = 5f;
    this.clone("speed5", "speed1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["speed"] = 6f;
    ItemModAsset itemModAsset6 = new ItemModAsset();
    itemModAsset6.id = "balance1";
    itemModAsset6.mod_type = "balance";
    itemModAsset6.translation_key = "mod_balance";
    itemModAsset6.rarity = 3;
    itemModAsset6.pool = "weapon,accessory,armor";
    ItemModAsset pAsset6 = itemModAsset6;
    this.t = itemModAsset6;
    this.add(pAsset6);
    this.t.base_stats["critical_chance"] = 0.05f;
    this.clone("balance2", "balance1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["critical_chance"] = 0.15f;
    this.clone("balance3", "balance1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["critical_chance"] = 0.2f;
    this.clone("balance4", "balance1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["critical_chance"] = 0.25f;
    this.clone("balance5", "balance1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["critical_chance"] = 0.3f;
    ItemModAsset itemModAsset7 = new ItemModAsset();
    itemModAsset7.id = "health1";
    itemModAsset7.mod_type = "health";
    itemModAsset7.translation_key = "mod_health";
    itemModAsset7.rarity = 1;
    itemModAsset7.pool = "armoraccessory";
    ItemModAsset pAsset7 = itemModAsset7;
    this.t = itemModAsset7;
    this.add(pAsset7);
    this.t.base_stats["health"] = 50f;
    this.clone("health2", "health1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["health"] = 100f;
    this.clone("health3", "health1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["health"] = 150f;
    this.clone("health4", "health1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["health"] = 200f;
    this.clone("health5", "health1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["health"] = 250f;
    ItemModAsset itemModAsset8 = new ItemModAsset();
    itemModAsset8.id = "finesse1";
    itemModAsset8.mod_type = "finesse";
    itemModAsset8.translation_key = "mod_finesse";
    itemModAsset8.rarity = 1;
    itemModAsset8.pool = "weaponaccessory";
    ItemModAsset pAsset8 = itemModAsset8;
    this.t = itemModAsset8;
    this.add(pAsset8);
    this.t.base_stats["attack_speed"] = 1f;
    this.clone("finesse2", "finesse1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["attack_speed"] = 1f;
    this.t.base_stats["speed"] = 1f;
    this.clone("finesse3", "finesse1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["attack_speed"] = 2f;
    this.t.base_stats["speed"] = 1f;
    this.clone("finesse4", "finesse1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["attack_speed"] = 2f;
    this.t.base_stats["speed"] = 2f;
    this.clone("finesse5", "finesse1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["attack_speed"] = 3f;
    this.t.base_stats["speed"] = 3f;
    ItemModAsset itemModAsset9 = new ItemModAsset();
    itemModAsset9.id = "mastery1";
    itemModAsset9.mod_type = "mastery";
    itemModAsset9.translation_key = "mod_mastery";
    itemModAsset9.rarity = 1;
    itemModAsset9.pool = "accessory";
    itemModAsset9.mod_rank = 1;
    ItemModAsset pAsset9 = itemModAsset9;
    this.t = itemModAsset9;
    this.add(pAsset9);
    this.t.base_stats["warfare"] = 1f;
    this.clone("mastery2", "mastery1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["warfare"] = 2f;
    this.clone("mastery3", "mastery1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["warfare"] = 3f;
    this.clone("mastery4", "mastery1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["warfare"] = 4f;
    this.clone("mastery5", "mastery1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["warfare"] = 5f;
    ItemModAsset itemModAsset10 = new ItemModAsset();
    itemModAsset10.id = "knowledge1";
    itemModAsset10.mod_type = "knowledge";
    itemModAsset10.translation_key = "mod_knowledge";
    itemModAsset10.rarity = 1;
    itemModAsset10.pool = "accessory";
    itemModAsset10.mod_rank = 1;
    ItemModAsset pAsset10 = itemModAsset10;
    this.t = itemModAsset10;
    this.add(pAsset10);
    this.t.base_stats["intelligence"] = 1f;
    this.clone("knowledge2", "knowledge1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["intelligence"] = 2f;
    this.clone("knowledge3", "knowledge1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["intelligence"] = 3f;
    this.clone("knowledge4", "knowledge1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["intelligence"] = 4f;
    this.clone("knowledge5", "knowledge1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["intelligence"] = 7f;
    ItemModAsset itemModAsset11 = new ItemModAsset();
    itemModAsset11.id = "sharpness1";
    itemModAsset11.mod_type = "sharpness";
    itemModAsset11.translation_key = "mod_sharpness";
    itemModAsset11.rarity = 1;
    itemModAsset11.pool = "accessory";
    itemModAsset11.mod_rank = 1;
    ItemModAsset pAsset11 = itemModAsset11;
    this.t = itemModAsset11;
    this.add(pAsset11);
    this.t.base_stats["damage"] = 1f;
    this.t.base_stats["multiplier_crit"] = 0.05f;
    this.clone("sharpness2", "sharpness1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 2;
    this.t.base_stats["damage"] = 2f;
    this.t.base_stats["multiplier_crit"] = 0.06f;
    this.clone("sharpness3", "sharpness1");
    this.t.quality = Rarity.R1_Rare;
    this.t.mod_rank = 3;
    this.t.base_stats["damage"] = 3f;
    this.t.base_stats["multiplier_crit"] = 0.08f;
    this.clone("sharpness4", "sharpness1");
    this.t.quality = Rarity.R2_Epic;
    this.t.mod_rank = 4;
    this.t.base_stats["damage"] = 5f;
    this.t.base_stats["multiplier_crit"] = 0.1f;
    this.clone("sharpness5", "sharpness1");
    this.t.quality = Rarity.R3_Legendary;
    this.t.mod_rank = 5;
    this.t.base_stats["damage"] = 10f;
    this.t.base_stats["multiplier_crit"] = 0.1f;
    ItemModAsset itemModAsset12 = new ItemModAsset();
    itemModAsset12.id = "flame";
    itemModAsset12.mod_type = "flame";
    itemModAsset12.translation_key = "mod_flame";
    itemModAsset12.rarity = 0;
    itemModAsset12.pool = "weapon";
    itemModAsset12.mod_rank = 1;
    ItemModAsset pAsset12 = itemModAsset12;
    this.t = itemModAsset12;
    this.add(pAsset12);
    this.t.base_stats.addTag("immunity_fire");
    this.t.action_attack_target = new AttackAction(ActionLibrary.addBurningEffectOnTarget);
    this.t.action_special_effect = new WorldAction(ActionLibrary.flamingWeapon);
    this.t.special_effect_interval = 0.1f;
    ItemModAsset itemModAsset13 = new ItemModAsset();
    itemModAsset13.id = "ice";
    itemModAsset13.mod_type = "ice";
    itemModAsset13.translation_key = "mod_ice";
    itemModAsset13.rarity = 0;
    itemModAsset13.pool = "weapon";
    itemModAsset13.mod_rank = 1;
    ItemModAsset pAsset13 = itemModAsset13;
    this.t = itemModAsset13;
    this.add(pAsset13);
    this.t.base_stats.addTag("immunity_cold");
    this.t.action_attack_target = new AttackAction(ActionLibrary.addFrozenEffectOnTarget20);
    ItemModAsset itemModAsset14 = new ItemModAsset();
    itemModAsset14.id = "stun";
    itemModAsset14.mod_type = "stun";
    itemModAsset14.translation_key = "mod_stun";
    itemModAsset14.rarity = 0;
    itemModAsset14.pool = "weapon";
    itemModAsset14.mod_rank = 1;
    ItemModAsset pAsset14 = itemModAsset14;
    this.t = itemModAsset14;
    this.add(pAsset14);
    this.t.action_attack_target = new AttackAction(ActionLibrary.addStunnedEffectOnTarget20);
    ItemModAsset itemModAsset15 = new ItemModAsset();
    itemModAsset15.id = "slowness";
    itemModAsset15.mod_type = "slowness";
    itemModAsset15.translation_key = "mod_slowness";
    itemModAsset15.rarity = 0;
    itemModAsset15.pool = "weapon";
    itemModAsset15.mod_rank = 1;
    ItemModAsset pAsset15 = itemModAsset15;
    this.t = itemModAsset15;
    this.add(pAsset15);
    this.t.action_attack_target = new AttackAction(ActionLibrary.addSlowEffectOnTarget20);
    ItemModAsset itemModAsset16 = new ItemModAsset();
    itemModAsset16.id = "poison";
    itemModAsset16.mod_type = "poison";
    itemModAsset16.translation_key = "mod_poison";
    itemModAsset16.rarity = 0;
    itemModAsset16.pool = "weapon";
    itemModAsset16.mod_rank = 1;
    ItemModAsset pAsset16 = itemModAsset16;
    this.t = itemModAsset16;
    this.add(pAsset16);
    this.t.action_attack_target = new AttackAction(ActionLibrary.addPoisonedEffectOnTarget);
    ItemModAsset itemModAsset17 = new ItemModAsset();
    itemModAsset17.id = "eternal";
    itemModAsset17.mod_type = "eternal";
    itemModAsset17.translation_key = "mod_eternal";
    itemModAsset17.rarity = 0;
    itemModAsset17.pool = "weapon,accessory,armor";
    itemModAsset17.mod_rank = 5;
    ItemModAsset pAsset17 = itemModAsset17;
    this.t = itemModAsset17;
    this.add(pAsset17);
    ItemModAsset itemModAsset18 = new ItemModAsset();
    itemModAsset18.id = "cursed";
    itemModAsset18.mod_type = "cursed";
    itemModAsset18.translation_key = "mod_cursed";
    itemModAsset18.rarity = 0;
    itemModAsset18.pool = "weapon,accessory,armor";
    itemModAsset18.mod_rank = 5;
    ItemModAsset pAsset18 = itemModAsset18;
    this.t = itemModAsset18;
    this.add(pAsset18);
    ItemModAsset itemModAsset19 = new ItemModAsset();
    itemModAsset19.id = "divine_rune";
    itemModAsset19.mod_type = "divine_rune";
    itemModAsset19.translation_key = "divine_rune";
    itemModAsset19.rarity = 0;
    itemModAsset19.pool = "weapon,accessory,armor";
    itemModAsset19.mod_rank = 5;
    ItemModAsset pAsset19 = itemModAsset19;
    this.t = itemModAsset19;
    this.add(pAsset19);
  }

  public override void linkAssets()
  {
    base.linkAssets();
    this.pools.Add("weapon", new List<ItemModAsset>());
    this.pools.Add("armor", new List<ItemModAsset>());
    this.pools.Add("accessory", new List<ItemModAsset>());
    foreach (ItemModAsset itemModAsset in this.list)
    {
      for (int index = 0; index < itemModAsset.rarity; ++index)
      {
        if (itemModAsset.pool.Contains("weapon"))
          this.pools["weapon"].Add(itemModAsset);
        if (itemModAsset.pool.Contains("armor"))
          this.pools["armor"].Add(itemModAsset);
        if (itemModAsset.pool.Contains("accessory"))
          this.pools["accessory"].Add(itemModAsset);
      }
    }
  }
}
