// Decompiled with JetBrains decompiler
// Type: NameSetsLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

using System;

#nullable disable
[Serializable]
public class NameSetsLibrary : AssetLibrary<NameSetAsset>
{
  public override void init()
  {
    base.init();
    this.addHumanLike();
    this.addFantasyRaces();
    this.addAnimalRaces();
    this.addMobRaces();
  }

  private void addMobRaces()
  {
    NameSetAsset pAsset1 = new NameSetAsset();
    pAsset1.id = "default_set";
    pAsset1.city = "default_name";
    pAsset1.clan = "default_name";
    pAsset1.culture = "default_name";
    pAsset1.family = "default_name";
    pAsset1.kingdom = "default_name";
    pAsset1.language = "default_name";
    pAsset1.unit = "default_name";
    pAsset1.religion = "default_name";
    this.add(pAsset1);
    NameSetAsset pAsset2 = new NameSetAsset();
    pAsset2.id = "cold_one_set";
    pAsset2.city = "cold_one_name";
    pAsset2.clan = "cold_one_name";
    pAsset2.culture = "cold_one_name";
    pAsset2.family = "cold_one_name";
    pAsset2.kingdom = "cold_one_name";
    pAsset2.language = "cold_one_name";
    pAsset2.unit = "cold_one_name";
    pAsset2.religion = "cold_one_name";
    this.add(pAsset2);
    NameSetAsset pAsset3 = new NameSetAsset();
    pAsset3.id = "necromancer_set";
    pAsset3.city = "necromancer_name";
    pAsset3.clan = "necromancer_name";
    pAsset3.culture = "necromancer_name";
    pAsset3.family = "necromancer_name";
    pAsset3.kingdom = "necromancer_name";
    pAsset3.language = "necromancer_name";
    pAsset3.unit = "necromancer_name";
    pAsset3.religion = "necromancer_name";
    this.add(pAsset3);
    NameSetAsset pAsset4 = new NameSetAsset();
    pAsset4.id = "druid_set";
    pAsset4.city = "flower_name";
    pAsset4.clan = "flower_name";
    pAsset4.culture = "flower_name";
    pAsset4.family = "flower_name";
    pAsset4.kingdom = "flower_name";
    pAsset4.language = "flower_name";
    pAsset4.unit = "flower_name";
    pAsset4.religion = "flower_name";
    this.add(pAsset4);
    NameSetAsset pAsset5 = new NameSetAsset();
    pAsset5.id = "plague_doctor_set";
    pAsset5.city = "white_mage_name";
    pAsset5.clan = "white_mage_name";
    pAsset5.culture = "white_mage_name";
    pAsset5.family = "white_mage_name";
    pAsset5.kingdom = "white_mage_name";
    pAsset5.language = "white_mage_name";
    pAsset5.unit = "white_mage_name";
    pAsset5.religion = "white_mage_name";
    this.add(pAsset5);
    NameSetAsset pAsset6 = new NameSetAsset();
    pAsset6.id = "white_mage_set";
    pAsset6.city = "white_mage_name";
    pAsset6.clan = "white_mage_name";
    pAsset6.culture = "white_mage_name";
    pAsset6.family = "white_mage_name";
    pAsset6.kingdom = "white_mage_name";
    pAsset6.language = "white_mage_name";
    pAsset6.unit = "white_mage_name";
    pAsset6.religion = "white_mage_name";
    this.add(pAsset6);
    NameSetAsset pAsset7 = new NameSetAsset();
    pAsset7.id = "evil_mage_set";
    pAsset7.city = "evil_mage_name";
    pAsset7.clan = "evil_mage_name";
    pAsset7.culture = "evil_mage_name";
    pAsset7.family = "evil_mage_name";
    pAsset7.kingdom = "evil_mage_name";
    pAsset7.language = "evil_mage_name";
    pAsset7.unit = "evil_mage_name";
    pAsset7.religion = "evil_mage_name";
    this.add(pAsset7);
    NameSetAsset pAsset8 = new NameSetAsset();
    pAsset8.id = "skeleton_set";
    pAsset8.city = "skeleton_name";
    pAsset8.clan = "skeleton_name";
    pAsset8.culture = "skeleton_name";
    pAsset8.family = "skeleton_name";
    pAsset8.kingdom = "skeleton_name";
    pAsset8.language = "skeleton_name";
    pAsset8.unit = "skeleton_name";
    pAsset8.religion = "skeleton_name";
    this.add(pAsset8);
    NameSetAsset pAsset9 = new NameSetAsset();
    pAsset9.id = "jumpy_skull_set";
    pAsset9.city = "jumpy_skull_name";
    pAsset9.clan = "jumpy_skull_name";
    pAsset9.culture = "jumpy_skull_name";
    pAsset9.family = "jumpy_skull_name";
    pAsset9.kingdom = "jumpy_skull_name";
    pAsset9.language = "jumpy_skull_name";
    pAsset9.unit = "jumpy_skull_name";
    pAsset9.religion = "jumpy_skull_name";
    this.add(pAsset9);
    NameSetAsset pAsset10 = new NameSetAsset();
    pAsset10.id = "fire_skull_set";
    pAsset10.city = "fire_skull_name";
    pAsset10.clan = "fire_skull_name";
    pAsset10.culture = "fire_skull_name";
    pAsset10.family = "fire_skull_name";
    pAsset10.kingdom = "fire_skull_name";
    pAsset10.language = "fire_skull_name";
    pAsset10.unit = "fire_skull_name";
    pAsset10.religion = "fire_skull_name";
    this.add(pAsset10);
    NameSetAsset pAsset11 = new NameSetAsset();
    pAsset11.id = "demon_set";
    pAsset11.city = "demon_name";
    pAsset11.clan = "demon_name";
    pAsset11.culture = "demon_name";
    pAsset11.family = "demon_name";
    pAsset11.kingdom = "demon_name";
    pAsset11.language = "demon_name";
    pAsset11.unit = "demon_name";
    pAsset11.religion = "demon_name";
    this.add(pAsset11);
    NameSetAsset pAsset12 = new NameSetAsset();
    pAsset12.id = "angle_set";
    pAsset12.city = "angle_name";
    pAsset12.clan = "angle_name";
    pAsset12.culture = "angle_name";
    pAsset12.family = "angle_name";
    pAsset12.kingdom = "angle_name";
    pAsset12.language = "angle_name";
    pAsset12.unit = "angle_name";
    pAsset12.religion = "angle_name";
    this.add(pAsset12);
    NameSetAsset pAsset13 = new NameSetAsset();
    pAsset13.id = "fairy_set";
    pAsset13.city = "fairy_name";
    pAsset13.clan = "fairy_name";
    pAsset13.culture = "fairy_name";
    pAsset13.family = "fairy_name";
    pAsset13.kingdom = "fairy_name";
    pAsset13.language = "fairy_name";
    pAsset13.unit = "fairy_name";
    pAsset13.religion = "fairy_name";
    this.add(pAsset13);
    NameSetAsset pAsset14 = new NameSetAsset();
    pAsset14.id = "bandit_set";
    pAsset14.city = "bandit_name";
    pAsset14.clan = "bandit_name";
    pAsset14.culture = "bandit_name";
    pAsset14.family = "bandit_name";
    pAsset14.kingdom = "bandit_name";
    pAsset14.language = "bandit_name";
    pAsset14.unit = "bandit_name";
    pAsset14.religion = "bandit_name";
    this.add(pAsset14);
    NameSetAsset pAsset15 = new NameSetAsset();
    pAsset15.id = "snowman_set";
    pAsset15.city = "snowman_name";
    pAsset15.clan = "snowman_name";
    pAsset15.culture = "snowman_name";
    pAsset15.family = "snowman_name";
    pAsset15.kingdom = "snowman_name";
    pAsset15.language = "snowman_name";
    pAsset15.unit = "snowman_name";
    pAsset15.religion = "snowman_name";
    this.add(pAsset15);
    NameSetAsset pAsset16 = new NameSetAsset();
    pAsset16.id = "alien_set";
    pAsset16.city = "alien_name";
    pAsset16.clan = "alien_name";
    pAsset16.culture = "alien_name";
    pAsset16.family = "alien_name";
    pAsset16.kingdom = "alien_name";
    pAsset16.language = "alien_name";
    pAsset16.unit = "alien_name";
    pAsset16.religion = "alien_name";
    this.add(pAsset16);
    NameSetAsset pAsset17 = new NameSetAsset();
    pAsset17.id = "fire_elemental_set";
    pAsset17.city = "fire_elemental_name";
    pAsset17.clan = "fire_elemental_name";
    pAsset17.culture = "fire_elemental_name";
    pAsset17.family = "fire_elemental_name";
    pAsset17.kingdom = "fire_elemental_name";
    pAsset17.language = "fire_elemental_name";
    pAsset17.unit = "fire_elemental_name";
    pAsset17.religion = "fire_elemental_name";
    this.add(pAsset17);
    NameSetAsset pAsset18 = new NameSetAsset();
    pAsset18.id = "pumpkin_set";
    pAsset18.city = "lil_pumpkin_name";
    pAsset18.clan = "lil_pumpkin_name";
    pAsset18.culture = "lil_pumpkin_name";
    pAsset18.family = "lil_pumpkin_name";
    pAsset18.kingdom = "lil_pumpkin_name";
    pAsset18.language = "lil_pumpkin_name";
    pAsset18.unit = "lil_pumpkin_name";
    pAsset18.religion = "lil_pumpkin_name";
    this.add(pAsset18);
    NameSetAsset pAsset19 = new NameSetAsset();
    pAsset19.id = "assimilator_set";
    pAsset19.city = "assimilator_name";
    pAsset19.clan = "assimilator_name";
    pAsset19.culture = "assimilator_name";
    pAsset19.family = "assimilator_name";
    pAsset19.kingdom = "assimilator_name";
    pAsset19.language = "assimilator_name";
    pAsset19.unit = "assimilator_name";
    pAsset19.religion = "assimilator_name";
    this.add(pAsset19);
    NameSetAsset pAsset20 = new NameSetAsset();
    pAsset20.id = "bioblob_set";
    pAsset20.city = "bioblob_name";
    pAsset20.clan = "bioblob_name";
    pAsset20.culture = "bioblob_name";
    pAsset20.family = "bioblob_name";
    pAsset20.kingdom = "bioblob_name";
    pAsset20.language = "bioblob_name";
    pAsset20.unit = "bioblob_name";
    pAsset20.religion = "bioblob_name";
    this.add(pAsset20);
    NameSetAsset pAsset21 = new NameSetAsset();
    pAsset21.id = "greg_set";
    pAsset21.city = "greg_name";
    pAsset21.clan = "greg_name";
    pAsset21.culture = "greg_name";
    pAsset21.family = "greg_name";
    pAsset21.kingdom = "greg_name";
    pAsset21.language = "greg_name";
    pAsset21.unit = "greg_name";
    pAsset21.religion = "greg_name";
    this.add(pAsset21);
    NameSetAsset pAsset22 = new NameSetAsset();
    pAsset22.id = "living_plant_set";
    pAsset22.city = "living_plant_name";
    pAsset22.clan = "living_plant_name";
    pAsset22.culture = "living_plant_name";
    pAsset22.family = "living_plant_name";
    pAsset22.kingdom = "living_plant_name";
    pAsset22.language = "living_plant_name";
    pAsset22.unit = "living_plant_name";
    pAsset22.religion = "living_plant_name";
    this.add(pAsset22);
    NameSetAsset pAsset23 = new NameSetAsset();
    pAsset23.id = "living_house_set";
    pAsset23.city = "living_house_name";
    pAsset23.clan = "living_house_name";
    pAsset23.culture = "living_house_name";
    pAsset23.family = "living_house_name";
    pAsset23.kingdom = "living_house_name";
    pAsset23.language = "living_house_name";
    pAsset23.unit = "living_house_name";
    pAsset23.religion = "living_house_name";
    this.add(pAsset23);
  }

  private void addAnimalRaces()
  {
    NameSetAsset pAsset1 = new NameSetAsset();
    pAsset1.id = "cat_set";
    pAsset1.city = "cat_name";
    pAsset1.clan = "cat_name";
    pAsset1.culture = "cat_name";
    pAsset1.family = "cat_name";
    pAsset1.kingdom = "cat_name";
    pAsset1.language = "cat_name";
    pAsset1.unit = "cat_name";
    pAsset1.religion = "cat_name";
    this.add(pAsset1);
    NameSetAsset pAsset2 = new NameSetAsset();
    pAsset2.id = "wolf_set";
    pAsset2.city = "wolf_name";
    pAsset2.clan = "wolf_name";
    pAsset2.culture = "wolf_name";
    pAsset2.family = "wolf_name";
    pAsset2.kingdom = "wolf_name";
    pAsset2.language = "wolf_name";
    pAsset2.unit = "wolf_name";
    pAsset2.religion = "wolf_name";
    this.add(pAsset2);
    NameSetAsset pAsset3 = new NameSetAsset();
    pAsset3.id = "fox_set";
    pAsset3.city = "fox_name";
    pAsset3.clan = "fox_name";
    pAsset3.culture = "fox_name";
    pAsset3.family = "fox_name";
    pAsset3.kingdom = "fox_name";
    pAsset3.language = "fox_name";
    pAsset3.unit = "fox_name";
    pAsset3.religion = "fox_name";
    this.add(pAsset3);
    NameSetAsset pAsset4 = new NameSetAsset();
    pAsset4.id = "chicken_set";
    pAsset4.city = "chicken_name";
    pAsset4.clan = "chicken_name";
    pAsset4.culture = "chicken_name";
    pAsset4.family = "chicken_name";
    pAsset4.kingdom = "chicken_name";
    pAsset4.language = "chicken_name";
    pAsset4.unit = "chicken_name";
    pAsset4.religion = "chicken_name";
    this.add(pAsset4);
    NameSetAsset pAsset5 = new NameSetAsset();
    pAsset5.id = "rabbit_set";
    pAsset5.city = "rabbit_name";
    pAsset5.clan = "rabbit_name";
    pAsset5.culture = "rabbit_name";
    pAsset5.family = "rabbit_name";
    pAsset5.kingdom = "rabbit_name";
    pAsset5.language = "rabbit_name";
    pAsset5.unit = "rabbit_name";
    pAsset5.religion = "rabbit_name";
    this.add(pAsset5);
    NameSetAsset pAsset6 = new NameSetAsset();
    pAsset6.id = "monkey_set";
    pAsset6.city = "monkey_name";
    pAsset6.clan = "monkey_name";
    pAsset6.culture = "monkey_name";
    pAsset6.family = "monkey_name";
    pAsset6.kingdom = "monkey_name";
    pAsset6.language = "monkey_name";
    pAsset6.unit = "monkey_name";
    pAsset6.religion = "monkey_name";
    this.add(pAsset6);
    NameSetAsset pAsset7 = new NameSetAsset();
    pAsset7.id = "sheep_set";
    pAsset7.city = "sheep_name";
    pAsset7.clan = "sheep_name";
    pAsset7.culture = "sheep_name";
    pAsset7.family = "sheep_name";
    pAsset7.kingdom = "sheep_name";
    pAsset7.language = "sheep_name";
    pAsset7.unit = "sheep_name";
    pAsset7.religion = "sheep_name";
    this.add(pAsset7);
    NameSetAsset pAsset8 = new NameSetAsset();
    pAsset8.id = "cow_set";
    pAsset8.city = "cow_name";
    pAsset8.clan = "cow_name";
    pAsset8.culture = "cow_name";
    pAsset8.family = "cow_name";
    pAsset8.kingdom = "cow_name";
    pAsset8.language = "cow_name";
    pAsset8.unit = "cow_name";
    pAsset8.religion = "cow_name";
    this.add(pAsset8);
    NameSetAsset pAsset9 = new NameSetAsset();
    pAsset9.id = "armadillo_set";
    pAsset9.city = "armadillo_name";
    pAsset9.clan = "armadillo_name";
    pAsset9.culture = "armadillo_name";
    pAsset9.family = "armadillo_name";
    pAsset9.kingdom = "armadillo_name";
    pAsset9.language = "armadillo_name";
    pAsset9.unit = "armadillo_name";
    pAsset9.religion = "armadillo_name";
    this.add(pAsset9);
    NameSetAsset pAsset10 = new NameSetAsset();
    pAsset10.id = "bear_set";
    pAsset10.city = "bear_name";
    pAsset10.clan = "bear_name";
    pAsset10.culture = "bear_name";
    pAsset10.family = "bear_name";
    pAsset10.kingdom = "bear_name";
    pAsset10.language = "bear_name";
    pAsset10.unit = "bear_name";
    pAsset10.religion = "bear_name";
    this.add(pAsset10);
    NameSetAsset pAsset11 = new NameSetAsset();
    pAsset11.id = "rhino_set";
    pAsset11.city = "rhino_name";
    pAsset11.clan = "rhino_name";
    pAsset11.culture = "rhino_name";
    pAsset11.family = "rhino_name";
    pAsset11.kingdom = "rhino_name";
    pAsset11.language = "rhino_name";
    pAsset11.unit = "rhino_name";
    pAsset11.religion = "rhino_name";
    this.add(pAsset11);
    NameSetAsset pAsset12 = new NameSetAsset();
    pAsset12.id = "buffalo_set";
    pAsset12.city = "buffalo_name";
    pAsset12.clan = "buffalo_name";
    pAsset12.culture = "buffalo_name";
    pAsset12.family = "buffalo_name";
    pAsset12.kingdom = "buffalo_name";
    pAsset12.language = "buffalo_name";
    pAsset12.unit = "buffalo_name";
    pAsset12.religion = "buffalo_name";
    this.add(pAsset12);
    NameSetAsset pAsset13 = new NameSetAsset();
    pAsset13.id = "rat_set";
    pAsset13.city = "rat_name";
    pAsset13.clan = "rat_name";
    pAsset13.culture = "rat_name";
    pAsset13.family = "rat_name";
    pAsset13.kingdom = "rat_name";
    pAsset13.language = "rat_name";
    pAsset13.unit = "rat_name";
    pAsset13.religion = "rat_name";
    this.add(pAsset13);
    NameSetAsset pAsset14 = new NameSetAsset();
    pAsset14.id = "capybara_set";
    pAsset14.city = "capybara_name";
    pAsset14.clan = "capybara_name";
    pAsset14.culture = "capybara_name";
    pAsset14.family = "capybara_name";
    pAsset14.kingdom = "capybara_name";
    pAsset14.language = "capybara_name";
    pAsset14.unit = "capybara_name";
    pAsset14.religion = "capybara_name";
    this.add(pAsset14);
    NameSetAsset pAsset15 = new NameSetAsset();
    pAsset15.id = "goat_set";
    pAsset15.city = "goat_name";
    pAsset15.clan = "goat_name";
    pAsset15.culture = "goat_name";
    pAsset15.family = "goat_name";
    pAsset15.kingdom = "goat_name";
    pAsset15.language = "goat_name";
    pAsset15.unit = "goat_name";
    pAsset15.religion = "goat_name";
    this.add(pAsset15);
    NameSetAsset pAsset16 = new NameSetAsset();
    pAsset16.id = "raccoon_set";
    pAsset16.city = "raccoon_name";
    pAsset16.clan = "raccoon_name";
    pAsset16.culture = "raccoon_name";
    pAsset16.family = "raccoon_name";
    pAsset16.kingdom = "raccoon_name";
    pAsset16.language = "raccoon_name";
    pAsset16.unit = "raccoon_name";
    pAsset16.religion = "raccoon_name";
    this.add(pAsset16);
    NameSetAsset pAsset17 = new NameSetAsset();
    pAsset17.id = "unicorn_set";
    pAsset17.city = "white_mage_name";
    pAsset17.clan = "white_mage_name";
    pAsset17.culture = "white_mage_name";
    pAsset17.family = "white_mage_name";
    pAsset17.kingdom = "white_mage_name";
    pAsset17.language = "white_mage_name";
    pAsset17.unit = "white_mage_name";
    pAsset17.religion = "white_mage_name";
    this.add(pAsset17);
    NameSetAsset pAsset18 = new NameSetAsset();
    pAsset18.id = "seal_set";
    pAsset18.city = "default_name";
    pAsset18.clan = "default_name";
    pAsset18.culture = "default_name";
    pAsset18.family = "default_name";
    pAsset18.kingdom = "default_name";
    pAsset18.language = "default_name";
    pAsset18.unit = "default_name";
    pAsset18.religion = "default_name";
    this.add(pAsset18);
    NameSetAsset pAsset19 = new NameSetAsset();
    pAsset19.id = "ostrich_set";
    pAsset19.city = "default_name";
    pAsset19.clan = "default_name";
    pAsset19.culture = "default_name";
    pAsset19.family = "default_name";
    pAsset19.kingdom = "default_name";
    pAsset19.language = "default_name";
    pAsset19.unit = "default_name";
    pAsset19.religion = "default_name";
    this.add(pAsset19);
    NameSetAsset pAsset20 = new NameSetAsset();
    pAsset20.id = "scorpion_set";
    pAsset20.city = "scorpion_name";
    pAsset20.clan = "scorpion_name";
    pAsset20.culture = "scorpion_name";
    pAsset20.family = "scorpion_name";
    pAsset20.kingdom = "scorpion_name";
    pAsset20.language = "scorpion_name";
    pAsset20.unit = "scorpion_name";
    pAsset20.religion = "scorpion_name";
    this.add(pAsset20);
    NameSetAsset pAsset21 = new NameSetAsset();
    pAsset21.id = "crab_set";
    pAsset21.city = "crab_name";
    pAsset21.clan = "crab_name";
    pAsset21.culture = "crab_name";
    pAsset21.family = "crab_name";
    pAsset21.kingdom = "crab_name";
    pAsset21.language = "crab_name";
    pAsset21.unit = "crab_name";
    pAsset21.religion = "crab_name";
    this.add(pAsset21);
    NameSetAsset pAsset22 = new NameSetAsset();
    pAsset22.id = "penguin_set";
    pAsset22.city = "penguin_name";
    pAsset22.clan = "penguin_name";
    pAsset22.culture = "penguin_name";
    pAsset22.family = "penguin_name";
    pAsset22.kingdom = "penguin_name";
    pAsset22.language = "penguin_name";
    pAsset22.unit = "penguin_name";
    pAsset22.religion = "penguin_name";
    this.add(pAsset22);
    NameSetAsset pAsset23 = new NameSetAsset();
    pAsset23.id = "turtle_set";
    pAsset23.city = "turtle_name";
    pAsset23.clan = "turtle_name";
    pAsset23.culture = "turtle_name";
    pAsset23.family = "turtle_name";
    pAsset23.kingdom = "turtle_name";
    pAsset23.language = "turtle_name";
    pAsset23.unit = "turtle_name";
    pAsset23.religion = "turtle_name";
    this.add(pAsset23);
    NameSetAsset pAsset24 = new NameSetAsset();
    pAsset24.id = "crocodile_set";
    pAsset24.city = "crocodile_name";
    pAsset24.clan = "crocodile_name";
    pAsset24.culture = "crocodile_name";
    pAsset24.family = "crocodile_name";
    pAsset24.kingdom = "crocodile_name";
    pAsset24.language = "crocodile_name";
    pAsset24.unit = "crocodile_name";
    pAsset24.religion = "crocodile_name";
    this.add(pAsset24);
    NameSetAsset pAsset25 = new NameSetAsset();
    pAsset25.id = "frog_set";
    pAsset25.city = "frog_name";
    pAsset25.clan = "frog_name";
    pAsset25.culture = "frog_name";
    pAsset25.family = "frog_name";
    pAsset25.kingdom = "frog_name";
    pAsset25.language = "frog_name";
    pAsset25.unit = "frog_name";
    pAsset25.religion = "frog_name";
    this.add(pAsset25);
    NameSetAsset pAsset26 = new NameSetAsset();
    pAsset26.id = "piranha_set";
    pAsset26.city = "piranha_name";
    pAsset26.clan = "piranha_name";
    pAsset26.culture = "piranha_name";
    pAsset26.family = "piranha_name";
    pAsset26.kingdom = "piranha_name";
    pAsset26.language = "piranha_name";
    pAsset26.unit = "piranha_name";
    pAsset26.religion = "piranha_name";
    this.add(pAsset26);
    NameSetAsset pAsset27 = new NameSetAsset();
    pAsset27.id = "flower_set";
    pAsset27.city = "flower_name";
    pAsset27.clan = "flower_name";
    pAsset27.culture = "flower_name";
    pAsset27.family = "flower_name";
    pAsset27.kingdom = "flower_name";
    pAsset27.language = "flower_name";
    pAsset27.unit = "flower_name";
    pAsset27.religion = "flower_name";
    this.add(pAsset27);
    NameSetAsset pAsset28 = new NameSetAsset();
    pAsset28.id = "garlic_man_set";
    pAsset28.city = "garlic_name";
    pAsset28.clan = "garlic_name";
    pAsset28.culture = "garlic_name";
    pAsset28.family = "garlic_name";
    pAsset28.kingdom = "garlic_name";
    pAsset28.language = "garlic_name";
    pAsset28.unit = "garlic_name";
    pAsset28.religion = "garlic_name";
    this.add(pAsset28);
    NameSetAsset pAsset29 = new NameSetAsset();
    pAsset29.id = "lemon_man_set";
    pAsset29.city = "lemon_name";
    pAsset29.clan = "lemon_name";
    pAsset29.culture = "lemon_name";
    pAsset29.family = "lemon_name";
    pAsset29.kingdom = "lemon_name";
    pAsset29.language = "lemon_name";
    pAsset29.unit = "lemon_name";
    pAsset29.religion = "lemon_name";
    this.add(pAsset29);
    NameSetAsset pAsset30 = new NameSetAsset();
    pAsset30.id = "acid_blob_set";
    pAsset30.city = "acid_blob_name";
    pAsset30.clan = "acid_blob_name";
    pAsset30.culture = "acid_blob_name";
    pAsset30.family = "acid_blob_name";
    pAsset30.kingdom = "acid_blob_name";
    pAsset30.language = "acid_blob_name";
    pAsset30.unit = "acid_blob_name";
    pAsset30.religion = "acid_blob_name";
    this.add(pAsset30);
    NameSetAsset pAsset31 = new NameSetAsset();
    pAsset31.id = "crystal_golem_set";
    pAsset31.city = "crystal_sword_name";
    pAsset31.clan = "crystal_sword_name";
    pAsset31.culture = "crystal_sword_name";
    pAsset31.family = "crystal_sword_name";
    pAsset31.kingdom = "crystal_sword_name";
    pAsset31.language = "crystal_sword_name";
    pAsset31.unit = "crystal_sword_name";
    pAsset31.religion = "crystal_sword_name";
    this.add(pAsset31);
    NameSetAsset pAsset32 = new NameSetAsset();
    pAsset32.id = "crystal_sword_set";
    pAsset32.city = "crystal_sword_name";
    pAsset32.clan = "crystal_sword_name";
    pAsset32.culture = "crystal_sword_name";
    pAsset32.family = "crystal_sword_name";
    pAsset32.kingdom = "crystal_sword_name";
    pAsset32.language = "crystal_sword_name";
    pAsset32.unit = "crystal_sword_name";
    pAsset32.religion = "crystal_sword_name";
    this.add(pAsset32);
    NameSetAsset pAsset33 = new NameSetAsset();
    pAsset33.id = "smore_set";
    pAsset33.city = "candy_name";
    pAsset33.clan = "candy_name";
    pAsset33.culture = "candy_name";
    pAsset33.family = "candy_name";
    pAsset33.kingdom = "candy_name";
    pAsset33.language = "candy_name";
    pAsset33.unit = "candy_name";
    pAsset33.religion = "candy_name";
    this.add(pAsset33);
    NameSetAsset pAsset34 = new NameSetAsset();
    pAsset34.id = "insect_set";
    pAsset34.city = "bug_name";
    pAsset34.clan = "bug_name";
    pAsset34.culture = "bug_name";
    pAsset34.family = "bug_name";
    pAsset34.kingdom = "bug_name";
    pAsset34.language = "bug_name";
    pAsset34.unit = "bug_name";
    pAsset34.religion = "bug_name";
    this.add(pAsset34);
    NameSetAsset pAsset35 = new NameSetAsset();
    pAsset35.id = "candy_man_set";
    pAsset35.city = "candy_name";
    pAsset35.clan = "candy_name";
    pAsset35.culture = "candy_name";
    pAsset35.family = "candy_name";
    pAsset35.kingdom = "candy_name";
    pAsset35.language = "candy_name";
    pAsset35.unit = "candy_name";
    pAsset35.religion = "candy_name";
    this.add(pAsset35);
    NameSetAsset pAsset36 = new NameSetAsset();
    pAsset36.id = "alpaca_set";
    pAsset36.city = "alpaca_name";
    pAsset36.clan = "alpaca_name";
    pAsset36.culture = "alpaca_name";
    pAsset36.family = "alpaca_name";
    pAsset36.kingdom = "alpaca_name";
    pAsset36.language = "alpaca_name";
    pAsset36.unit = "alpaca_name";
    pAsset36.religion = "alpaca_name";
    this.add(pAsset36);
    NameSetAsset pAsset37 = new NameSetAsset();
    pAsset37.id = "hyena_set";
    pAsset37.city = "hyena_city";
    pAsset37.clan = "hyena_name";
    pAsset37.culture = "hyena_name";
    pAsset37.family = "hyena_name";
    pAsset37.kingdom = "hyena_name";
    pAsset37.language = "hyena_name";
    pAsset37.unit = "hyena_name";
    pAsset37.religion = "hyena_name";
    this.add(pAsset37);
    NameSetAsset pAsset38 = new NameSetAsset();
    pAsset38.id = "snake_set";
    pAsset38.city = "snake_city";
    pAsset38.clan = "snake_name";
    pAsset38.culture = "snake_name";
    pAsset38.family = "snake_name";
    pAsset38.kingdom = "snake_name";
    pAsset38.language = "snake_name";
    pAsset38.unit = "snake_name";
    pAsset38.religion = "snake_name";
    this.add(pAsset38);
  }

  private void addFantasyRaces()
  {
    NameSetAsset pAsset1 = new NameSetAsset();
    pAsset1.id = "dwarf_default_set";
    pAsset1.city = "dwarf_city";
    pAsset1.clan = "dwarf_clan";
    pAsset1.culture = "dwarf_culture";
    pAsset1.family = "dwarf_clan";
    pAsset1.kingdom = "dwarf_kingdom";
    pAsset1.language = "dwarf_language";
    pAsset1.unit = "dwarf_unit";
    pAsset1.religion = "dwarf_religion";
    this.add(pAsset1);
    NameSetAsset pAsset2 = new NameSetAsset();
    pAsset2.id = "dwarf_nordic_set";
    pAsset2.city = "nordic_city";
    pAsset2.clan = "nordic_clan";
    pAsset2.culture = "dwarf_culture";
    pAsset2.family = "nordic_clan";
    pAsset2.kingdom = "nordic_kingdom";
    pAsset2.language = "dwarf_language";
    pAsset2.unit = "nordic_unit";
    pAsset2.religion = "dwarf_religion";
    this.add(pAsset2);
    NameSetAsset pAsset3 = new NameSetAsset();
    pAsset3.id = "elf_default_set";
    pAsset3.city = "elf_city";
    pAsset3.clan = "elf_clan";
    pAsset3.culture = "elf_culture";
    pAsset3.family = "elf_clan";
    pAsset3.kingdom = "elf_kingdom";
    pAsset3.language = "elf_language";
    pAsset3.unit = "elf_unit";
    pAsset3.religion = "elf_religion";
    this.add(pAsset3);
    NameSetAsset pAsset4 = new NameSetAsset();
    pAsset4.id = "orc_default_set";
    pAsset4.city = "orc_city";
    pAsset4.clan = "orc_clan";
    pAsset4.culture = "orc_culture";
    pAsset4.family = "orc_clan";
    pAsset4.kingdom = "orc_kingdom";
    pAsset4.language = "orc_language";
    pAsset4.unit = "orc_unit";
    pAsset4.religion = "orc_religion";
    this.add(pAsset4);
  }

  private void addHumanLike()
  {
    NameSetAsset pAsset1 = new NameSetAsset();
    pAsset1.id = "human_default_set";
    pAsset1.city = "human_city";
    pAsset1.clan = "human_clan";
    pAsset1.culture = "human_culture";
    pAsset1.family = "human_clan";
    pAsset1.kingdom = "human_kingdom";
    pAsset1.language = "human_language";
    pAsset1.unit = "human_unit";
    pAsset1.religion = "human_religion";
    this.add(pAsset1);
    NameSetAsset pAsset2 = new NameSetAsset();
    pAsset2.id = "human_slavic_set";
    pAsset2.city = "slavic_city";
    pAsset2.clan = "slavic_clan";
    pAsset2.culture = "human_culture";
    pAsset2.family = "slavic_clan";
    pAsset2.kingdom = "slavic_kingdom";
    pAsset2.language = "human_language";
    pAsset2.unit = "slavic_unit";
    pAsset2.religion = "human_religion";
    this.add(pAsset2);
    NameSetAsset pAsset3 = new NameSetAsset();
    pAsset3.id = "human_germanic_set";
    pAsset3.city = "germanic_city";
    pAsset3.clan = "germanic_clan";
    pAsset3.culture = "human_culture";
    pAsset3.family = "germanic_clan";
    pAsset3.kingdom = "germanic_kingdom";
    pAsset3.language = "human_language";
    pAsset3.unit = "germanic_unit";
    pAsset3.religion = "human_religion";
    this.add(pAsset3);
    NameSetAsset pAsset4 = new NameSetAsset();
    pAsset4.id = "human_rus_set";
    pAsset4.city = "rus_city";
    pAsset4.clan = "rus_clan";
    pAsset4.culture = "human_culture";
    pAsset4.family = "rus_clan";
    pAsset4.kingdom = "rus_kingdom";
    pAsset4.language = "human_language";
    pAsset4.unit = "rus_unit";
    pAsset4.religion = "human_religion";
    this.add(pAsset4);
    NameSetAsset pAsset5 = new NameSetAsset();
    pAsset5.id = "human_posh_set";
    pAsset5.city = "posh_city";
    pAsset5.clan = "posh_clan";
    pAsset5.culture = "human_culture";
    pAsset5.family = "posh_clan";
    pAsset5.kingdom = "posh_kingdom";
    pAsset5.language = "human_language";
    pAsset5.unit = "posh_unit";
    pAsset5.religion = "human_religion";
    this.add(pAsset5);
    NameSetAsset pAsset6 = new NameSetAsset();
    pAsset6.id = "human_folk_set";
    pAsset6.city = "folk_city";
    pAsset6.clan = "folk_clan";
    pAsset6.culture = "human_culture";
    pAsset6.family = "folk_clan";
    pAsset6.kingdom = "folk_kingdom";
    pAsset6.language = "human_language";
    pAsset6.unit = "folk_unit";
    pAsset6.religion = "human_religion";
    this.add(pAsset6);
    NameSetAsset pAsset7 = new NameSetAsset();
    pAsset7.id = "human_pomeranian_set";
    pAsset7.city = "pomeranian_city";
    pAsset7.clan = "pomeranian_clan";
    pAsset7.culture = "human_culture";
    pAsset7.family = "pomeranian_clan";
    pAsset7.kingdom = "pomeranian_kingdom";
    pAsset7.language = "human_language";
    pAsset7.unit = "pomeranian_unit";
    pAsset7.religion = "human_religion";
    this.add(pAsset7);
    NameSetAsset pAsset8 = new NameSetAsset();
    pAsset8.id = "human_frankish_set";
    pAsset8.city = "frankish_city";
    pAsset8.clan = "frankish_clan";
    pAsset8.culture = "human_culture";
    pAsset8.family = "frankish_clan";
    pAsset8.kingdom = "frankish_kingdom";
    pAsset8.language = "human_language";
    pAsset8.unit = "frankish_unit";
    pAsset8.religion = "human_religion";
    this.add(pAsset8);
    NameSetAsset pAsset9 = new NameSetAsset();
    pAsset9.id = "human_rome_set";
    pAsset9.city = "rome_city";
    pAsset9.clan = "rome_clan";
    pAsset9.culture = "human_culture";
    pAsset9.family = "rome_clan";
    pAsset9.kingdom = "rome_kingdom";
    pAsset9.language = "human_language";
    pAsset9.unit = "rome_unit";
    pAsset9.religion = "human_religion";
    this.add(pAsset9);
    NameSetAsset pAsset10 = new NameSetAsset();
    pAsset10.id = "human_iberian_set";
    pAsset10.city = "iberian_city";
    pAsset10.clan = "iberian_clan";
    pAsset10.culture = "human_culture";
    pAsset10.family = "iberian_clan";
    pAsset10.kingdom = "iberian_kingdom";
    pAsset10.language = "human_language";
    pAsset10.unit = "iberian_unit";
    pAsset10.religion = "human_religion";
    this.add(pAsset10);
    NameSetAsset pAsset11 = new NameSetAsset();
    pAsset11.id = "human_monolux_set";
    pAsset11.city = "monolux_city";
    pAsset11.clan = "monolux_clan";
    pAsset11.culture = "human_culture";
    pAsset11.family = "monolux_clan";
    pAsset11.kingdom = "monolux_kingdom";
    pAsset11.language = "human_language";
    pAsset11.unit = "monolux_unit";
    pAsset11.religion = "human_religion";
    this.add(pAsset11);
    NameSetAsset pAsset12 = new NameSetAsset();
    pAsset12.id = "polynesian_set";
    pAsset12.city = "poly_city";
    pAsset12.clan = "poly_clan";
    pAsset12.culture = "human_culture";
    pAsset12.family = "poly_clan";
    pAsset12.kingdom = "poly_kingdom";
    pAsset12.language = "human_language";
    pAsset12.unit = "poly_unit";
    pAsset12.religion = "human_religion";
    this.add(pAsset12);
    NameSetAsset pAsset13 = new NameSetAsset();
    pAsset13.id = "nomads_set";
    pAsset13.city = "nomad_city";
    pAsset13.clan = "nomad_clan";
    pAsset13.culture = "human_culture";
    pAsset13.family = "nomad_clan";
    pAsset13.kingdom = "nomad_kingdom";
    pAsset13.language = "human_language";
    pAsset13.unit = "nomad_unit";
    pAsset13.religion = "human_religion";
    this.add(pAsset13);
    NameSetAsset pAsset14 = new NameSetAsset();
    pAsset14.id = "sino_set";
    pAsset14.city = "sino_city";
    pAsset14.clan = "sino_clan";
    pAsset14.culture = "human_culture";
    pAsset14.family = "sino_clan";
    pAsset14.kingdom = "sino_kingdom";
    pAsset14.language = "human_language";
    pAsset14.unit = "sino_unit";
    pAsset14.religion = "human_religion";
    this.add(pAsset14);
    NameSetAsset pAsset15 = new NameSetAsset();
    pAsset15.id = "siam_set";
    pAsset15.city = "siam_city";
    pAsset15.clan = "siam_clan";
    pAsset15.culture = "human_culture";
    pAsset15.family = "siam_clan";
    pAsset15.kingdom = "siam_kingdom";
    pAsset15.language = "human_language";
    pAsset15.unit = "siam_unit";
    pAsset15.religion = "human_religion";
    this.add(pAsset15);
    NameSetAsset pAsset16 = new NameSetAsset();
    pAsset16.id = "vishna_set";
    pAsset16.city = "vishna_city";
    pAsset16.clan = "vishna_clan";
    pAsset16.culture = "human_culture";
    pAsset16.family = "vishna_family";
    pAsset16.kingdom = "vishna_kingdom";
    pAsset16.language = "human_language";
    pAsset16.unit = "vishna_unit";
    pAsset16.religion = "human_religion";
    this.add(pAsset16);
    NameSetAsset pAsset17 = new NameSetAsset();
    pAsset17.id = "nihon_set";
    pAsset17.city = "nihon_city";
    pAsset17.clan = "nihon_clan";
    pAsset17.culture = "human_culture";
    pAsset17.family = "nihon_clan";
    pAsset17.kingdom = "nihon_kingdom";
    pAsset17.language = "human_language";
    pAsset17.unit = "nihon_unit";
    pAsset17.religion = "human_religion";
    this.add(pAsset17);
  }

  public override void editorDiagnostic()
  {
    // ISSUE: unable to decompile the method.
  }
}
