// Decompiled with JetBrains decompiler
// Type: ProjectileLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

#nullable disable
public class ProjectileLibrary : AssetLibrary<ProjectileAsset>
{
  public override void init()
  {
    base.init();
    ProjectileAsset pAsset1 = new ProjectileAsset();
    pAsset1.id = "arrow";
    pAsset1.speed = 20f;
    pAsset1.texture = "arrow";
    pAsset1.texture_shadow = "shadows/projectiles/shadow_arrow";
    pAsset1.sound_launch = "event:/SFX/WEAPONS/WeaponStartArrow";
    pAsset1.sound_impact = "event:/SFX/HIT/HitGeneric";
    pAsset1.can_be_left_on_ground = true;
    pAsset1.can_be_blocked = true;
    this.add(pAsset1);
    ProjectileAsset pAsset2 = new ProjectileAsset();
    pAsset2.id = "snowball";
    pAsset2.texture = "snowball";
    pAsset2.texture_shadow = "shadows/projectiles/shadow_snowball";
    pAsset2.sound_launch = "event:/SFX/WEAPONS/WeaponStartThrow";
    pAsset2.sound_impact = "event:/SFX/WEAPONS/WeaponSnowballLand";
    pAsset2.hit_freeze = true;
    pAsset2.can_be_blocked = true;
    this.add(pAsset2);
    ProjectileAsset pAsset3 = new ProjectileAsset();
    pAsset3.id = "firebomb";
    pAsset3.texture = "firebomb";
    pAsset3.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset3.speed = 12f;
    pAsset3.trigger_on_collision = true;
    pAsset3.terraform_option = "demon_fireball";
    pAsset3.end_effect = "fx_firebomb_explosion";
    pAsset3.hit_shake = true;
    pAsset3.shake_duration = 0.01f;
    pAsset3.shake_interval = 0.01f;
    pAsset3.shake_intensity = 0.25f;
    pAsset3.scale_start = 0.075f;
    pAsset3.scale_target = 0.075f;
    pAsset3.draw_light_area = true;
    pAsset3.sound_launch = "event:/SFX/WEAPONS/WeaponStartThrow";
    pAsset3.terraform_range = 2;
    this.add(pAsset3);
    ProjectileAsset pAsset4 = new ProjectileAsset();
    pAsset4.id = "torch";
    pAsset4.texture = "pr_torch";
    pAsset4.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset4.terraform_option = "torch";
    pAsset4.scale_start = 0.075f;
    pAsset4.scale_target = 0.075f;
    pAsset4.speed = 15f;
    pAsset4.terraform_range = 1;
    pAsset4.trigger_on_collision = true;
    pAsset4.draw_light_area = true;
    pAsset4.sound_launch = "event:/SFX/WEAPONS/WeaponStartThrow";
    pAsset4.sound_impact = "event:/SFX/WEAPONS/WeaponTorchLand";
    this.add(pAsset4);
    ProjectileAsset pAsset5 = new ProjectileAsset();
    pAsset5.id = "red_orb";
    pAsset5.speed_random = 5f;
    pAsset5.texture = "pr_red_orb";
    pAsset5.trigger_on_collision = true;
    pAsset5.scale_start = 0.035f;
    pAsset5.scale_target = 0.2f;
    pAsset5.sound_launch = "event:/SFX/WEAPONS/WeaponRedOrbStart";
    pAsset5.sound_impact = "event:/SFX/WEAPONS/WeaponRedOrbLand";
    pAsset5.draw_light_area = true;
    this.add(pAsset5);
    this.t.world_actions += new AttackAction(ActionLibrary.burnTile);
    ProjectileAsset pAsset6 = new ProjectileAsset();
    pAsset6.id = "freeze_orb";
    pAsset6.texture = "pr_freeze_orb";
    pAsset6.trigger_on_collision = true;
    pAsset6.scale_start = 0.035f;
    pAsset6.scale_target = 0.2f;
    pAsset6.sound_launch = "event:/SFX/WEAPONS/WeaponFreezeOrbStart";
    pAsset6.sound_impact = "event:/SFX/WEAPONS/WeaponFreezeOrbLand";
    pAsset6.draw_light_area = true;
    this.add(pAsset6);
    ProjectileAsset pAsset7 = new ProjectileAsset();
    pAsset7.id = "green_orb";
    pAsset7.texture = "pr_green_orb";
    pAsset7.trigger_on_collision = true;
    pAsset7.scale_start = 0.035f;
    pAsset7.scale_target = 0.2f;
    pAsset7.sound_launch = "event:/SFX/WEAPONS/WeaponGreenOrbStart";
    pAsset7.sound_impact = "event:/SFX/WEAPONS/WeaponGreenOrbLand";
    pAsset7.draw_light_area = true;
    this.add(pAsset7);
    ProjectileAsset pAsset8 = new ProjectileAsset();
    pAsset8.id = "bone";
    pAsset8.speed = 15f;
    pAsset8.texture = "pr_bone";
    pAsset8.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset8.scale_start = 0.035f;
    pAsset8.scale_target = 0.05f;
    pAsset8.sound_launch = "event:/SFX/WEAPONS/WeaponBoneProjectileStart";
    pAsset8.sound_impact = "event:/SFX/WEAPONS/WeaponBoneProjectileLand";
    pAsset8.can_be_blocked = true;
    this.add(pAsset8);
    ProjectileAsset pAsset9 = new ProjectileAsset();
    pAsset9.id = "plasma_ball";
    pAsset9.speed = 40f;
    pAsset9.texture = "pr_plasma_ball";
    pAsset9.trigger_on_collision = true;
    pAsset9.trail_effect_enabled = true;
    pAsset9.trail_effect_id = "fx_plasma_trail";
    pAsset9.trail_effect_scale = 0.1f;
    pAsset9.trail_effect_timer = 0.1f;
    pAsset9.look_at_target = true;
    pAsset9.terraform_option = "plasma_ball";
    pAsset9.end_effect = "fx_plasma_ball_explosion";
    pAsset9.terraform_range = 2;
    pAsset9.draw_light_area = true;
    pAsset9.draw_light_size = 0.1f;
    pAsset9.sound_launch = "event:/SFX/WEAPONS/WeaponPlasmaBallStart";
    pAsset9.sound_impact = "event:/SFX/WEAPONS/WeaponPlasmaBallLand";
    pAsset9.scale_start = 0.035f;
    pAsset9.scale_target = 0.2f;
    pAsset9.mass = 1f;
    this.add(pAsset9);
    ProjectileAsset pAsset10 = new ProjectileAsset();
    pAsset10.id = "skull";
    pAsset10.speed = 17f;
    pAsset10.texture = "pr_skull";
    pAsset10.animation_speed = 10f;
    pAsset10.trigger_on_collision = true;
    pAsset10.look_at_target = true;
    pAsset10.end_effect = "fx_cast_ground_purple";
    pAsset10.end_effect_scale = 0.12f;
    pAsset10.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset10.scale_start = 0.035f;
    pAsset10.scale_target = 0.08f;
    pAsset10.sound_launch = "event:/SFX/WEAPONS/WeaponBoneProjectileStart";
    pAsset10.sound_impact = "event:/SFX/WEAPONS/WeaponBoneProjectileLand";
    this.add(pAsset10);
    ProjectileAsset pAsset11 = new ProjectileAsset();
    pAsset11.id = "fireball";
    pAsset11.speed = 25f;
    pAsset11.texture = "fireball";
    pAsset11.trail_effect_enabled = true;
    pAsset11.trigger_on_collision = true;
    pAsset11.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset11.terraform_option = "demon_fireball";
    pAsset11.end_effect = "fx_fireball_explosion";
    pAsset11.terraform_range = 3;
    pAsset11.draw_light_area = true;
    pAsset11.draw_light_size = 0.1f;
    pAsset11.sound_launch = "event:/SFX/WEAPONS/WeaponFireballStart";
    pAsset11.sound_impact = "event:/SFX/WEAPONS/WeaponFireballLand";
    pAsset11.scale_start = 0.035f;
    pAsset11.scale_target = 0.2f;
    this.add(pAsset11);
    ProjectileAsset pAsset12 = new ProjectileAsset();
    pAsset12.id = "madness_ball";
    pAsset12.speed = 30f;
    pAsset12.trigger_on_collision = true;
    pAsset12.texture = "madness_ball";
    pAsset12.terraform_option = "madness_ball";
    pAsset12.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset12.terraform_range = 3;
    pAsset12.scale_start = 0.035f;
    pAsset12.scale_target = 0.2f;
    pAsset12.draw_light_area = true;
    pAsset12.sound_launch = "event:/SFX/WEAPONS/WeaponMadnessBallStart";
    pAsset12.sound_impact = "event:/SFX/WEAPONS/WeaponMadnessBallLand";
    this.add(pAsset12);
    ProjectileAsset pAsset13 = new ProjectileAsset();
    pAsset13.id = "rock";
    pAsset13.texture = "rock";
    pAsset13.texture_shadow = "shadows/projectiles/shadow_snowball";
    pAsset13.sound_launch = "event:/SFX/WEAPONS/WeaponStartThrow";
    pAsset13.sound_impact = "event:/SFX/WEAPONS/WeaponRockLand";
    pAsset13.can_be_left_on_ground = true;
    pAsset13.scale_start = 0.05f;
    pAsset13.scale_target = 0.09f;
    pAsset13.can_be_blocked = true;
    this.add(pAsset13);
    ProjectileAsset pAsset14 = new ProjectileAsset();
    pAsset14.id = "shotgun_bullet";
    pAsset14.speed = 30f;
    pAsset14.speed_random = 7f;
    pAsset14.texture = "shotgun_bullet";
    pAsset14.look_at_target = true;
    pAsset14.draw_light_area = true;
    pAsset14.terraform_option = "assimilator_bullet";
    pAsset14.sound_launch = "event:/SFX/WEAPONS/WeaponShotgunStart";
    pAsset14.sound_impact = "event:/SFX/WEAPONS/WeaponShotgunLand";
    pAsset14.scale_start = 0.035f;
    pAsset14.scale_target = 0.08f;
    pAsset14.can_be_blocked = true;
    this.add(pAsset14);
    ProjectileAsset pAsset15 = new ProjectileAsset();
    pAsset15.id = "cannonball";
    pAsset15.speed = 25f;
    pAsset15.texture = "cannonball";
    pAsset15.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset15.terraform_option = "cannonball";
    pAsset15.terraform_range = 2;
    pAsset15.sound_launch = "event:/SFX/WEAPONS/WeaponShotgunStart";
    pAsset15.sound_impact = "event:/SFX/WEAPONS/WeaponShotgunLand";
    pAsset15.end_effect = "fx_firebomb_explosion";
    pAsset15.scale_start = 0.1f;
    pAsset15.scale_target = 0.1f;
    this.add(pAsset15);
    ProjectileAsset pAsset16 = new ProjectileAsset();
    pAsset16.id = "acid_ball";
    pAsset16.speed = 25f;
    pAsset16.texture = "acid_ball";
    pAsset16.texture_shadow = "shadows/projectiles/shadow_ball";
    pAsset16.terraform_option = "acid_ball";
    pAsset16.terraform_range = 2;
    pAsset16.sound_impact = "event:/SFX/DROPS/DropAcid";
    pAsset16.end_effect = "fx_cast_top_green";
    pAsset16.scale_start = 0.1f;
    pAsset16.scale_target = 0.1f;
    this.add(pAsset16);
  }
}
