// Decompiled with JetBrains decompiler
// Type: TerraformLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

#nullable disable
public class TerraformLibrary : AssetLibrary<TerraformOptions>
{
  public static TerraformOptions nothing;
  public static TerraformOptions remove_lava;
  public static TerraformOptions lava_damage;
  public static TerraformOptions destroy_no_flash;
  public static TerraformOptions remove;
  public static TerraformOptions draw;
  public static TerraformOptions water_fill;
  public static TerraformOptions grey_goo;
  public static TerraformOptions flash;
  public static TerraformOptions road;
  public static TerraformOptions tumor_attack;
  public static TerraformOptions destroy;
  public static TerraformOptions destroy_life;
  public static TerraformOptions earthquake;
  public static TerraformOptions earthquake_disaster;
  public static TerraformOptions atomic_bomb;
  public static TerraformOptions crabzilla_bomb;
  public static TerraformOptions bomb;
  public static TerraformOptions czar_bomba;

  public override void init()
  {
    base.init();
    TerraformOptions pAsset1 = new TerraformOptions();
    pAsset1.id = "tumor_attack";
    pAsset1.flash = true;
    pAsset1.destroy_buildings = true;
    pAsset1.remove_frozen = true;
    pAsset1.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("tumor");
    TerraformLibrary.tumor_attack = this.add(pAsset1);
    TerraformOptions pAsset2 = new TerraformOptions();
    pAsset2.id = "destroy";
    pAsset2.flash = true;
    pAsset2.destroy_buildings = true;
    TerraformLibrary.destroy = this.add(pAsset2);
    TerraformOptions pAsset3 = new TerraformOptions();
    pAsset3.id = "destroy_life";
    pAsset3.destroy_only = AssetLibrary<TerraformOptions>.l<string>("tumor", "super_pumpkin", "biomass");
    pAsset3.destroy_buildings = true;
    pAsset3.flash = true;
    pAsset3.remove_borders = true;
    pAsset3.remove_tornado = true;
    TerraformLibrary.destroy_life = this.add(pAsset3);
    TerraformOptions pAsset4 = new TerraformOptions();
    pAsset4.id = "earthquake";
    pAsset4.remove_lava = true;
    pAsset4.make_ruins = true;
    pAsset4.remove_top_tile = true;
    pAsset4.remove_roads = true;
    pAsset4.remove_frozen = true;
    pAsset4.remove_water = true;
    TerraformLibrary.earthquake = this.add(pAsset4);
    TerraformOptions pAsset5 = new TerraformOptions();
    pAsset5.id = "earthquake_disaster";
    pAsset5.remove_lava = true;
    pAsset5.make_ruins = true;
    pAsset5.remove_top_tile = true;
    pAsset5.remove_roads = true;
    pAsset5.remove_frozen = true;
    pAsset5.remove_water = true;
    TerraformLibrary.earthquake_disaster = this.add(pAsset5);
    TerraformOptions pAsset6 = new TerraformOptions();
    pAsset6.id = "road";
    pAsset6.flash = true;
    pAsset6.destroy_buildings = true;
    pAsset6.remove_frozen = true;
    pAsset6.destroy_only = AssetLibrary<TerraformOptions>.l<string>("nature");
    TerraformLibrary.road = this.add(pAsset6);
    TerraformOptions pAsset7 = new TerraformOptions();
    pAsset7.id = "flash";
    pAsset7.flash = true;
    TerraformLibrary.flash = this.add(pAsset7);
    TerraformOptions pAsset8 = new TerraformOptions();
    pAsset8.id = "grey_goo";
    pAsset8.destroy_buildings = true;
    pAsset8.flash = true;
    pAsset8.remove_borders = true;
    pAsset8.remove_frozen = true;
    TerraformLibrary.grey_goo = this.add(pAsset8);
    TerraformOptions pAsset9 = new TerraformOptions();
    pAsset9.id = "remove";
    pAsset9.flash = true;
    pAsset9.destroy_buildings = true;
    pAsset9.remove_frozen = true;
    TerraformLibrary.remove = this.add(pAsset9);
    TerraformOptions pAsset10 = new TerraformOptions();
    pAsset10.id = "draw";
    pAsset10.flash = true;
    pAsset10.remove_frozen = true;
    TerraformLibrary.draw = this.add(pAsset10);
    TerraformOptions pAsset11 = new TerraformOptions();
    pAsset11.id = "water_fill";
    pAsset11.flash = true;
    pAsset11.destroy_buildings = true;
    pAsset11.remove_frozen = true;
    pAsset11.remove_fire = true;
    pAsset11.ignore_buildings = AssetLibrary<TerraformOptions>.l<string>("geyser", "volcano", "geyser_acid");
    TerraformLibrary.water_fill = this.add(pAsset11);
    TerraformOptions pAsset12 = new TerraformOptions();
    pAsset12.id = "destroy_no_flash";
    pAsset12.remove_burned = true;
    pAsset12.destroy_buildings = true;
    TerraformLibrary.destroy_no_flash = this.add(pAsset12);
    TerraformOptions pAsset13 = new TerraformOptions();
    pAsset13.id = "nothing";
    TerraformLibrary.nothing = this.add(pAsset13);
    TerraformOptions pAsset14 = new TerraformOptions();
    pAsset14.id = "remove_lava";
    pAsset14.remove_lava = true;
    TerraformLibrary.remove_lava = this.add(pAsset14);
    TerraformOptions pAsset15 = new TerraformOptions();
    pAsset15.id = "lava_damage";
    pAsset15.flash = true;
    pAsset15.damage_buildings = true;
    pAsset15.damage = 100;
    pAsset15.remove_frozen = true;
    TerraformLibrary.lava_damage = this.add(pAsset15);
    TerraformOptions pAsset16 = new TerraformOptions();
    pAsset16.id = "grenade";
    pAsset16.flash = true;
    pAsset16.damage_buildings = true;
    pAsset16.damage = 50;
    pAsset16.apply_force = true;
    pAsset16.explode_and_set_random_fire = true;
    pAsset16.explode_tile = true;
    pAsset16.explosion_pixel_effect = true;
    pAsset16.explode_strength = 1;
    pAsset16.shake = true;
    pAsset16.remove_tornado = true;
    pAsset16.remove_frozen = true;
    pAsset16.attack_type = AttackType.Explosion;
    this.add(pAsset16);
    TerraformOptions pAsset17 = new TerraformOptions();
    pAsset17.id = "lightning_power";
    pAsset17.flash = true;
    pAsset17.lightning_effect = true;
    pAsset17.add_burned = true;
    pAsset17.add_heat = 9;
    pAsset17.damage = 77;
    pAsset17.set_fire = true;
    pAsset17.apply_force = true;
    pAsset17.force_power = 2.5f;
    pAsset17.shake = true;
    pAsset17.shake_intensity = 2f;
    pAsset17.remove_frozen = true;
    this.add(pAsset17);
    TerraformOptions pAsset18 = new TerraformOptions();
    pAsset18.id = "lightning_normal";
    pAsset18.flash = true;
    pAsset18.lightning_effect = true;
    pAsset18.add_burned = true;
    pAsset18.damage = 47;
    pAsset18.set_fire = true;
    pAsset18.apply_force = true;
    pAsset18.force_power = 2.5f;
    pAsset18.remove_frozen = true;
    this.add(pAsset18);
    TerraformOptions pAsset19 = new TerraformOptions();
    pAsset19.id = "madness_ball";
    pAsset19.apply_force = true;
    pAsset19.force_power = 1.6f;
    pAsset19.add_trait = "madness";
    pAsset19.flash = true;
    pAsset19.remove_frozen = true;
    this.add(pAsset19);
    TerraformOptions pAsset20 = new TerraformOptions();
    pAsset20.id = "ufo_attack";
    pAsset20.flash = true;
    pAsset20.add_burned = true;
    pAsset20.damage = 50;
    pAsset20.set_fire = true;
    pAsset20.apply_force = true;
    pAsset20.shake = true;
    pAsset20.damage_buildings = true;
    pAsset20.remove_frozen = true;
    this.add(pAsset20);
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("aliens");
    this.t.shake_intensity = 0.1f;
    TerraformOptions pAsset21 = new TerraformOptions();
    pAsset21.id = "dragon_attack";
    pAsset21.flash = true;
    pAsset21.add_burned = true;
    pAsset21.force_power = 0.5f;
    pAsset21.damage = 25;
    pAsset21.set_fire = true;
    pAsset21.apply_force = true;
    pAsset21.shake = true;
    pAsset21.damage_buildings = true;
    pAsset21.remove_frozen = true;
    pAsset21.attack_type = AttackType.Fire;
    this.add(pAsset21);
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("dragons");
    this.t.shake_intensity = 0.1f;
    TerraformOptions pAsset22 = new TerraformOptions();
    pAsset22.id = "zombie_dragon_attack";
    pAsset22.flash = true;
    pAsset22.force_power = 0.5f;
    pAsset22.damage = 25;
    pAsset22.set_fire = false;
    pAsset22.apply_force = true;
    pAsset22.shake = true;
    pAsset22.damage_buildings = true;
    pAsset22.remove_frozen = true;
    pAsset22.attack_type = AttackType.Acid;
    this.add(pAsset22);
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("undead");
    this.t.shake_intensity = 0.1f;
    this.clone("ufo_explosion", "grenade");
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("aliens");
    TerraformLibrary.bomb = this.clone("bomb", "grenade");
    this.t.damage = 100;
    this.t.explode_strength = 3;
    this.clone("meteorite", "grenade");
    this.t.damage = 1000;
    this.t.explode_strength = 1;
    this.clone("meteorite_disaster", "grenade");
    this.t.damage = 500;
    this.t.explode_strength = 1;
    this.clone("crab_bomb", "grenade");
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("crabzilla", "crab");
    this.t.damage_buildings = true;
    this.t.damage = 30;
    this.t.set_fire = true;
    this.t.shake = false;
    TerraformLibrary.atomic_bomb = this.clone("atomic_bomb", "bomb");
    this.t.damage = 10000;
    this.t.explode_strength = 1;
    this.t.transform_to_wasteland = true;
    this.t.applies_to_high_flyers = true;
    this.t.shake = false;
    this.t.bomb_action = new WorldAction(NukeFlash.atomic_bomb_action);
    TerraformLibrary.crabzilla_bomb = this.clone("crabzilla_bomb", "bomb");
    this.t.damage = 10000;
    this.t.explode_strength = 1;
    this.t.applies_to_high_flyers = true;
    this.t.bomb_action = new WorldAction(NukeFlash.crabzilla_bomb_action);
    TerraformLibrary.czar_bomba = this.clone("czar_bomba", "bomb");
    this.t.damage = 10000;
    this.t.transform_to_wasteland = true;
    this.t.explode_strength = 4;
    this.t.applies_to_high_flyers = true;
    this.t.shake = false;
    this.t.bomb_action = new WorldAction(NukeFlash.czar_bomba_action);
    TerraformOptions pAsset23 = new TerraformOptions();
    pAsset23.id = "crab_step";
    pAsset23.flash = true;
    pAsset23.damage_buildings = true;
    pAsset23.damage = 10;
    pAsset23.apply_force = true;
    pAsset23.explode_tile = true;
    pAsset23.explosion_pixel_effect = false;
    pAsset23.explode_strength = 1;
    pAsset23.shake = true;
    pAsset23.shake_intensity = 0.1f;
    pAsset23.remove_frozen = true;
    this.add(pAsset23);
    this.clone("crab_laser", "bomb");
    this.t.damage = 200;
    this.t.explode_strength = 1;
    this.t.shake_intensity = 1f;
    this.t.attack_type = AttackType.Fire;
    this.clone("santa_bomb", "bomb");
    this.clone("demon_fireball", "grenade");
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("demon");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 30;
    this.t.set_fire = true;
    this.clone("plasma_ball", "grenade");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 30;
    this.clone("torch", "grenade");
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("demon");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 25;
    this.t.set_fire = true;
    this.t.attack_type = AttackType.Fire;
    this.clone("assimilator_bullet", "flash");
    this.t.remove_frozen = true;
    this.t.ignore_kingdoms = AssetLibrary<TerraformOptions>.a<string>("assimilators");
    this.t.remove_frozen = true;
    this.clone("cannonball", "grenade");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 0;
    this.t.apply_force = true;
    this.t.force_power = 2f;
    this.clone("acid", "grenade");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 0;
    this.t.explode_strength = 2;
    this.t.apply_force = true;
    this.t.force_power = 0.5f;
    this.t.set_fire = false;
    this.t.flash = true;
    this.t.remove_frozen = true;
    this.t.explode_and_set_random_fire = false;
    this.t.attack_type = AttackType.Acid;
    this.clone("acid_ball", "grenade");
    this.t.shake = false;
    this.t.damage_buildings = true;
    this.t.damage = 0;
    this.t.apply_force = true;
    this.t.force_power = 0.5f;
    this.t.set_fire = false;
    this.t.flash = true;
    this.t.remove_frozen = true;
    this.t.explode_and_set_random_fire = false;
    this.t.attack_type = AttackType.Acid;
  }
}
