// Decompiled with JetBrains decompiler
// Type: TesterBehTaskLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

using Unity.Mathematics;

#nullable disable
public class TesterBehTaskLibrary : AssetLibrary<BehaviourTaskTester>
{
  public override void init()
  {
    base.init();
    BehaviourTaskTester behaviourTaskTester1 = new BehaviourTaskTester();
    behaviourTaskTester1.id = "close_all_windows";
    BehaviourTaskTester pAsset1 = behaviourTaskTester1;
    this.t = behaviourTaskTester1;
    this.add(pAsset1);
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    BehaviourTaskTester behaviourTaskTester2 = new BehaviourTaskTester();
    behaviourTaskTester2.id = "open_random_window";
    BehaviourTaskTester pAsset2 = behaviourTaskTester2;
    this.t = behaviourTaskTester2;
    this.add(pAsset2);
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("random"));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    BehaviourTaskTester behaviourTaskTester3 = new BehaviourTaskTester();
    behaviourTaskTester3.id = "open_next_window";
    BehaviourTaskTester pAsset3 = behaviourTaskTester3;
    this.t = behaviourTaskTester3;
    this.add(pAsset3);
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenNextWindow());
    BehaviourTaskTester behaviourTaskTester4 = new BehaviourTaskTester();
    behaviourTaskTester4.id = "open_next_meta_window";
    BehaviourTaskTester pAsset4 = behaviourTaskTester4;
    this.t = behaviourTaskTester4;
    this.add(pAsset4);
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenNextWindow(true));
    BehaviourTaskTester behaviourTaskTester5 = new BehaviourTaskTester();
    behaviourTaskTester5.id = "open_random_meta_window";
    BehaviourTaskTester pAsset5 = behaviourTaskTester5;
    this.t = behaviourTaskTester5;
    this.add(pAsset5);
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenNextWindow(true, true));
    BehaviourTaskTester behaviourTaskTester6 = new BehaviourTaskTester();
    behaviourTaskTester6.id = "screenshot_window";
    BehaviourTaskTester pAsset6 = behaviourTaskTester6;
    this.t = behaviourTaskTester6;
    this.add(pAsset6);
    this.t.addBeh((BehaviourActionTester) new TesterBehScreenshotTooltips());
    this.t.addBeh((BehaviourActionTester) new TesterBehScreenshotWindow());
    this.t.addBeh((BehaviourActionTester) new TesterBehScrollWindow());
    BehaviourTaskTester behaviourTaskTester7 = new BehaviourTaskTester();
    behaviourTaskTester7.id = "test_window_and_tooltips";
    BehaviourTaskTester pAsset7 = behaviourTaskTester7;
    this.t = behaviourTaskTester7;
    this.add(pAsset7);
    this.t.addBeh((BehaviourActionTester) new TesterBehScreenshotTooltips(false));
    this.t.addBeh((BehaviourActionTester) new TesterBehScrollWindow());
    BehaviourTaskTester behaviourTaskTester8 = new BehaviourTaskTester();
    behaviourTaskTester8.id = "setup_window_test";
    BehaviourTaskTester pAsset8 = behaviourTaskTester8;
    this.t = behaviourTaskTester8;
    this.add(pAsset8);
    this.t.addBeh((BehaviourActionTester) new TesterBehResetTweens());
    this.t.addBeh((BehaviourActionTester) new TesterBehSetResolution(562, 1000, "iPhone 7 66x"));
    this.t.addBeh((BehaviourActionTester) new TesterBehLoadWorld(1, "mapTemplates/Editor/map_windows"));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    this.t.addBeh((BehaviourActionTester) new TesterBehSaveWorldIfEmpty(1));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    this.t.addBeh((BehaviourActionTester) new TesterBehCheckWorld());
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    BehaviourTaskTester behaviourTaskTester9 = new BehaviourTaskTester();
    behaviourTaskTester9.id = "reset_tweens";
    BehaviourTaskTester pAsset9 = behaviourTaskTester9;
    this.t = behaviourTaskTester9;
    this.add(pAsset9);
    this.t.addBeh((BehaviourActionTester) new TesterBehResetTweens());
    BehaviourTaskTester behaviourTaskTester10 = new BehaviourTaskTester();
    behaviourTaskTester10.id = "next_language";
    BehaviourTaskTester pAsset10 = behaviourTaskTester10;
    this.t = behaviourTaskTester10;
    this.add(pAsset10);
    this.t.addBeh((BehaviourActionTester) new TesterBehSetNextLanguage());
    this.t.addBeh((BehaviourActionTester) new TesterBehScreenshotFolder());
    BehaviourTaskTester behaviourTaskTester11 = new BehaviourTaskTester();
    behaviourTaskTester11.id = "add_language_file";
    BehaviourTaskTester pAsset11 = behaviourTaskTester11;
    this.t = behaviourTaskTester11;
    this.add(pAsset11);
    this.t.addBeh((BehaviourActionTester) new TesterBehCopyCurrentLanguage());
    BehaviourTaskTester behaviourTaskTester12 = new BehaviourTaskTester();
    behaviourTaskTester12.id = "prepare_window_testdata";
    BehaviourTaskTester pAsset12 = behaviourTaskTester12;
    this.t = behaviourTaskTester12;
    this.add(pAsset12);
    this.t.addBeh((BehaviourActionTester) new TesterBehSetupWindowTest());
    BehaviourTaskTester behaviourTaskTester13 = new BehaviourTaskTester();
    behaviourTaskTester13.id = "clear_window_testdata";
    BehaviourTaskTester pAsset13 = behaviourTaskTester13;
    this.t = behaviourTaskTester13;
    this.add(pAsset13);
    this.t.addBeh((BehaviourActionTester) new TesterBehClearWindowTest());
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    BehaviourTaskTester behaviourTaskTester14 = new BehaviourTaskTester();
    behaviourTaskTester14.id = "fill_world_lava";
    BehaviourTaskTester pAsset14 = behaviourTaskTester14;
    this.t = behaviourTaskTester14;
    this.add(pAsset14);
    this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("lava0"));
    this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("lava1"));
    this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("lava2"));
    this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("lava3"));
    BehaviourTaskTester behaviourTaskTester15 = new BehaviourTaskTester();
    behaviourTaskTester15.id = "fill_world_pit";
    BehaviourTaskTester pAsset15 = behaviourTaskTester15;
    this.t = behaviourTaskTester15;
    this.add(pAsset15);
    for (int index = 0; index < 50; ++index)
      this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("pit_close_ocean"));
    BehaviourTaskTester behaviourTaskTester16 = new BehaviourTaskTester();
    behaviourTaskTester16.id = "fill_world_water";
    BehaviourTaskTester pAsset16 = behaviourTaskTester16;
    this.t = behaviourTaskTester16;
    this.add(pAsset16);
    for (int index = 0; index < 50; ++index)
      this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("deep_ocean"));
    BehaviourTaskTester behaviourTaskTester17 = new BehaviourTaskTester();
    behaviourTaskTester17.id = "fill_world_soil";
    BehaviourTaskTester pAsset17 = behaviourTaskTester17;
    this.t = behaviourTaskTester17;
    this.add(pAsset17);
    for (int index = 0; index < 50; ++index)
      this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("soil_low"));
    BehaviourTaskTester behaviourTaskTester18 = new BehaviourTaskTester();
    behaviourTaskTester18.id = "fill_world_randomly";
    BehaviourTaskTester pAsset18 = behaviourTaskTester18;
    this.t = behaviourTaskTester18;
    this.add(pAsset18);
    for (int index = 0; index < 50; ++index)
      this.t.addBeh((BehaviourActionTester) new TesterBehFillWorld("random"));
    BehaviourTaskTester behaviourTaskTester19 = new BehaviourTaskTester();
    behaviourTaskTester19.id = "destroy_sim_objects";
    BehaviourTaskTester pAsset19 = behaviourTaskTester19;
    this.t = behaviourTaskTester19;
    this.add(pAsset19);
    this.t.addBeh((BehaviourActionTester) new TesterBehDestroySimObjects());
    BehaviourTaskTester behaviourTaskTester20 = new BehaviourTaskTester();
    behaviourTaskTester20.id = "end_test";
    BehaviourTaskTester pAsset20 = behaviourTaskTester20;
    this.t = behaviourTaskTester20;
    this.add(pAsset20);
    this.t.addBeh((BehaviourActionTester) new TesterBehEndJobTest());
    BehaviourTaskTester behaviourTaskTester21 = new BehaviourTaskTester();
    behaviourTaskTester21.id = "restart_test";
    BehaviourTaskTester pAsset21 = behaviourTaskTester21;
    this.t = behaviourTaskTester21;
    this.add(pAsset21);
    this.t.addBeh((BehaviourActionTester) new TesterBehRestartJobTest());
    BehaviourTaskTester behaviourTaskTester22 = new BehaviourTaskTester();
    behaviourTaskTester22.id = "stop_autotester";
    BehaviourTaskTester pAsset22 = behaviourTaskTester22;
    this.t = behaviourTaskTester22;
    this.add(pAsset22);
    this.t.addBeh((BehaviourActionTester) new TesterBehEndAutoTester());
    BehaviourTaskTester behaviourTaskTester23 = new BehaviourTaskTester();
    behaviourTaskTester23.id = "shutdown";
    BehaviourTaskTester pAsset23 = behaviourTaskTester23;
    this.t = behaviourTaskTester23;
    this.add(pAsset23);
    this.t.addBeh((BehaviourActionTester) new TesterBehShutdown());
    BehaviourTaskTester behaviourTaskTester24 = new BehaviourTaskTester();
    behaviourTaskTester24.id = "set_speed_1";
    BehaviourTaskTester pAsset24 = behaviourTaskTester24;
    this.t = behaviourTaskTester24;
    this.add(pAsset24);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Changing game speed"));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldSpeed("x1"));
    BehaviourTaskTester behaviourTaskTester25 = new BehaviourTaskTester();
    behaviourTaskTester25.id = "set_speed_5";
    BehaviourTaskTester pAsset25 = behaviourTaskTester25;
    this.t = behaviourTaskTester25;
    this.add(pAsset25);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Changing game speed"));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldSpeed("x5"));
    BehaviourTaskTester behaviourTaskTester26 = new BehaviourTaskTester();
    behaviourTaskTester26.id = "set_speed_sonic";
    BehaviourTaskTester pAsset26 = behaviourTaskTester26;
    this.t = behaviourTaskTester26;
    this.add(pAsset26);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Changing game speed"));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldSpeed("x40"));
    BehaviourTaskTester behaviourTaskTester27 = new BehaviourTaskTester();
    behaviourTaskTester27.id = "set_speed_sonic_5";
    BehaviourTaskTester pAsset27 = behaviourTaskTester27;
    this.t = behaviourTaskTester27;
    this.add(pAsset27);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Changing game speed"));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldSpeed("x200"));
    BehaviourTaskTester behaviourTaskTester28 = new BehaviourTaskTester();
    behaviourTaskTester28.id = "pause";
    BehaviourTaskTester pAsset28 = behaviourTaskTester28;
    this.t = behaviourTaskTester28;
    this.add(pAsset28);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Pausing game"));
    this.t.addBeh((BehaviourActionTester) new TesterBehPause(true));
    BehaviourTaskTester behaviourTaskTester29 = new BehaviourTaskTester();
    behaviourTaskTester29.id = "unpause";
    BehaviourTaskTester pAsset29 = behaviourTaskTester29;
    this.t = behaviourTaskTester29;
    this.add(pAsset29);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Resuming game"));
    this.t.addBeh((BehaviourActionTester) new TesterBehPause(false));
    BehaviourTaskTester behaviourTaskTester30 = new BehaviourTaskTester();
    behaviourTaskTester30.id = "setup_laws";
    BehaviourTaskTester pAsset30 = behaviourTaskTester30;
    this.t = behaviourTaskTester30;
    this.add(pAsset30);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Setting up world laws"));
    this.t.addBeh((BehaviourActionTester) new TesterBehResetSeeds(123));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldLaw("world_law_hunger", false));
    this.t.addBeh((BehaviourActionTester) new TesterBehChangeWorldLaw("world_law_old_age", false));
    BehaviourTaskTester behaviourTaskTester31 = new BehaviourTaskTester();
    behaviourTaskTester31.id = "try_new_city";
    BehaviourTaskTester pAsset31 = behaviourTaskTester31;
    this.t = behaviourTaskTester31;
    this.add(pAsset31);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Spawning 50 units to build a city"));
    this.t.addBeh((BehaviourActionTester) new TesterBehFindTileForCity());
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomCivUnit(50, "tile_target"));
    BehaviourTaskTester behaviourTaskTester32 = new BehaviourTaskTester();
    behaviourTaskTester32.id = "wait_for_cities";
    BehaviourTaskTester pAsset32 = behaviourTaskTester32;
    this.t = behaviourTaskTester32;
    this.add(pAsset32);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 3 cities"));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitFor("city", 3));
    BehaviourTaskTester behaviourTaskTester33 = new BehaviourTaskTester();
    behaviourTaskTester33.id = "cull_mobs";
    BehaviourTaskTester pAsset33 = behaviourTaskTester33;
    this.t = behaviourTaskTester33;
    this.add(pAsset33);
    this.t.addBeh((BehaviourActionTester) new TesterBehRequire("unit", 1000));
    this.t.addBeh((BehaviourActionTester) new TesterBehCullMobs());
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(0.5f));
    BehaviourTaskTester behaviourTaskTester34 = new BehaviourTaskTester();
    behaviourTaskTester34.id = "fix_water";
    BehaviourTaskTester pAsset34 = behaviourTaskTester34;
    this.t = behaviourTaskTester34;
    this.add(pAsset34);
    this.t.addBeh((BehaviourActionTester) new TesterBehRequireUnits("god_finger", 25, RequireCondition.AtMost));
    this.t.addBeh((BehaviourActionTester) new TesterBehRequireGroundRatio(0.3f, RequireCondition.AtMost));
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnPowerActor("god_finger", 50));
    BehaviourTaskTester behaviourTaskTester35 = new BehaviourTaskTester();
    behaviourTaskTester35.id = "cull_godfinger";
    BehaviourTaskTester pAsset35 = behaviourTaskTester35;
    this.t = behaviourTaskTester35;
    this.add(pAsset35);
    this.t.addBeh((BehaviourActionTester) new TesterBehRequireUnits("god_finger", 1));
    this.t.addBeh((BehaviourActionTester) new TesterBehRequireGroundRatio(0.5f));
    this.t.addBeh((BehaviourActionTester) new TesterBehCullUnits("god_finger"));
    BehaviourTaskTester behaviourTaskTester36 = new BehaviourTaskTester();
    behaviourTaskTester36.id = "cull_units";
    BehaviourTaskTester pAsset36 = behaviourTaskTester36;
    this.t = behaviourTaskTester36;
    this.add(pAsset36);
    this.t.addBeh((BehaviourActionTester) new TesterBehRequire("unit", 1000));
    this.t.addBeh((BehaviourActionTester) new TesterBehClearFavorites());
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnPower("infinity_coin"));
    BehaviourTaskTester behaviourTaskTester37 = new BehaviourTaskTester();
    behaviourTaskTester37.id = "pick_random_meta_objects_graph";
    BehaviourTaskTester pAsset37 = behaviourTaskTester37;
    this.t = behaviourTaskTester37;
    this.add(pAsset37);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Picking random meta objects"));
    this.t.addBeh((BehaviourActionTester) new TesterBehSelectRandomMetaObjects(true));
    BehaviourTaskTester behaviourTaskTester38 = new BehaviourTaskTester();
    behaviourTaskTester38.id = "pick_random_meta_objects";
    BehaviourTaskTester pAsset38 = behaviourTaskTester38;
    this.t = behaviourTaskTester38;
    this.add(pAsset38);
    this.t.addBeh((BehaviourActionTester) new TesterBehSelectRandomMetaObjects());
    BehaviourTaskTester behaviourTaskTester39 = new BehaviourTaskTester();
    behaviourTaskTester39.id = "open_gene_editor";
    BehaviourTaskTester pAsset39 = behaviourTaskTester39;
    this.t = behaviourTaskTester39;
    this.add(pAsset39);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Opening subspecies window with gene editor tab"));
    this.t.addBeh((BehaviourActionTester) new TesterBehSelectRandomMetaObjects());
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("subspecies"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindowTab("Genetics"));
    BehaviourTaskTester behaviourTaskTester40 = new BehaviourTaskTester();
    behaviourTaskTester40.id = "open_city_chart_window";
    BehaviourTaskTester pAsset40 = behaviourTaskTester40;
    this.t = behaviourTaskTester40;
    this.add(pAsset40);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Opening city window with chart tab"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("city"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindowTab("Statistics"));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    BehaviourTaskTester behaviourTaskTester41 = new BehaviourTaskTester();
    behaviourTaskTester41.id = "open_kingdom_chart_window";
    BehaviourTaskTester pAsset41 = behaviourTaskTester41;
    this.t = behaviourTaskTester41;
    this.add(pAsset41);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Opening kingdom window with chart tab"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("kingdom"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindowTab("Statistics"));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehClickRandomButton(typeof (ButtonGraphCategory)));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    BehaviourTaskTester behaviourTaskTester42 = new BehaviourTaskTester();
    behaviourTaskTester42.id = "open_city_window";
    BehaviourTaskTester pAsset42 = behaviourTaskTester42;
    this.t = behaviourTaskTester42;
    this.add(pAsset42);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Opening city window"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("city"));
    BehaviourTaskTester behaviourTaskTester43 = new BehaviourTaskTester();
    behaviourTaskTester43.id = "random_meta_switch";
    BehaviourTaskTester pAsset43 = behaviourTaskTester43;
    this.t = behaviourTaskTester43;
    this.add(pAsset43);
    this.t.addBeh((BehaviourActionTester) new TesterBehRandomMetaSwitch());
    BehaviourTaskTester behaviourTaskTester44 = new BehaviourTaskTester();
    behaviourTaskTester44.id = "open_kingdom_window";
    BehaviourTaskTester pAsset44 = behaviourTaskTester44;
    this.t = behaviourTaskTester44;
    this.add(pAsset44);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Opening kingdom window"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("kingdom"));
    BehaviourTaskTester behaviourTaskTester45 = new BehaviourTaskTester();
    behaviourTaskTester45.id = "random_window_tab";
    BehaviourTaskTester pAsset45 = behaviourTaskTester45;
    this.t = behaviourTaskTester45;
    this.add(pAsset45);
    this.t.addBeh((BehaviourActionTester) new TesterBehRandomWindowTab());
    Random random;
    // ISSUE: explicit constructor call
    ((Random) ref random).\u002Ector(100U);
    BehaviourTaskTester behaviourTaskTester46 = new BehaviourTaskTester();
    behaviourTaskTester46.id = "random_bombs_and_kingdoms";
    BehaviourTaskTester pAsset46 = behaviourTaskTester46;
    this.t = behaviourTaskTester46;
    this.add(pAsset46);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Spawning random units and bombs"));
    int pWaitYears = ((Random) ref random).NextInt(2, 5);
    int num = ((Random) ref random).NextInt(25, 50);
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitYears(pWaitYears));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitForYear());
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Spawning units and bombs"));
    for (int index = 0; index < num; ++index)
      this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomKingdomUnit());
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomBomb());
    BehaviourTaskTester behaviourTaskTester47 = new BehaviourTaskTester();
    behaviourTaskTester47.id = "show_compare_window";
    BehaviourTaskTester pAsset47 = behaviourTaskTester47;
    this.t = behaviourTaskTester47;
    this.add(pAsset47);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Showing chart compare window"));
    this.t.addBeh((BehaviourActionTester) new TesterBehOpenWindow("chart_comparer"));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    this.t.addBeh((BehaviourActionTester) new TesterBehCloseWindows());
    BehaviourTaskTester behaviourTaskTester48 = new BehaviourTaskTester();
    behaviourTaskTester48.id = "wait_05";
    BehaviourTaskTester pAsset48 = behaviourTaskTester48;
    this.t = behaviourTaskTester48;
    this.add(pAsset48);
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(0.5f));
    BehaviourTaskTester behaviourTaskTester49 = new BehaviourTaskTester();
    behaviourTaskTester49.id = "wait_1";
    BehaviourTaskTester pAsset49 = behaviourTaskTester49;
    this.t = behaviourTaskTester49;
    this.add(pAsset49);
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(1f));
    BehaviourTaskTester behaviourTaskTester50 = new BehaviourTaskTester();
    behaviourTaskTester50.id = "wait_5";
    BehaviourTaskTester pAsset50 = behaviourTaskTester50;
    this.t = behaviourTaskTester50;
    this.add(pAsset50);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 5 game seconds..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(5f));
    BehaviourTaskTester behaviourTaskTester51 = new BehaviourTaskTester();
    behaviourTaskTester51.id = "wait_10";
    BehaviourTaskTester pAsset51 = behaviourTaskTester51;
    this.t = behaviourTaskTester51;
    this.add(pAsset51);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 10 game seconds..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(10f));
    BehaviourTaskTester behaviourTaskTester52 = new BehaviourTaskTester();
    behaviourTaskTester52.id = "wait_20";
    BehaviourTaskTester pAsset52 = behaviourTaskTester52;
    this.t = behaviourTaskTester52;
    this.add(pAsset52);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 20 game seconds..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(20f));
    BehaviourTaskTester behaviourTaskTester53 = new BehaviourTaskTester();
    behaviourTaskTester53.id = "wait_years_1";
    BehaviourTaskTester pAsset53 = behaviourTaskTester53;
    this.t = behaviourTaskTester53;
    this.add(pAsset53);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 1 year..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitYears(1));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitForYear());
    BehaviourTaskTester behaviourTaskTester54 = new BehaviourTaskTester();
    behaviourTaskTester54.id = "wait_years_5";
    BehaviourTaskTester pAsset54 = behaviourTaskTester54;
    this.t = behaviourTaskTester54;
    this.add(pAsset54);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 5 years..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitYears(5));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitForYear());
    BehaviourTaskTester behaviourTaskTester55 = new BehaviourTaskTester();
    behaviourTaskTester55.id = "wait_years_10";
    BehaviourTaskTester pAsset55 = behaviourTaskTester55;
    this.t = behaviourTaskTester55;
    this.add(pAsset55);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 10 years..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitYears(10));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitForYear());
    BehaviourTaskTester behaviourTaskTester56 = new BehaviourTaskTester();
    behaviourTaskTester56.id = "wait_years_20";
    BehaviourTaskTester pAsset56 = behaviourTaskTester56;
    this.t = behaviourTaskTester56;
    this.add(pAsset56);
    this.t.addBeh((BehaviourActionTester) new TesterBehLog("Waiting for 20 years..."));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitYears(20));
    this.t.addBeh((BehaviourActionTester) new TesterBehWaitForYear());
    BehaviourTaskTester behaviourTaskTester57 = new BehaviourTaskTester();
    behaviourTaskTester57.id = "spawn_random_power";
    BehaviourTaskTester pAsset57 = behaviourTaskTester57;
    this.t = behaviourTaskTester57;
    this.add(pAsset57);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomPower());
    this.t.addBeh((BehaviourActionTester) new TesterBehWait(0.1f));
    BehaviourTaskTester behaviourTaskTester58 = new BehaviourTaskTester();
    behaviourTaskTester58.id = "randomize_subspecies_traits";
    BehaviourTaskTester pAsset58 = behaviourTaskTester58;
    this.t = behaviourTaskTester58;
    this.add(pAsset58);
    this.t.addBeh((BehaviourActionTester) new TesterMutateSubspeciesTraits());
    BehaviourTaskTester behaviourTaskTester59 = new BehaviourTaskTester();
    behaviourTaskTester59.id = "randomize_subspecies_genes";
    BehaviourTaskTester pAsset59 = behaviourTaskTester59;
    this.t = behaviourTaskTester59;
    this.add(pAsset59);
    this.t.addBeh((BehaviourActionTester) new TesterMutateSubspeciesGenes());
    BehaviourTaskTester behaviourTaskTester60 = new BehaviourTaskTester();
    behaviourTaskTester60.id = "randomize_actor_traits";
    BehaviourTaskTester pAsset60 = behaviourTaskTester60;
    this.t = behaviourTaskTester60;
    this.add(pAsset60);
    this.t.addBeh((BehaviourActionTester) new TesterMutateActorTraits());
    BehaviourTaskTester behaviourTaskTester61 = new BehaviourTaskTester();
    behaviourTaskTester61.id = "randomize_actor_status";
    BehaviourTaskTester pAsset61 = behaviourTaskTester61;
    this.t = behaviourTaskTester61;
    this.add(pAsset61);
    this.t.addBeh((BehaviourActionTester) new TesterMutateActorStatus());
    BehaviourTaskTester behaviourTaskTester62 = new BehaviourTaskTester();
    behaviourTaskTester62.id = "spawn_infinity_coin";
    BehaviourTaskTester pAsset62 = behaviourTaskTester62;
    this.t = behaviourTaskTester62;
    this.add(pAsset62);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnPower("infinity_coin"));
    BehaviourTaskTester behaviourTaskTester63 = new BehaviourTaskTester();
    behaviourTaskTester63.id = "spawn_random_unit";
    BehaviourTaskTester pAsset63 = behaviourTaskTester63;
    this.t = behaviourTaskTester63;
    this.add(pAsset63);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomUnit());
    BehaviourTaskTester behaviourTaskTester64 = new BehaviourTaskTester();
    behaviourTaskTester64.id = "spawn_random_unit_5";
    BehaviourTaskTester pAsset64 = behaviourTaskTester64;
    this.t = behaviourTaskTester64;
    this.add(pAsset64);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomUnit(5));
    BehaviourTaskTester behaviourTaskTester65 = new BehaviourTaskTester();
    behaviourTaskTester65.id = "spawn_random_unit_10";
    BehaviourTaskTester pAsset65 = behaviourTaskTester65;
    this.t = behaviourTaskTester65;
    this.add(pAsset65);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomUnit(10));
    BehaviourTaskTester behaviourTaskTester66 = new BehaviourTaskTester();
    behaviourTaskTester66.id = "spawn_random_building";
    BehaviourTaskTester pAsset66 = behaviourTaskTester66;
    this.t = behaviourTaskTester66;
    this.add(pAsset66);
    this.t.addBeh((BehaviourActionTester) new TesterBehSpawnRandomBuilding());
    BehaviourTaskTester behaviourTaskTester67 = new BehaviourTaskTester();
    behaviourTaskTester67.id = "generate_map_random";
    BehaviourTaskTester pAsset67 = behaviourTaskTester67;
    this.t = behaviourTaskTester67;
    this.add(pAsset67);
    this.t.addBeh((BehaviourActionTester) new TesterBehGenerateMap());
    BehaviourTaskTester behaviourTaskTester68 = new BehaviourTaskTester();
    behaviourTaskTester68.id = "super_damage_units";
    BehaviourTaskTester pAsset68 = behaviourTaskTester68;
    this.t = behaviourTaskTester68;
    this.add(pAsset68);
    this.t.addBeh((BehaviourActionTester) new TesterBehSuperDamageToUnits());
  }

  public override void editorDiagnosticLocales()
  {
  }
}
