// Decompiled with JetBrains decompiler
// Type: WorldBehaviourLibrary
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EAF20368-35E7-4BB6-B082-5477D61019A6
// Assembly location: C:\Users\Takko\Downloads\Worldbox .NET\Assembly-CSharp.dll

#nullable disable
public class WorldBehaviourLibrary : AssetLibrary<WorldBehaviourAsset>
{
  public override void init()
  {
    base.init();
    WorldBehaviourAsset pAsset1 = new WorldBehaviourAsset();
    pAsset1.id = "grin_reaper";
    pAsset1.interval = 0.01f;
    pAsset1.interval_random = 0.01f;
    pAsset1.stop_when_world_on_pause = false;
    pAsset1.action = new WorldBehaviourAction(WorldBehaviourActions.updateGrinReaper);
    pAsset1.action_world_clear = new WorldBehaviourAction(WorldBehaviourActions.clearGrinReaper);
    this.add(pAsset1);
    WorldBehaviourAsset pAsset2 = new WorldBehaviourAsset();
    pAsset2.id = "zones_meta_data_visualizer";
    pAsset2.interval = 0.4f;
    pAsset2.interval_random = 0.0f;
    pAsset2.stop_when_world_on_pause = false;
    pAsset2.action = new WorldBehaviourAction(ZoneMetaDataVisualizer.updateMetaZones);
    this.add(pAsset2);
    WorldBehaviourAsset pAsset3 = new WorldBehaviourAsset();
    pAsset3.id = "debug_highlight";
    pAsset3.interval = 0.1f;
    pAsset3.interval_random = 0.0f;
    pAsset3.stop_when_world_on_pause = false;
    pAsset3.action = new WorldBehaviourAction(DebugHighlight.updateDebugHighlights);
    this.add(pAsset3);
    WorldBehaviourAsset pAsset4 = new WorldBehaviourAsset();
    pAsset4.id = "disasters";
    pAsset4.interval = 80f;
    pAsset4.interval_random = 0.0f;
    pAsset4.action = new WorldBehaviourAction(WorldBehaviourActions.updateDisasters);
    this.add(pAsset4);
    WorldBehaviourAsset pAsset5 = new WorldBehaviourAsset();
    pAsset5.id = "migrants";
    pAsset5.interval = 80f;
    pAsset5.interval_random = 0.0f;
    pAsset5.action = new WorldBehaviourAction(WorldBehaviourActions.updateMigrants);
    this.add(pAsset5);
    WorldBehaviourAsset pAsset6 = new WorldBehaviourAsset();
    pAsset6.id = "decay_roads";
    pAsset6.interval = 1f;
    pAsset6.interval_random = 1f;
    pAsset6.action = new WorldBehaviourAction(WorldBehaviourActions.updateRoadDecay);
    this.add(pAsset6);
    WorldBehaviourAsset pAsset7 = new WorldBehaviourAsset();
    pAsset7.id = "decay_farms";
    pAsset7.interval = 1f;
    pAsset7.interval_random = 1f;
    pAsset7.action = new WorldBehaviourAction(WorldBehaviourActions.updateFarmDecay);
    pAsset7.action_world_clear = new WorldBehaviourAction(WorldBehaviourActions.clearFarmDecay);
    this.add(pAsset7);
    WorldBehaviourAsset pAsset8 = new WorldBehaviourAsset();
    pAsset8.id = "spawn_random_vegetation";
    pAsset8.interval = 10f;
    pAsset8.interval_random = 10f;
    pAsset8.action = new WorldBehaviourAction(WorldBehaviourActions.spawnRandomVegetation);
    this.add(pAsset8);
    WorldBehaviourAsset pAsset9 = new WorldBehaviourAsset();
    pAsset9.id = "spawn_minerals";
    pAsset9.interval = 2f;
    pAsset9.interval_random = 3f;
    pAsset9.action = new WorldBehaviourAction(WorldBehaviourActions.growMinerals);
    this.add(pAsset9);
    WorldBehaviourAsset pAsset10 = new WorldBehaviourAsset();
    pAsset10.id = "building_sparks";
    pAsset10.interval = 0.1f;
    pAsset10.interval_random = 1f;
    pAsset10.enabled_on_minimap = false;
    pAsset10.action = new WorldBehaviourAction(WorldBehaviourActions.buildingSparks);
    this.add(pAsset10);
    WorldBehaviourAsset pAsset11 = new WorldBehaviourAsset();
    pAsset11.id = "unit_spawn";
    pAsset11.interval = 24.5f;
    pAsset11.interval_random = 30f;
    pAsset11.action = new WorldBehaviourAction(WorldBehaviourActions.updateUnitSpawn);
    this.add(pAsset11);
    WorldBehaviourAsset pAsset12 = new WorldBehaviourAsset();
    pAsset12.id = "ruins_rat_spawn";
    pAsset12.interval = 30.5f;
    pAsset12.interval_random = 3f;
    pAsset12.action = new WorldBehaviourAction(WorldBehaviourActions.updateRuinRatSpawn);
    this.add(pAsset12);
    WorldBehaviourAsset pAsset13 = new WorldBehaviourAsset();
    pAsset13.id = "creep_decay";
    pAsset13.interval = 1f;
    pAsset13.interval_random = 0.3f;
    pAsset13.action = new WorldBehaviourAction(WorldBehaviourActionCreepDecay.checkCreep);
    pAsset13.action_world_clear = new WorldBehaviourAction(WorldBehaviourActionCreepDecay.clear);
    this.add(pAsset13);
    WorldBehaviourAsset pAsset14 = new WorldBehaviourAsset();
    pAsset14.id = "ocean";
    pAsset14.interval = 0.2f;
    pAsset14.interval_random = 0.0f;
    pAsset14.action = new WorldBehaviourAction(WorldBehaviourOcean.updateOcean);
    pAsset14.action_world_clear = new WorldBehaviourAction(WorldBehaviourOcean.clear);
    this.add(pAsset14);
    WorldBehaviourAsset pAsset15 = new WorldBehaviourAsset();
    pAsset15.id = "tiles_freeze";
    pAsset15.interval = 0.1f;
    pAsset15.interval_random = 0.0f;
    pAsset15.action = new WorldBehaviourAction(WorldBehaviourTilesTemperatureFreeze.update);
    pAsset15.action_world_clear = new WorldBehaviourAction(WorldBehaviourTilesRunner.clearTilesToCheck);
    this.add(pAsset15);
    WorldBehaviourAsset pAsset16 = new WorldBehaviourAsset();
    pAsset16.id = "tiles_unfreeze";
    pAsset16.interval = 0.01f;
    pAsset16.interval_random = 0.0f;
    pAsset16.action = new WorldBehaviourAction(WorldBehaviourTilesTemperatureUnFreeze.update);
    pAsset16.action_world_clear = new WorldBehaviourAction(WorldBehaviourTilesRunner.clearTilesToCheck);
    this.add(pAsset16);
    WorldBehaviourAsset pAsset17 = new WorldBehaviourAsset();
    pAsset17.id = "biomes";
    pAsset17.interval = 0.05f;
    pAsset17.interval_random = 0.05f;
    pAsset17.action = new WorldBehaviourAction(WorldBehaviourActionBiomes.update);
    pAsset17.action_world_clear = new WorldBehaviourAction(WorldBehaviourActionBiomes.clear);
    this.add(pAsset17);
    WorldBehaviourAsset pAsset18 = new WorldBehaviourAsset();
    pAsset18.id = "lava";
    pAsset18.interval = 0.05f;
    pAsset18.interval_random = 0.05f;
    pAsset18.action = new WorldBehaviourAction(WorldBehaviourActionLava.update);
    pAsset18.action_world_clear = new WorldBehaviourAction(WorldBehaviourTilesRunner.clearTilesToCheck);
    this.add(pAsset18);
    WorldBehaviourAsset pAsset19 = new WorldBehaviourAsset();
    pAsset19.id = "fire";
    pAsset19.interval = 1f;
    pAsset19.interval_random = 0.0f;
    pAsset19.action = new WorldBehaviourAction(WorldBehaviourActionFire.updateFire);
    pAsset19.action_world_clear = new WorldBehaviourAction(WorldBehaviourActionFire.clear);
    this.add(pAsset19);
    WorldBehaviourAsset pAsset20 = new WorldBehaviourAsset();
    pAsset20.id = "burned_tiles";
    pAsset20.interval = 3f;
    pAsset20.interval_random = 5f;
    pAsset20.action = new WorldBehaviourAction(WorldBehaviourActionBurnedTiles.updateBurnedTiles);
    pAsset20.action_world_clear = new WorldBehaviourAction(WorldBehaviourActionBurnedTiles.clear);
    this.add(pAsset20);
    WorldBehaviourAsset pAsset21 = new WorldBehaviourAsset();
    pAsset21.id = "erosion";
    pAsset21.interval = 3f;
    pAsset21.interval_random = 1f;
    pAsset21.action = new WorldBehaviourAction(WorldBehaviourActionErosion.updateErosion);
    pAsset21.action_world_clear = new WorldBehaviourAction(WorldBehaviourActionErosion.clear);
    this.add(pAsset21);
    WorldBehaviourAsset pAsset22 = new WorldBehaviourAsset();
    pAsset22.id = "biome_inferno_fires";
    pAsset22.interval = 0.5f;
    pAsset22.interval_random = 1f;
    pAsset22.action = new WorldBehaviourAction(WorldBehaviourActionInferno.updateInfernoFireAction);
    pAsset22.enabled_on_minimap = false;
    this.add(pAsset22);
    WorldBehaviourAsset pAsset23 = new WorldBehaviourAsset();
    pAsset23.id = "biome_inferno_tile_low_animations";
    pAsset23.interval = 0.5f;
    pAsset23.interval_random = 0.5f;
    pAsset23.action = new WorldBehaviourAction(WorldBehaviourActionInferno.updateInfernalLowAnimations);
    pAsset23.enabled_on_minimap = false;
    this.add(pAsset23);
    WorldBehaviourAsset pAsset24 = new WorldBehaviourAsset();
    pAsset24.id = "biome_singularity_tile_animations";
    pAsset24.interval = 0.5f;
    pAsset24.interval_random = 0.5f;
    pAsset24.action = new WorldBehaviourAction(WorldBehaviourActionSingularity.updateSingularityTiles);
    pAsset24.enabled_on_minimap = false;
    this.add(pAsset24);
    WorldBehaviourAsset pAsset25 = new WorldBehaviourAsset();
    pAsset25.id = "creep_biomass";
    pAsset25.interval = 0.1f;
    pAsset25.interval_random = 0.1f;
    pAsset25.action = new WorldBehaviourAction(WorldBehaviourActionCreepBiomass.updateBiomassTiles);
    pAsset25.enabled_on_minimap = false;
    this.add(pAsset25);
    WorldBehaviourAsset pAsset26 = new WorldBehaviourAsset();
    pAsset26.id = "biome_low_swamp_animations";
    pAsset26.interval = 0.1f;
    pAsset26.interval_random = 0.1f;
    pAsset26.action = new WorldBehaviourAction(WorldBehaviourActionSwampAnimation.updateSwampTiles);
    pAsset26.enabled_on_minimap = false;
    this.add(pAsset26);
    WorldBehaviourAsset pAsset27 = new WorldBehaviourAsset();
    pAsset27.id = "unit_temperatures";
    pAsset27.interval = 0.1f;
    pAsset27.interval_random = 0.1f;
    pAsset27.action = new WorldBehaviourAction(WorldBehaviourUnitTemperatures.updateUnitTemperatures);
    pAsset27.action_world_clear = new WorldBehaviourAction(WorldBehaviourUnitTemperatures.clear);
    this.add(pAsset27);
    WorldBehaviourAsset pAsset28 = new WorldBehaviourAsset();
    pAsset28.id = "waves";
    pAsset28.interval = 0.1f;
    pAsset28.interval_random = 0.1f;
    pAsset28.enabled_on_minimap = false;
    pAsset28.action = new WorldBehaviourAction(WorldBehaviourTileEffects.tryToStartTileEffects);
    this.add(pAsset28);
    WorldBehaviourAsset pAsset29 = new WorldBehaviourAsset();
    pAsset29.id = "clouds";
    pAsset29.interval = 1f;
    pAsset29.interval_random = 1f;
    pAsset29.action = new WorldBehaviourAction(WorldBehaviourClouds.spawnRandomCloud);
    this.add(pAsset29);
    WorldBehaviourAsset pAsset30 = new WorldBehaviourAsset();
    pAsset30.id = "achievements_checks";
    pAsset30.interval = 5f;
    pAsset30.action = (WorldBehaviourAction) (() =>
    {
      AchievementLibrary.great_plague.check();
      AchievementLibrary.eternal_chaos.checkBySignal();
      AchievementLibrary.minefield.checkBySignal();
      AchievementLibrary.rain_tornado.checkBySignal();
      AchievementLibrary.ancient_war_of_geometry_and_evil.checkBySignal();
    });
    this.add(pAsset30);
  }

  public void createManagers()
  {
    foreach (WorldBehaviourAsset pAsset in this.list)
      pAsset.manager = new WorldBehaviour(pAsset);
  }
}
